### ISSUE TITLE
DotVVM 3 - Dictionary values not rendered

### ISSUE THREAD

**Issue by dnajcz** [riganti/dotvvm#1008]
When I start new DotVVM project and change DotVVM version to 3, I cannot use dictionaries in value binding?

I have in **DefualtViewModel.cs** definition:
`public Dictionary<string, bool> Pravidla { get; set; } = new Dictionary<string, bool>() { {"key1", true }, { "key2", false } };`

In **Default.dothtml** I put:
`<div>{{value: _root.Pravidla["key1"]}} - {{value: _root.Pravidla["key2"]}}</div>`

After Rebuild and run the project, no dictionary values are rendered. 

In browser dev. tools I can see proper values in __dot_viewmodel_root element:
```
 "viewModel": {
    "$type": "14T6z33hWTxwPvI4Zryl151VX+s=",
    "Pravidla": [
      {
        "Key": "key1",
        "Value": true
      },
      {
        "Key": "key2",
        "Value": false
      }
    ],
    "Title": "Hello from DotVVM!", 
...
```
So why it is not rendered properly in DotVVM 3.02 while in DotVVM 2.5.2 it is working ok?
Am I doing something wrong?

**Comment by exyi** [comment]
I'm sorry, but Dictionary is not supported in view models. I was never supported, although sometimes it worked by accident.

We should probably add support for indexing dictionaries. @acizmarik You are working on the JS translations, would you mind to also add Dictionary indexers?

**Comment by acizmarik** [comment]
Yes I think it is a good idea. I will add a translation for this as well
