### ISSUE TITLE
4.5 Framework Support

### ISSUE THREAD

**Issue by AMBULATUR** [riganti/dotvvm#1010]
Good day, there is a hosting on which i can run a web application only with the .net Framework 4.5 (.0) version, is it possible to somehow ignore and run DotVVM which requires the framework 4.5.1 version>= ?

**Comment by tomasherceg** [comment]
As stated [here](https://docs.microsoft.com/en-us/lifecycle/faq/dotnet-framework), the support of .NET 4.5 ended in 2016. 
It is possible that there is some hosting that still have only .NET 4.5, but I think it is more probable that they just forgot to update their website. 
If they install the latest updates on their servers, they'll probably have a higher version of .NET already installed (at least 4.5.2 which is still supported). And if they don't install updates, I'd rather not use such hosting.
