### ISSUE TITLE
Simple page does not work on IE11

### ISSUE THREAD

**Issue by neumatho** [riganti/dotvvm#1019]
It seems like the new 3.0.x version of DotVVM does not work on IE11. When showing a dothtml page, it comes up with the following error:

![error](https://user-images.githubusercontent.com/49920464/117952588-97f47e80-b315-11eb-9492-e34f2aa379fa.png)

It can be reproduced simply by using the standard project templates for Owin.

- Create new project of type "DotVVM Web Application (OWIN on .NET Framework".
- Compile and run in debug mode using IE11, it works fine.
- Update all packages to the newest version, so we get 3.0.3 of DotVVM.
- Compile and run again in debug mode, the error is shown.

**Comment by tomasherceg** [comment]
Thanks for the report, we'll investigate the issue. It seems that the scripts for IE11 don't contain polyfills they should have.

**Comment by tomasherceg** [comment]
We've just released DotVVM 3.0.4 which should fix the issue.
Sorry for the issue.
