### ISSUE TITLE
EmptyDataTemplate on Repeater and GridView

### ISSUE THREAD

**Issue by tomasherceg** [riganti/dotvvm#102]

**Comment by exyi** [comment]
we have `<dot:EmptyData>` control

**Comment by tomasherceg** [comment]
Oh, I didn't knew that.
However it would be nice to be able to set EmptyDataTemplate globally for all GridViews using styles.
Also, when the GridView points to an empty collection, the header is still being rendered.

We can keep the EmptyData control and if the user specifies the EmptyDataTemplate, we can use it internally in the controls to implement this feature.
