### ISSUE TITLE
Resource group

### ISSUE THREAD

**Issue by neumatho** [riganti/dotvvm#1025]
I'm really new to DotVVM, so if there already exist a solution for by proposal, then please point me to the right duration.

I have started porting an ASP.NET (framework) application to use DotVVM, because we want to upgrade to .NET Core/.NET 5. In this application, I have an advanced control that is written in TypeScript. It contains several TypeScript files, one for each class needed. Each file is compiled into its own JavaScript file.

As I can see it, it is only possible to add a single JavaScript file to a resource. It would be nice, if it is possible to add multiple locations into one resource, so when using that resource, all files will be included.

I do not know what is best, to add an extra property to ScriptResource as an array of IResourceLocation or create a new resource location class, but you know what is best :-)

**Comment by tomasherceg** [comment]
There are two ways how to achieve this:
* You can register multiple resources and specify their dependencies. Then, you can just require the "top" resource, and all dependent resources will be included automatically.
* Alternatively, you can use some JavaScript bundler (e. g. webpack or rollup) which can produce a single file from all of your JS resources. Then, you can just register this bundle. See https://dev.to/larswillemsens/managing-asp-net-core-mvc-front-end-dependencies-with-npm-and-webpack-part-1-3jf5 for more details.

**Comment by neumatho** [comment]
Option 2 is not a good idea when development, because the map files from generated when compiling the TypeScript files won't match and it will be hard to debug. Of course, such a solution can be used, when creating the production package.

Option 1 is a possibility and I was thinking of that first, but then I need to add each script file as independent resources and I think I got around 10 of them. It would be better if its possible to add a group, like something you have for routing.

**Comment by tomasherceg** [comment]
It's not a problem - webpack can create a source map for the bundle that points to the original files. 
https://survivejs.com/webpack/building/source-maps/
We are using it on many projects and it is quite convenient.

About multi-registration - DotVVM doesn't have any API for registering a group of resources, but it is quite easy to do it yourself - you can use foreach to enumerate the files in the specific folder and register all of them. The only thing I'd be worried about is the order in which the files are included.

**Comment by neumatho** [comment]
Maybe I can use the file scanning method. I will look into that. In this case, it doesn't matter in which order the files are included, since the TypeScript compiler creates some JavaScript that checks, if the object to put the functions in is already created or not.

**Comment by exyi** [comment]
Since there is an existing functionality (using Dependencies and registering many resources) that can do what you need, I'd close this issue. We don't want to add many features that do very similar things, that just makes the entire framework (even) more complex and hard to use.

If you have any further questions how to achieve what you need, feel free to comment here on github or chat with us on https://gitter.im/riganti/dotvvm
