### ISSUE TITLE
SpaContentPlaceHolder - obsolete comments (will) point to wrong url.

### ISSUE THREAD

**Issue by MichalTichy** [riganti/dotvvm#1027]
After release of doc for dotvvm 3.0 the comments describing the new SPA will point to wrong URL.

```
        /// <summary>
        /// Gets or sets the default name of the route that should be loaded when there is no hash part in the URL.
        /// </summary>
        [MarkupOptions(AllowBinding = false)]
        [Obsolete("The DefaultRouteName property is not supported - the classic SPA more (URLs with #/) was removed from DotVVM. See https://www.dotvvm.com/docs/tutorials/basics-single-page-applications-spa/latest for more details.")]
        public string? DefaultRouteName
        {
            get { return (string?)GetValue(DefaultRouteNameProperty); }
            set { SetValue(DefaultRouteNameProperty, value); }
        }
```

Also we should test whether the obsolete props are hidden in doc.

**Comment by tomasherceg** [comment]
The links can remain as they are - the docs site does the redirect to the most current version of the page. 
But there is a typo - "the classic SPA more" => "the classic SPA mode".

Also, I've noticed that we still have `UseHistoryApiSpaNavigation` property that should be obsoleted too.
