### ISSUE TITLE
Comprehensive fix of misspellings/typos

### ISSUE THREAD

**Issue by JosefPihrt** [riganti/dotvvm#1048]
Hi,

I would like to do a comprehensive fix of misspellings/typos in this project.

I developed tools specially for this purpose: [Roslynator](https://www.nuget.org/packages/Roslynator.CommandLine) (code files), [Orang](https://www.nuget.org/packages/Orang.DotNet.Cli) (text files), [Wordb](https://github.com/josefpihrt/wordb) (wordlists)

I have a couple of questions:
* Should US or British English be preferred?
* Are there any projects in which publicly visible types/members should not be fixed because they have been shipped as a part of public API/library?

**Comment by exyi** [comment]
Hi! Thanks a lot for your effort. US English should be preferred, but we are definitely not pedantic about it (I can't even tell the difference :facepalm:)

The DotVVM.Core, DotVVM.Framework, DotVVM.Framework.Hosting.AspNetCore, and DotVVM.Framework.Hosting.Owin are "public projects" and should avoid breaking changes in the API. However, could you please also run the checks on them (in a separate PR, preferably)? We could break some API in the next major version if it's used sparsely, add overloads with corrected spelling or avoid the breaking change in other ways, this depends on the specific case.

**Comment by exyi** [comment]
This is already merged
