### ISSUE TITLE
Extend the @wrapperTag directive

### ISSUE THREAD

**Issue by tomasherceg** [riganti/dotvvm#1053]
People from our front-end team had an idea to extend the possibilities of the `wrapperTag` directive in markup controls so they'll be able to specify CSS classes and attributes on the wrapper element without the need to have the code-behind class. 

```DOTHTML
@viewModel ...
@wrapperTag div[role=tab][aria-title=...].my-panel.col-6-xs
```

It would produce something like this:

```
<div role=tab aria-title=... class="my-panel col-6-xs">...</div>
```

**Comment by exyi** [comment]
I find this feature to be quite redundant - you can just use `@noWrapperTag` and wrap the control yourself.
