### ISSUE TITLE
Improve API for registering JS translations

### ISSUE THREAD

**Issue by acizmarik** [riganti/dotvvm#1063]
Current API for registering JS translations has a couple of issues:

- It is easy to reference a non-existing method
- It is easy to reference a method that is not available for all targetted frameworks (e.g. available for .NET 5 but not available for .NET Framework)
- Distinguishing between methods with numerous overloads is problematic (we are comparing individual parameter types)
- It is not future-proof, see #1034 on how easy it is to break our JS registrations system
- Also for more complex methods it can be considered as overly verbose and not easy to comprehend

**Solution**
- Add new API that better leverages capabilities of C# compiler
    - Capture a specific method invocation with arbitrary arguments (for example default values) using a lambda function
    - Such lambda function can be then stored as a LINQ expression that should be consisting of a single `MethodCallExpression` using which we can easily extract the target `MethodInfo`
- We can change all registrations in framework using this safer approach
- We can deprecate current (unsafe) API
- Note that with this safer approach no longer needs the complex method matching rountine that we are using today (although it needs to stay to remain compatible with the current API). Instead we are relying on the capabilities of C# compiler to give us the correct `MethodInfo`

**Example**
```csharp
Expression<Action> expr = () => Console.WriteLine(String.Empty);
var method = (expr.Body as MethodCallExpression).Method;
```
`method` is of type `RuntimeMethodInfo` and points exactly to a static method `WriteLine` that takes a single `string` argument.

**Comment by exyi** [comment]
This was done in #1608
