### ISSUE TITLE
Validator.InvalidCssClass and other properties not working when applied on GridViewColumn

### ISSUE THREAD

**Issue by tomasherceg** [riganti/dotvvm#1064]
Since the `GridViewColumn` itself is not a part of the control tree, the attached properties assigned to it are not inherited.
We should either "copy" them to the `td` element, or provide another way to apply these properties on the contents of the column (maybe add the `CellDecorators` property that will be similar to `RowDecorators`).

**Comment by mrnustik** [comment]
👍 for `CellDecorators`, this would also add the possibility to for example change the colour of a cell based on its value.

**Comment by tomasherceg** [comment]
Related to #153

**Comment by exyi** [comment]
This is already done, right?
