### ISSUE TITLE
Make DotVVM properties and route parameters case-insensitive.

### ISSUE THREAD

**Issue by quigamdev** [riganti/dotvvm#107]
Please, make DotVVM properties and route parameters case-insensitive. It is very annoying to care about case-sensitivity during coding.

**Comment by exyi** [comment]
Published on NuGet. Do you like it? Does it work as expected? @quigamdev

**Comment by tomasherceg** [comment]
Route names and parameters are case insensitive. Resolved in 683ef91b

However, we need also need to make the other things to be case insensitive, otherwise it doesn't make any sense:
- control names and tag prefixes
- binding names ({Value: ...} etc.)

**Comment by exyi** [comment]
done in 3fc71441bbf2762419fd9838e6ae0cfc97ff438e
