### ISSUE TITLE
New structure of the repo

### ISSUE THREAD

**Issue by tomasherceg** [riganti/dotvvm#1079]
There was an idea to merge some of DotVVM-related repos into the main repo (so we can simplify the process of publishing all packages together). This should also include changing the structure of the repo as it gets messier and messier.

1. Currently, we have the `/src/Tools` folder which contains build and publish scripts. We should move it to `/build`, and also clean it up - many of the scripts are not used anymore.

2. The projects in the `/src` should be reorganized to separate the following areas:
* `framework`
* `samples` - these are used internally by Selenium UI tests
* `extensions` - this folder should also include the projects from related repos: [Dynamic Data](https://github.com/riganti/dotvvm-dynamic-data), [Tracing](https://github.com/riganti/dotvvm-tracing), [Status Page](https://github.com/riganti/dotvvm-samples-compilation-status-page), [Hot Reload](https://github.com/riganti/dotvvm-diagnostics-hot-reload), and [Server Side Cache](https://github.com/riganti/dotvvm-diagnostics-server-side-cache)
* `tools` - contains various CLI tools and utilities
* `templates` - contains a `dotnet new` template

Each folder can have a subfolder called `tests` with tests for the particular area.

Here is the **proposed structure of the `src` folder** (without renaming the projects discussed in a separate issue #723): 

```POWERSHELL
framework
  tests      # do we want it here, or in the root? 
    DotVVM.Framework.PerfTests # superseded by dotvvm-benchmarks, remove
    DotVVM.Framework.Tests
    fallback-test-project   # unused -> remove
  DotVVM.Core
  DotVVM.Framework
  DotVVM.Framework.Hosting.AspNetCore
  DotVVM.Framework.Hosting.Owin
tools
  DotVVM.CommandLine
  DotVVM.Compiler
  DotVVM.Compiler.Light  # can we delete it? I think it is not used.
  DotVVM.Tools.StartupPerfTester

extensions
  api
    tests
      DotVVM.Framework.Api.Swashbuckle.AspNetCore.Tests
      DotVVM.Framework.Api.Swashbuckle.Owin.Tests
    DotVVM.Framework.Api.Swashbuckle.AspNetCore
    DotVVM.Framework.Api.Swashbuckle.Owin
    DotVVM.Framework.Api.Swashbuckle.Owin.old     # can we delete it?
  selenium
    tests
      DotVVM.Framework.Tools.SeleniumGenerator
    DotVVM.Framework.Testing.SeleniumHelpers
  dynamic-data      # this is new
    DotVVM.Framework.Controls.DynamicData
    DotVVM.Framework.Controls.DynamicData.Annotations
  tracing          # this is new
    tests
      DotVVM.Tracing.MiniProfiler.Tests
    DotVVM.Tracing.ApplicationInsights
    DotVVM.Tracing.ApplicationInsights.AspNetCore
    DotVVM.Tracing.ApplicationInsights.Owin
    DotVVM.Tracing.MiniProfiler.AspNetCore
    DotVVM.Tracing.MiniProfiler.Owin
    DotVVM.Tracing.MiniProfiler.Shared
  diagnostics        # this is new
    server-side-cache
      DotVVM.Diagnostics.ServerSideCache
      DotVVM.Diagnostics.ServerSideCache.Sample
    status-page
      DotVVM.Diagnostics.StatusPage
      DotVVM.Diagnostics.StatusPage.Sample
    view-hot-reload
      DotVVM.Diagnostics.ViewHotReload
      DotVVM.Diagnostics.ViewHotReload.AspNetCore
      DotVVM.Diagnostics.ViewHotReload.Owin
      DotVVM.Diagnostics.ViewHotReload.Samples.AspNetCore
      DotVVM.Diagnostics.ViewHotReload.Samples.Owin

samples
  tests
    DotVVM.Samples.Tests
    DotVVM.Samples.Tests.CompletenessChecker
    DotVVM.Testing.Abstractions
  EmbeddedResourceControls
  DotVVM.Samples.BasicSamples.Api.AspNetCore
  DotVVM.Samples.BasicSamples.Api.AspNetCoreLatest
  DotVVM.Samples.BasicSamples.Api.Common
  DotVVM.Samples.BasicSamples.Api.Owin
  DotVVM.Samples.BasicSamples.AspNetCore
  DotVVM.Samples.BasicSamples.AspNetCoreLatest
  DotVVM.Samples.BasicSamples.Owin
  DotVVM.Samples.Common

templates 
```

I wonder what's the best time to do this change. If we only move files between folders, I believe git should handle this quite well, but there will be changes in `csproj` files (paths to project references) and in the `sln` file. 
I just want to avoid merge conflicts.
Also, it will affect build and release pipelines, so we should plan this maybe after a release of 3.2.

**Comment by exyi** [comment]
- [ ] We should also merge DotVVM.Samples.BasicSamples.Api and DotVVM.Samples.BasicSamples
- [ ] Merge AspNetCoreLatest and AspNetCore into one folder with to csproj files (and maybe some `#if`s for the differences)
- [ ] We should make the directory names shorter
- [ ] We should remove the version number from all these places and put it into `Directory.Build.props`, so we avoid merge conflicts.

**Comment by cafour** [comment]
* `DotVVM.Compiler.Light` should not be in the list. It has been deleted a while back.
* I think we should use a similar directory structure as the big dotnet repositories (e.g. `dotnet/roslyn` or `dotnet/aspnetcore`) to make it more approachable to outside contributors:
  1. Use `PascalCase` for dirs that aren't top-level (e.g. `src/Framework`).
  2. Omit obvious namespace segments (e.g. `src/Tools/Compiler` instead of `src/Tools/DotVVM.Compiler`).
  3. Use fewer groupings (e.g. have `src/Framework` and `src/Core` instead of `src/Framework/Framework` and `src/Framework/Core`).

**Comment by exyi** [comment]
Done.
