### ISSUE TITLE
Literal - add a RenderSpanElement property

### ISSUE THREAD

**Issue by tomasherceg** [riganti/dotvvm#108]
When this property is true, allow adding HTML attributes to the control.

**Comment by exyi** [comment]
Do you really need it on Literal? I think it would be better to add another control or use span element directly.

**Comment by tomasherceg** [comment]
Yes, I want it on the Literal, so the user can choose whether the span will be rendered (and then he can add HTML attributes to the control, it also applies to Visible etc.), or whether no span will be there (and in that case you are not able to set any attribute on it).
Also, currently in server rendering mode, the span is not present, however in the client rendering mode, it is. I want to make this consistent.

And since the Literal has also the FormatString or HtmlEncode properties, I don't think we need to duplicate this functionality creating another control.
