### ISSUE TITLE
Add C# documentation comments to StyleOverrideOptions

### ISSUE THREAD

**Issue by mrnustik** [riganti/dotvvm#1092]

**Comment by exyi** [comment]
This is already done: https://github.com/riganti/dotvvm/blob/v4-main/src/DotVVM.Framework/Compilation/Styles/StyleOverrideOptions.cs

You can backport it to main, if you want.

**Comment by mrnustik** [comment]
I am sorry. I did not see it in DtoVVM 3 so i Created this ticket and did not check the main for v4.
