### ISSUE TITLE
Reapplying viewmodel on the page in the SPA mode doesn't clear the foreach bindings

### ISSUE THREAD

**Issue by tomasherceg** [riganti/dotvvm#113]
Consider the following page:

    <dot:Repeater DataSource="{value: Tabs}">
        <a href="{value: Url}">{{value: Text}}</a>
    </dot:Repeater>
    <dot:SpaContentPlaceHolder ... />

When the page in the SPA container is changed, a new viewmodel is retrieved from the server and since it is a completely new object, it is reapplied to the page. However, the foreach binding in the Repeater doesn't clear its contents so the new tabs in the viewmodel are appended to the old ones.

There are several ways to solve this issue, the easiest will be to create a custom foreach binding which hooks on the dotvvm spaNavigated event (or some other suitable one) and clears the collection.

**Comment by exyi** [comment]
It should be enough to set all properties in ViewModel to null. Knockout will remove the content on observable property update

**Comment by tomasherceg** [comment]
Done. It was as easy as wrapping the whole viewmodel into ko.observable(). 
Resolved in d32aa799.
