### ISSUE TITLE
Bundling and minification of DotVVM resources

### ISSUE THREAD

**Issue by tomasherceg** [riganti/dotvvm#115]
1. Split DotVVM.ts into multiple files.
2. Introduce a mechanism to bundle resources.
3. Put the assembly version number to the URL and enable caching on the resource files.

**Comment by exyi** [comment]
I don't think it's good idea to use assembly version as script version identifier, because DotVVM is the only project I know that use assembly version :) and when I'm debugging I don't want to change the version number to reload scripts. It may also refresh excessively when the assembly version changes and script not. What about to use some hash of the script content?

**Comment by tomasherceg** [comment]
I know many projects which use assembly versioning, actually., almost all assemblies distributed on NuGet I know, use the assembly versoning.
If you want to debug the scripts, you can turn off the caching in your browser (I know that Chrome and IE can do it quite easily, so I guess the other browsers can do it too and it seems OK for debugging purposes). 

However hashing the script contents seems also like a viable way - I only don't like the fact that the URLs will be long. The URL /dotvvmResource/dotvvm-0.8.6.5.js looks much nicer. Or we can append something like ?time=timestamp automatically when the debug mode is turned on in the configuration.

**Comment by exyi** [comment]
The hash does not have to be cryptographically long. And who cares about query parameters, debuggers do not display them. /dotvvmResource/dotvvm.js?ver=12def345690ab78c is maybe longer, but will make browsers reload always and only if the content is changed. It shouldn't be problem to make it bit extensible or make a switch, but the hash is much more stable and should be default.

**Comment by darilek** [comment]
IMHO adding something like hash code to the URL is better. You get different hash only with changes in scripts/styles (DotVVM version (C#) may differ but scripts can by unaffected). 

If You want implement bundling feature, please add possibility create bundle groups instead bundle all resources to one big file. From client browser perspective - it opens more connections for parallel downloads for better performance

**Comment by exyi** [comment]
@darilek +1, It should use current BundlingProcessor to determine which bundles should be used. We only need to automatically create these bundles from scripts.

**Comment by exyi** [comment]
Maybe it'd better to bundle and minify resources during build process and register it to DotVVM resource management. The advantage would be that Dotvvm will not have to reference any runtime minifier.

**Comment by tomasherceg** [comment]
Bundling was implemented long time ago.
We don't want to handle minification on the framework level.
