### ISSUE TITLE
Empty css - Business pack 3 with Bootstrap4 theme

### ISSUE THREAD

**Issue by mirecad** [riganti/dotvvm#1160]
It looks like `BusinessPackTheme.Bootstrap4` is missing all its css. Included file _/dotvvmResource/dotvvm--businesspack-bootstrap4-css/dotvvm--businesspack-bootstrap4-css_ is **empty**.

Steps to reproduce:
- Create new project and check _DotVVM business pack_ and _Add Bootstrap 4_.
- Update packages to: DotVVM.AspNetCore 3.2.1 and DotVVM.BusinessPack 3.2.0-preview01-final
- In DotvvmStartup set up `options.AddBusinessPack(BusinessPackTheme.Bootstrap4);`
- Use any BP control for example MultiSelect

Control now looks like:

![image](https://user-images.githubusercontent.com/13980038/134865424-662249d4-f484-429e-87f1-3a16a7a57b64.png)

**Comment by exyi** [comment]
I believe this is fixed with the newest 3.2 BP release.
