### ISSUE TITLE
Async version of Context.ReturnFile?

### ISSUE THREAD

**Issue by GrabzIt** [riganti/dotvvm#1164]
Love Dotvvm! Maybe there is a reason not to do it. However, as ReturnFile is doing disk I/O it should probably be async. Or at least have an async version. Looking, at the code it seems to only be a minor change.

https://github.com/riganti/dotvvm/blob/4d1def067be1d32f1b41be2adc1b558d437f4d83/src/Framework/Framework/Hosting/DotvvmRequestContextExtensions.cs#L218

**Comment by tomasherceg** [comment]
Wow, we are calling `.Result` inside because the underlying service is already `async`. It seems we forgot to update this method. :-(
