### ISSUE TITLE
Generic control types

### ISSUE THREAD

**Issue by exyi** [riganti/dotvvm#117]
Control type could be generic classes. The type argument could be deduced from properties or somehow in the markup. It would be useful when you need to call back to viewModel using command.
Like:

``` C#
class Grid<T> ... {
    public IEnumerable<T> DataSource { get; set; }
    public Action<T> NewItemCommand {...}
    ...
}
```

Used as expected:

``` html
<dot:Grid DataSource="{value: MyItems}" NewItemCommand="{command: AddItem}" />
```

**Comment by tomasherceg** [comment]
This issue was created before introducing DataContextChange attributes which solve a similar problem (providing typings to a property or a template based on the type of another property).
I don't think that this is necessary.

**Comment by exyi** [comment]
They do not, this issue was acutally opened after the DataContextChange attributes were born.

When you want to have a property that is related to the type of another property you can hack it by changing data context type or introducing extension parameter if passing a value of this type is enough, it still can not check if the result type is corrent and so on. I understand that we don't want to implement this feature, but it's definitely not solved in any other way.
