### ISSUE TITLE
Lambdas in command bindings

### ISSUE THREAD

**Issue by exyi** [riganti/dotvvm#118]
Since parameters can be passed to command bindings, it should also be possible to use them directly. Like:

``` html
<dot:GridView DataSource="{value: Items5}" SortChanged="{command: column => Sort('Items5', column)}" />
```

**Comment by tomasherceg** [comment]
I like `SortChanged="{command: column => Sort('Items5', column)}"` more than `SortChanges="{command: Sort('Items5', _this)}"` and I am sure that lambdas will have much more use cases than this.

It can be used in `Validation.Target` which cannot handle primitive types right now. With lambdas, it could work like this:

```
Validation.Target="{value: () => NumberOfItems}"
```

**Comment by exyi** [comment]
It would not solve the problem with Validation.Target, because it actually already works correctly - It validates everything inside the specified value according to rules of the specified type. Except, there is nothing inside a primitive value... If it would be in lambda, how would that change the situation?

**Comment by tomasherceg** [comment]
It could be a "lambda expression".

**Comment by exyi** [comment]
Ah, you mean that it could be a Linq.Expression - it's not an problem to get the Expression from a binding - it's in some of the binding properties. But it does not really solve the problem, since there is no problem. If you don't consider this behavior to be, then we will probably have to redesign how the validation works.

**Comment by tomasherceg** [comment]
On the server it is not a problem and we could make the `Validation.Target` to work with that. The problem is on the client side.

I am not saying that the `Validation.Target` needs to support lambdas - I was trying to point out that on some places we need to reference a property and lambda expressions can be used for that. We would need to translate them to the JS somehow.

**Comment by tomasherceg** [comment]
The support for lambdas in bindings is becoming more and more important - I've changed the milestone to v3.0. 

We could use it in #749 and #833.

**Comment by exyi** [comment]
We need optional support for types for the parameters. For example, in the NamedCommand control, we don't have a way of knowing which types will be used, so the usage will have to be explicit:

```html
<dot:NamedCommand Command={command: (string arg1, int arg2) => kokos(arg1, arg2)} />
```

On the other hand, normal use cases won't need the type specifier. For example:

```html
<dot:GridView sortChanged={command: expr => ...} />
```
