### ISSUE TITLE
Non-pair HTML tag handling

### ISSUE THREAD

**Issue by siwicgrey** [riganti/dotvvm#119]
While heavy-using DataContext in DataContext in DataContext, I used unclosed < hr >. That caused dotvvm to collapse on build. I solved it by replacing that element with < hr/ >, but it should tolerate < hr > as well, or notify user.

**Comment by tomasherceg** [comment]
Can you look at the Sample 50 and modify it so it would fail? I am unable to find a combination of DataContexts and unclosed hr element which would break this.
Commit 75470f18

**Comment by tomasherceg** [comment]
Maybe it was fixed with some other bug.
