### ISSUE TITLE
Problém s Dictionary v dotvvm 4.0 preview3

### ISSUE THREAD

**Issue by dnajcz** [riganti/dotvvm#1221]
Je tam nějaká chyba ve verzi dotvvm 4.0 preview3 (v dotvvm 3.2.1 to funguje správně):

Když si ve viewmodelu nadefinuji Dictionary:
`public Dictionary<string, bool> Pravidla { get; set; } = new Dictionary<string, bool>() { { "key1", true }, { "key2", false } };`
a v .dothtml chci vypsat hodnotu dle klíče:
`<p>Hodnota: {{value: _root.Pravidla["key2"]}}</p>`
Vypíše se místo hodnoty řetězec: ` [object Object]`, tedy výpis vypadá takto:
`Hodnota: [object Object]`
Zajímavé ale je, že když v tagu současně vypíšu např. uvozovky, apostrof nebo znaky áéí..., tak se to zobrazí správně, tedy např.:
`<p>á {{value: _root.Pravidla["key2"]}}</p>` vypíše správně `á false`.

Jsou to ale věci mezi nebem a zemí :)

**Comment by exyi** [comment]
Díky za odvahu vyzkoušet novou verzi, chybu jsem opravil :) Další preview release bude snad brzy.

Lehce vtipné je, že tam je už nějakou dobu, jen jsme jí teď zviditelnili. To divné chování je protože jsme přidali do frameworku drobnou optimalizaci, která `<p>Hodnota: {{value: _root.Pravidla["key2"]}}</p>` převede na `<p InnerText={value: "Hodnota: " + _root.Pravidla["key2"]}></p>`, protože je to pak o dost efektivnější na klientovi. Optimalizaci si to ale radši netroufne když jsou tam html nebezpečné znaky jako uvozovka. Proč se tomu nelíbí ani á nevím, asi nějaký relikt v .NET z dob kdy nebylo všechno utf8.
