### ISSUE TITLE
Cannot combine @js directive and @baseType with DotVVM properties in markup controls

### ISSUE THREAD

**Issue by tomasherceg** [riganti/dotvvm#1249]
When a markup control uses both DotVVM properties (via the code-behind file) and the `@js` directive, a Knockout error occurs because the wrapper tag of the control has two Knockout data-bindings which control descendant bindings.

As a workaround, I can use `@noWrapperTag` but it's not very intuitive - we should either combine both binding handlers into one, or to find a better solution. 
I guess that the same problem will occur when implementing #1231.

**Comment by exyi** [comment]
This is a bug, there is already a logic which combines those two data bindings, it's just probably broken or something.

**Comment by quigamdev** [comment]
In general, the `@js` directive has been broken in markup control. #1278 this PR fixes it. Maybe the PR could be also a fix for this issue.

**Comment by exyi** [comment]
Aha, this is the same error, I just forgot about this issue :facepalm:
