### ISSUE TITLE
Compilation API nonauthorized access

### ISSUE THREAD

**Issue by mrnustik** [riganti/dotvvm#1268]
As a part of #1119 the `NonAuthorizedApiAccessMode` setting was removed from the status page API options. 

This is unfortunate because we have used this setting for checking the compilation status after deployment. Right now it directly returns 403 when the `AuthorizationPredicate` fails. Through this setting, we have been able to make the API return just a 200 when view compilation did not fail.

## Suggested solutions:

1. Return `NonAuthorizedApiAccessMode` to the `DotvvmCompilationPageConfiguration`.
2. Add `ApiAuthorizationPredicate` to have separate option for authorization only of the API itself.

**Comment by exyi** [comment]
will the healthcheck introduced in this PR be enough for your needs? https://github.com/riganti/dotvvm/pull/1209

**Comment by mrnustik** [comment]
Yes, this looks like the solution to my problem. Thanks. Closing the issue.

**Comment by exyi** [comment]
Not so fast, it's not merged yet :D
