### ISSUE TITLE
Add better Visual Studio .dothtml text editor experience

### ISSUE THREAD

**Issue by kaderavaclav** [riganti/dotvvm#131]
Please implement features from HTML text editor f.e.:
 - Collapsible elements [+][-]
 - HTML IntelliSense 
     - css classes hintning not working (really annoying)
     - url insertion, ...
 - Element inline style not highliting properties and values
 - Double-tab to finish input, and so on...

Really bad experience writing html code in dothtml text editor.

// PS. Using free extension installed on Visual Studio 2015 Community

**Comment by tomasherceg** [comment]
Some features will be fixed in the next release which will be out soon.
Some of them will be only available in the commercial version.

**Comment by exyi** [comment]
Most of these is fixed in internal release. There was a little mistake in how we derived from HTML editor, all features that are derived from HTML editor will be available in free version. I hope we'll import it soon.
