### ISSUE TITLE
Make exception filters working with all exceptions

### ISSUE THREAD

**Issue by kaderavaclav** [riganti/dotvvm#132]
It would be nice to have possibility to catch and log all application/server exceptions, not only command exceptions, using Exceptions Filters.

**Comment by exyi** [comment]
You can catch these exception using custom OWIN middleware. You register it like:
```C#
#if DEBUG
app.Use<DotvvmErrorPageMiddleware>();
#endif
app.Use<ExceptionLogger>();
app.UseDotvvm(..., errorPages: false); // errorPages: true will catch exceptions and will not pass them
```

**Comment by kaderavaclav** [comment]
Application exceptions are in catch block intercepted properly, but server errors like 404 or similar are probably fired without running OWIN pipeline. I'm receiving 200 OK all the time.

**Comment by exyi** [comment]
404 is not thrown as exception, it is set by webserver, when no response is rendered by any of middlewares.
