### ISSUE TITLE
Split Literal control into Literal and HtmlLiteral

### ISSUE THREAD

**Issue by tomasherceg** [riganti/dotvvm#133]
There are many combinations of HtmlEncode, RenderSpanElement and FormatString on Literal which don't make sense, some of them are also not supported by Knockout.
It would be better to split this functionality.

**Comment by exyi** [comment]
maybe we can make literal always render <span> element and remove 'RenderSpanElement' property. We already have RawLiteral, which is really lightweight and is used internally for texts from dothtml
