### ISSUE TITLE
RadioButton is not throwing exception when approaches are combined

### ISSUE THREAD

**Issue by Duzij** [riganti/dotvvm#1347]
Currently, there are two main approaches how to mark RadioButton as selected:

1. First approach: CheckedValue (string) and CheckedItem (string) properties are used, and if properties are same, RadioButton is selected
2. Second approach: CheckedValue (bool) and Checked (bool) properties are used, and if properties are same, RadioButton is selected

It is possible to use a combination of these two approaches, I think it would be nice to add DotVVMException to avoid such mistakes:
```
<bs:RadioButton Text="Should be checked" ID="radio" GroupName="RadioButtonGroup"
                           CheckedValue="testRadio" CheckedItem="{value: Radio}"
                           Checked="{value: RadioChecked}"
```

**Comment by exyi** [comment]
Resolved in #1667
