### ISSUE TITLE
dotvvm for vs2019 

### ISSUE THREAD

**Issue by daltinkurt** [riganti/dotvvm#1358]
Hi, I updated my vs2019 to 16.11.12 (latest version).
Now dotvvm for vs2019 extensions gives me error.
I tried to 

- delete the "ComponentModelCache" folder, 
- uninstall/install the extension with different versions (v4.0.539.0, v4.0.534.0),
- vs2019 resetting settings & user data

but  I keep seeing errors.
should i update to vs2022?

website is working,
but intellisense, f7, and others not :(

```
 <entry>
    <record>884</record>
    <time>2022/04/16 14:45:40.553</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Begin package load [DotvvmPackage]</description>
    <guid>{1B39C66B-16E9-4B17-A90D-841357CC282C}</guid>
  </entry>
  <entry>
    <record>885</record>
    <time>2022/04/16 14:45:40.555</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>SetSite failed for package [DotvvmPackage]Source: &apos;System.ComponentModel.Composition&apos; Description: The composition produced multiple composition errors, with 2 root causes. The root causes are provided below. Review the CompositionException.Errors property for more detailed information.&#x000D;&#x000A;&#x000D;&#x000A;1) No exports were found that match the constraint: &#x000A;&#x0009;ContractName&#x0009;DotVVM.Integration.VisualStudio.Dialogs.DialogFactory&#x000A;&#x0009;RequiredTypeIdentity&#x0009;DotVVM.Integration.VisualStudio.Dialogs.DialogFactory&#x000D;&#x000A;&#x000D;&#x000A;Resulting in: Cannot set import &apos;DotVVM.Integration.VisualStudio.VsPackages.DotvvmPackageDependencies.DialogFactory (ContractName=&quot;DotVVM.Integration.VisualStudio.Dialogs.DialogFactory&quot;)&apos; on part &apos;DotVVM.Integration.VisualStudio.VsPackages.DotvvmPackageDependencies&apos;.&#x000D;&#x000A;Element: DotVVM.Integration.VisualStudio.VsPackages.DotvvmPackageDependencies.DialogFactory (ContractName=&quot;DotVVM.Integration.VisualStudio.Dialogs.DialogFactory&quot;) --&gt;  DotVVM.Integration.VisualStudio.VsPackages.DotvvmPackageDependencies&#x000D;&#x000A;&#x000D;&#x000A;2) No exports were found that match the constraint: &#x000A;&#x0009;ContractName&#x0009;DotVVM.Integration.VisualStudio.Common.Licensing.ILoginProvider&#x000A;&#x0009;RequiredTypeIdentity&#x0009;DotVVM.Integration.VisualStudio.Common.Licensing.ILoginProvider&#x000D;&#x000A;&#x000D;&#x000A;Resulting in: Cannot set import &apos;DotVVM.Integration.VisualStudio.VsPackages.DotvvmPackageDependencies.LoginProvider (ContractName=&quot;DotVVM.Integration.VisualStudio.Common.Licensing.ILoginProvider&quot;)&apos; on part &apos;DotVVM.Integration.VisualStudio.VsPackages.DotvvmPackageDependencies&apos;.&#x000D;&#x000A;Element: DotVVM.Integration.VisualStudio.VsPackages.DotvvmPackageDependencies.LoginProvider (ContractName=&quot;DotVVM.Integration.VisualStudio.Common.Licensing.ILoginProvider&quot;) --&gt;  DotVVM.Integration.VisualStudio.VsPackages.DotvvmPackageDependencies&#x000D;&#x000A;&#x000D;&#x000A;</description>
    <guid>{1B39C66B-16E9-4B17-A90D-841357CC282C}</guid>
    <hr>80131500</hr>
    <errorinfo></errorinfo>
  </entry>
```

**Comment by honzakmenta** [comment]
I have the same problem after update to 16.11.12

**Comment by tomasherceg** [comment]
> But from today I'm getting warning the Visual Studio 2019 is no longer supported.
Where does this warning show? Can you post a screenshot? 

DotVVM still supports VS 2019 and we are currently working on a fix to support the latest update - there were some breaking changes in the internal API.

**Comment by honzakmenta** [comment]
> > But from today I'm getting warning the Visual Studio 2019 is no longer supported.
> > Where does this warning show? Can you post a screenshot?
> 
> DotVVM still supports VS 2019 and we are currently working on a fix to support the latest update - there were some breaking changes in the internal API.

I can't see this warning again in VS 2019 after install VS 2022. But it was yellow bar under toolbar (the same when any extension slows down the VS)

**Comment by tomasherceg** [comment]
We've just released an updated version of DotVVM for Visual Studio which should work with the latest update of VS 2019. 
Feel free to reopen the issue if you experience problems.

**Comment by daltinkurt** [comment]
> We've just released an updated version of DotVVM for Visual Studio which should work with the latest update of VS 2019. Feel free to reopen the issue if you experience problems.

Hi, I updated vs to latest version (vs2022 v17.1.5)
I alse updated extension.
deleted the "ComponentModelCache" folder.
But cannot create new dotvvm project
gives me that error:
![ScreenShot_20220420165845](https://user-images.githubusercontent.com/3593684/164248547-ee672370-5f03-469a-a4f8-045eb0fac3ee.png)
