### ISSUE TITLE
Docker image build fails when Dotvvm private nuget feed is used

### ISSUE THREAD

**Issue by Mitroz** [riganti/dotvvm#1386]
Other nuget feeds (nuget.org, github private feed) works properly. 
Build fails on github actions, local devs computers (tried two) with the same error
Simple test project is inclued. 

/usr/share/dotnet/sdk/6.0.101/NuGet.targets(130,5): error : Unable to load the service index for source https://www.dotvvm.com/nuget/v3/index.json. [/src/DockerBuildTest/DockerBuildTest.csproj]
/usr/share/dotnet/sdk/6.0.101/NuGet.targets(130,5): error :   The SSL connection could not be established, see inner exception. [/src/DockerBuildTest/DockerBuildTest.csproj]
/usr/share/dotnet/sdk/6.0.101/NuGet.targets(130,5): error :   The remote certificate is invalid because of errors in the certificate chain: PartialChain [/src/DockerBuildTest/DockerBuildTest.csproj]

OpenSSL verify of certificate from https://www.dotvvm.com/nuget/v3/index.json
OpenSSL> verify  c:\data\cert.crt
C = US, ST = California, L = San Francisco, O = "Cloudflare, Inc.", CN = sni.cloudflaressl.com
error 20 at 0 depth lookup: unable to get local issuer certificate
error c:\data\cert.crt verification failed
error in verify

[DockerBuildTest.zip](https://github.com/riganti/dotvvm/files/8737186/DockerBuildTest.zip)

**Comment by tomasherceg** [comment]
I've tried the sample project but I am not able to replicate the error - the SSL verification goes well in my case and the NuGet restore succeeds. 

However I've found an issue in the `nuget.config` file - the package source name contains spaces which need to be replaced with `_x0020_` sequences in the element name:

```
        <DotVVM_x0020_Private_x0020_Nuget_x0020_Feed>
            <add key="Username" value="xxx" />
            <add key="ClearTextPassword" value="xxx" />
        </DotVVM_x0020_Private_x0020_Nuget_x0020_Feed>
```

I've also added `protocolVersion="3"` to the DotVVM package source but I think it is not needed.

Can you try to ping the URL with curl from the container?

First, run `docker run --rm -it mcr.microsoft.com/dotnet/sdk:6.0 /bin/bash` - it should open the shell in the container. 
Then, run `curl "https://www.dotvvm.com/nuget/v3/index.json" -u "username:password"`

**Comment by Mitroz** [comment]
Eh, stupid error in nuget.config. Now issue is fixed on github action. Thank you!

Certificate error remains but only on the local machine but this is some issue on our company network. It confused me, the error had the same message: Unable to load the service index for source [https://www.dotvvm.com/nuget/v3/index.json]

I found some similar here (I'm a lucky man, I'm always happy when I win a some specialty...) :
https://github.com/dotnet/dotnet-docker/issues/2788

Thank again for help
