### ISSUE TITLE
Calling DOTVVM functions from JS events

### ISSUE THREAD

**Issue by benj989** [riganti/dotvvm#1396]
Hi team, how can I call the DOTVVM function using Named Commands and JS directives directly from JS? I have followed all steps to create module, register it in DotvvmStartup.cs, import @js module etc, create dot:NamedCommand and the functionality only works if calling the _js.Invoke using a <dot:button> control with a Click event (or similar control). But I cannot call the Named Command from Javascript directly. For example:

In DOTHTML page, say I have:
`$(document).on('click', '.class-name', function (e) {
    this.context.namedCommands["ReloadData"](); // NOT WORKING
});`
`<dot:NamedCommand Name="ReloadDataNC" Command="{staticCommand: myList = ReloadFromDatabase();}" />`

In the imported JS Module:
`export default context => new MyViewModule(context);
class MyViewModule{
    constructor(context) {
        this.context = context;
    }
    ReloadData() {
        this.context.namedCommands["ReloadDataNC"]();
    }
}`

I also tried moving the JS click event code into the Module with no success. I get errors like "Uncaught TypeError: Cannot read properties of undefined (reading 'namedCommands')".

Can you let me know if I'm missing something or is this simply not possible? Thanks!

**Comment by tomasherceg** [comment]
The first way will not work - `this.context` is available only in the viewmodule, not in `onclick` handlers in the page.

The second option should work fine:
- Can you look in the Dev Tools if there are any errors connected to loading the module? Maybe check also the Network tab if you see the browser actually loaded the module.
- Make sure the JS module is registered as a ScriptModuleResource, not just ScriptResource.
- Can you try adding `console.log(this.context)` before the line that accesses the `namedCommands`? We should see what's in the context.

**Comment by exyi** [comment]
The second option, but you have to use [arrow function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions) instead of classic anonymous function to preserve `this`. Or, I'd suggest avoiding using `class` in Javascript, you don't need it and you get rid of all these `this` is not this issues:

```
export default context => {
     $(document).on('click', '.class-name', function (e) { context.namedCommands["ReloadData"]() })
    return {
      ReloadData() { this.context.namedCommands["ReloadDataNC"]()
    }
}
```

**Comment by tomasherceg** [comment]
In such case I believe it should be `ReloadData() { context.namedCommands["ReloadDataNC"]()`
