### ISSUE TITLE
Visual Studio 2022 v 17.2.4 - Extension 4.0.543.0 load error

### ISSUE THREAD

**Issue by keeper7** [riganti/dotvvm#1417]
Visual Studio 2022 v17.2.4  Community 
Extension v 4.0.543.0

DotvvmPackage did not load correctly

ActivityLog.xml

 <entry>
    <record>669</record>
    <time>2022/06/14 22:15:52.117</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>SetSite failed for package [DotvvmPackage]Source: 'System.ComponentModel.Composition' Description: The composition produced multiple composition errors, with 2 root causes. The root causes are provided below. Review the CompositionException.Errors property for more detailed information.

1) No exports were found that match the constraint: 
	ContractName	DotVVM.Integration.VisualStudio.Dialogs.DialogFactory
	RequiredTypeIdentity	DotVVM.Integration.VisualStudio.Dialogs.DialogFactory

Resulting in: Cannot set import 'DotVVM.Integration.VisualStudio.VsPackages.DotvvmPackageDependencies.DialogFactory (ContractName="DotVVM.Integration.VisualStudio.Dialogs.DialogFactory")' on part 'DotVVM.Integration.VisualStudio.VsPackages.DotvvmPackageDependencies'.
Element: DotVVM.Integration.VisualStudio.VsPackages.DotvvmPackageDependencies.DialogFactory (ContractName="DotVVM.Integration.VisualStudio.Dialogs.DialogFactory") -->  DotVVM.Integration.VisualStudio.VsPackages.DotvvmPackageDependencies

2) No exports were found that match the constraint: 
	ContractName	DotVVM.Integration.VisualStudio.Common.Licensing.ILoginProvider
	RequiredTypeIdentity	DotVVM.Integration.VisualStudio.Common.Licensing.ILoginProvider

Resulting in: Cannot set import 'DotVVM.Integration.VisualStudio.VsPackages.DotvvmPackageDependencies.LoginProvider (ContractName="DotVVM.Integration.VisualStudio.Common.Licensing.ILoginProvider")' on part 'DotVVM.Integration.VisualStudio.VsPackages.DotvvmPackageDependencies'.
Element: DotVVM.Integration.VisualStudio.VsPackages.DotvvmPackageDependencies.LoginProvider (ContractName="DotVVM.Integration.VisualStudio.Common.Licensing.ILoginProvider") -->  DotVVM.Integration.VisualStudio.VsPackages.DotvvmPackageDependencies

</description>
    <guid>{1B39C66B-16E9-4B17-A90D-841357CC282C}</guid>
    <hr>80131500</hr>
    <errorinfo></errorinfo>
  </entry>

**Comment by acizmarik** [comment]
Thanks for reporting. We are already preparing a new release that is compatible with newest updates

**Comment by acizmarik** [comment]
New versions (4.0.544.0) have been released to marketplace. After a while, they should also appear on our documentation pages.
If you still exprience these issues after update, feel free to reopen this issue.
