### ISSUE TITLE
Determine whether the postback is currently running in a bindings

### ISSUE THREAD

**Issue by tomasherceg** [riganti/dotvvm#142]
When using the FileUpload control, it may take several seconds for the server to process the uploaded files. However the IsBusy property of the UploadedFilesCollection is true only when the files are uploading on the server and not when the UploadCompleted postback is running.

It would be useful to create some generic mechanism for binidings to be able to determine whether specific postback is running. 

What about adding a PostbackStatusHandler postback handler which would set some viewmodel property to true before the postback and set the value back to false after the postback.

Something like this:

    <dot:FileUpload Files="{value: Files}" UploadCompleted="{command: ProcessFiles()}">
        <PostBack.Handlers>
            <dot:PostbackStatusHandler IsPostbackRunning="{value: IsProcessing}" />
        </PostBack.Handlers>
    </dot:FileUpload>
    <div class="loading" Visible="{value: Files.IsBusy || IsProcessing}">Uploading</div>

The advantage of this mechanism is that the postback handlers can already specify which event they are associated with and the only thing we have to implement would be the handler itself and some thing that would allow to specify a callback for a particular postback.

**Comment by exyi** [comment]
I'm not against the postback handler, this is quite cool use case for it. However there may be more use cases for evaluating client-side functions. We can just create static class and import it by default to bindings - it'll look like `{value: Dotvvm.IsPostbackRunning}`, another property could be `{value: Browser.WindowWidth}` or {value: Dotvvm.LastPostbackErrorMessage}.

**Comment by tomasherceg** [comment]
We could add these things for sure, however we need to define what they return on the server (I'd expect empty values). And I'd like them to have the `_dotvvm` prefix so everyone can easily distinguish whether they come from the viewmodel or not.

We should create a list of things we'd like to have there.

**Comment by exyi** [comment]
I don't think prefixes are needed, it will be like static class. You can already use some classes from .net, I think System is imported by default, however only few method can be translated to javascript. You can use all of them in server evaluated bindings (command, resource)

**Comment by exyi** [comment]
OK, implemented. You can use _page binding parameter: `{value: _page.IsPostbackRunning}`
