### ISSUE TITLE
How to call function in script tag of dothtml from dotvvm html tag

### ISSUE THREAD

**Issue by nagulapallinaveen** [riganti/dotvvm#1426]
account_receivable.dothtml:

<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title></title>
</head>

<body>
    <script type="text/javascript">

        var oReport = {};

    oReport.GetReport = function () {
        if (!ValidateDateRange('ddlARRDate', 'txtARRDateFrom', 'txtARRDateTo')) {
            return null;
        }

        var sClientId = $("#ddlClient").val();
        var sDailyWeekId = $("#ddlARRDate").val();
        var sStartDate = $("#txtARRDateFrom").val();
        var sEndDate = $("#txtARRDateTo").val();

        if (sDailyWeekId == "-1" && sStartDate == "" && sEndDate == "") {
            ErrorValidation("Must select a range date", "txtARRDateFrom");
            return false;
        }

        if (sClientId == "-1") {
            ErrorValidation("Must select a Client", "ddlClient");
            return false;
        }

        var oParam = {
            sClientId: sClientId,
            sDailyWeekId: sDailyWeekId,
            sStartDate: sStartDate,
            sEndDate: sEndDate
        };

        var sType = $('input[name=rdbType]:radio:checked').val();

        switch (sType) {
            case '1':
                AjaxMethod('Aging_ServerEvent', oParam, '../Report/Account.aspx', oReport.AgingReport_Callback);
                break;
            case '2':
                AjaxMethod('QuickbookTotal_ServerEvent', oParam, '../Report/Account.aspx', oReport.QuickbookDetail_Callback);
                break;
            default:
                Alert("", "Must select a report type");
                break;
        }
    };

</script>

            <dot:Button class="btnMenu" Text="Get Report" 
                        Click="{staticCommand: _js.Invoke("GetReport", null)}" />
        </div>
</body>
</html>

**Comment by exyi** [comment]
I don't understand what exactly are you trying to achieve, but I think in this case you can simply use plain html `<button onclick="oReport.GetReport()" />`. The `_js.Invoke` is used for calling function from imported modules and you don't seem to need that.

Reopen this if this comment didn't help.
