### ISSUE TITLE
The @viewModel directive IntelliSense only suggests custom types and not the system ones

### ISSUE THREAD

**Issue by tomasherceg** [riganti/dotvvm#143]
We should also add interfaces and system types (at least System.Object and the basic system types) into the completion list.

The question is whether it is not a perf issue when we put thousands of items in the IntelliSense...

**Comment by exyi** [comment]
It should also prioritize types implementing `IDotvvmViewModel`, types in current assembly. It may be a performance issue, however you can solve it by pre-filtering types based on typed characters.
