### ISSUE TITLE
Styles.Tag not known by VS Extension

### ISSUE THREAD

**Issue by JosefPihrt** [riganti/dotvvm#1431]
Hi,

I'm on latest version and I would like to use `Styles.Tag` property but I'm getting warning that this property does not exist.

![image](https://user-images.githubusercontent.com/11931318/177528711-60df03b4-eca7-404d-854b-37bf33a4723c.png)

I found it here: https://www.dotvvm.com/docs/4.0/pages/concepts/dothtml-markup/server-side-styles

**Comment by exyi** [comment]
I think it will work runtime, looks like VS Extension glitch to me. Can you please verify that it's the case?

**Comment by JosefPihrt** [comment]
I confirm that it works in the runtime.
