### ISSUE TITLE
Date/DateTime Textbox value resets if user changes year

### ISSUE THREAD

**Issue by Mylan719** [riganti/dotvvm#1438]
- I am trying to use: `<dot:TextBox Type="Date" Text={value: EndDate} />`
- I bind it to `public DateTime StartDate { get; set; }` 
- I type `10`,`10` for month and day into the date field like this: 
![image](https://user-images.githubusercontent.com/3776116/181761167-b5225a13-0835-4daa-8e1a-c302e2b195a8.png)
- If I now type `20` to write year 2022 the value resets to empty.
Another way to get this behavior is to go to filled in date select year and start typing.

With ordinary `<input type='date'>` this does not happen and I can fill the year no problem.

**Comment by exyi** [comment]
This is solved by #1451
