### ISSUE TITLE
ViewModel namespace and assembly root

### ISSUE THREAD

**Issue by exyi** [riganti/dotvvm#145]
It should be possible to declare a namespace as ViewModel root and then you will not have to type the full path, just class name (or possibly few namespaces).
dotvvm.json:

``` json
{
    "viewModelRoot": "My.Super.Cool.Project.WebSite.ViewModels"
}
```

and dothtml:

```
@viewModel LoginPageViewModel
```

or

```
@viewModel UserManagement.LoginPageViewModel
```

**Comment by tomasherceg** [comment]
Wouldn't global imports be better? They could apply also to static command services.

**Comment by exyi** [comment]
> Wouldn't global imports be better? They could apply also to static
> command services.

We actually have global import
(DotvvmConfiguration.Markup.ImportedNamespaces), but it does not apply
to type names in directives. Do you think this is a good idea? Should
@import directives in the file also apply to them? Should that apply to
@import directives?

**Comment by exyi** [comment]
I don't think specifying the viewmodel full name is an issue and the assembly is already optional. Let's close this.
