### ISSUE TITLE
Javascript deserializer updates observables even when they haven't change

### ISSUE THREAD

**Issue by tomasherceg** [riganti/dotvvm#146]
The postback response contains only fields that have changed in the viewmodel, which is correct. However, the client takes the viewModelDiff from the server, applies it to the serialized viewmodel (which was sent to the server originally), and then it deserializes the patched object back to the Knockout viewmodel which is really not necessary. 

It causes many updates on the observables which hits the performance.

We should modify the `patch` function to patch only the fields which have really changed in the viewmodel, and do not reapply the whole viewmodel if it is not really needed.

And we should definitely add tests for the patch method to be sure it stays working.

**Comment by tomasherceg** [comment]
The patching is in DotVVM.ts:210. We can move it to line 225 and replace the deserialize routine.

**Comment by exyi** [comment]
ViewModel diff is currently optional feature, and I don't want to force it. The bug was only in

**Comment by tomasherceg** [comment]
Actually, I think that the viewModelDiff should be used always (the only exception is when you switching to a different page in the SPA). There is absolutely no point in sending viewmodel properties which didn't change to the client. 

Consider a page with TextBox and the TextChanged event. Before the response from the server arrives, the user might already changed another field. If we get the whole viewmodel, the changes the user made after the postback was issued, will be discarded. I don't think it is a good idea.

In all cases, the viewModelDiff should be turned on by default.

**Comment by tomasherceg** [comment]
There is also a bug when updating an array - it is always cleared and recreated from scratch. I have added a condition which detects whether the array has the same number of elements - if so, it only updates the elements and not create the array again.
