### ISSUE TITLE
Hot reload breaks markup controls with @property directive

### ISSUE THREAD

**Issue by tomasherceg** [riganti/dotvvm#1474]
When a markup control with the `@property` directive is used, and its file is changed with the Hot reload turned on, we are probably not deleting some caches - I am getting the following exception:

```
Unable to cast object of type 'DotvvmMarkupControl-690dd7db-a01e-41a5-9897-b4bfda8c472d' to type 'DotvvmMarkupControl-4f6bb064-cc07-4b26-9b8d-9534a0433f50'.
```

**Comment by exyi** [comment]
That's the same issue as https://github.com/riganti/dotvvm/issues/1080

**Comment by tomasherceg** [comment]
Sorry, I didn't notice it's a duplicate.

**Comment by exyi** [comment]
Oh, it's extra annoying because we break it for each change in the control, not just in `@property` directive. It's easy to add cache, so we can fix that first.
