### ISSUE TITLE
IncludedInPage with resource binding to _control property doesn't work

### ISSUE THREAD

**Issue by tomasherceg** [riganti/dotvvm#1475]
I've tried markup controls with the `@property` directive, but I am getting `NullReferenceException` in `Render` method when the property is passed to `IncludedInPage` via `resource` binding on `_control.SomeProperty`.

```
@property bool ShowDescription

<p IncludeInPage="{resource: _control.ShowDescription}">test</p>
```

The exception: 
[dotvvm-error-NullReferenceException.zip](https://github.com/riganti/dotvvm/files/9616168/dotvvm-error-NullReferenceException.zip)

**Comment by exyi** [comment]
It happens because the property isn't assigned and it's default value is null. I'll fix the default value, and IMHO it would make sense to make properties without defined default required.
