### ISSUE TITLE
Add support of css classes and styles to JsComponent

### ISSUE THREAD

**Issue by lorencjan** [riganti/dotvvm#1485]
Currently, there cannot be added a css class or style to JsComponent as it's DotvvmControl and not HtmlGenericControl. This is not uniform with other dotvvm controls + it's handy to be able to style the wrapper element.

**Comment by exyi** [comment]
Thanks for feedback, we'll add HtmlCapability to the JsComponent (prefix `WrapperTag:`?)

For now, workaround is to wrap the JsComponent in `<dot:Decorator class='x'>`
