### ISSUE TITLE
FileUpload validation

### ISSUE THREAD

**Issue by siwicgrey** [riganti/dotvvm#150]
There is a need to prevent uploading in cases like: file is too big, extension is incorrect etc.

**Comment by djanosik** [comment]
We have properties `IsFileTypeAllowed`, `IsMaxSizeExceeded` and `IsAllowed` available on the [UploadedFile](https://github.com/riganti/dotvvm/blob/master/src/DotVVM.Framework/Storage/UploadedFile.cs) class. You can use them. However values of these properties are based on data sent from client and can't be trusted. There is no easy way to fix this.

If you have some security-critical scenario, you should always validate the file yourself (check stream length, file headers, etc). Also you can limit the maximum size of HTTP request.
