### ISSUE TITLE
Dotvvm CommandLine commands dont work if csproj path contains spaces

### ISSUE THREAD

**Issue by MichalOberreiter** [riganti/dotvvm#1533]
Hi,

I know I posted it few months ago, but unfortunately it still doesnt work (tested with command line version 4.0.10).

if I want to use for example command dotvvm info, it ends with error "The project metadata could not be obtained".
Figured out that it caused by spaces in absolute path (anywhere) of .csproj file:

invalid path "C:\Users\Jake\My Projects\Project\Project.csproj"
valid path "C:\Users\Jake\MyProjects\Project\Project.csproj"

**Comment by exyi** [comment]
Sorry, we didn't release it as 4.0 bugfix, but it should be fixed 4.1 preview. Since we are currently unable to release new nuget packages (reasons...), I can't easily backport it for you :/. Could you please verify that the fix in 4.1 preview actually works?
