### ISSUE TITLE
Strange behaviour with bind attribute Direction.ClientToServerInPostbackPath

### ISSUE THREAD

**Issue by MichalOberreiter** [riganti/dotvvm#1534]
Hi,
my goal (customer's goal..) is to create large dataset which is filled and sent to client only at first request and allows sending postbacks for individual rows without sending whole dataset back to server.
I'm done with example below.

When I click on Action button of first element, dataset shrinks to one element list, but postbacks can be repeated.
When I click on second/third button, postback doesnt render result and 
second postback ends with error: "Nothing was found inside specified DataContext. Please check if ViewModel is populated."

I tried experimenting with "Direction.ClientToServerInPostbackPath" in lots of examples (filling the dataset on client, etc.),
but none worked as expected.

Is any chance to reach my goal?

Thanks for help

VIEWMODEL:

   ```
       [Bind(Direction.ServerToClientFirstRequest | Direction.ClientToServerInPostbackPath)]
       public List<ItemDTO> Items { get; set; } = new List<ItemDTO>();

       public string Result { get; set; }

        public override Task PreRender()
        {
            if (!Context.IsPostBack)
            {
                this.Items = new List<ItemDTO>()
                {
                    new ItemDTO()
                    {
                        Value = 1,
                        Name = "One"
                    },
                    new ItemDTO()
                    {
                        Value = 2,
                        Name = "Two"
                    },
                    new ItemDTO()
                    {
                        Value = 3,
                        Name = "Three"
                    },
                };
            }

            return base.PreRender();
        }


        public void Action(int item)
        {
            Result = item + Guid.NewGuid().ToString();
        }

        public class ItemDTO
        {
            public int Value { get; set; }

            public string Name { get; set; }
        }
```

VIEW:
```
    <div>Count: {{value: Items.Count}}</div>
    <div>{{value: Result}}</div>

    <hr />
    <dot:Repeater DataSource="{value:Items}">
        <ItemTemplate>
            <div>
                {{value: Name}}
                <dot:Button Text="ACTION" Click="{command: _parent.Action(_this.Value)}" />
            </div>
        </ItemTemplate>
    </dot:Repeater>
```
Bonus at the end:
If you change name of property "Name" to "Text", postbacks of second and third elements has absolutely different behaviour :-D

**Comment by exyi** [comment]
This is definitely a bug. Seems like we don't even have a test for this :facepalm:, I'll look into it.


You might get similar results with https://www.dotvvm.com/docs/4.0/pages/concepts/viewmodels/server-side-viewmodel-cache (and we even have test for that...) - only changed parts of your viewmodel will be transfered, but the entire viewmodel will be deserialized and serialized, so it's going to be much slower than `ClientToServerInPostbackPath` (if it worked)
