### ISSUE TITLE
Class attribute and binding conflicts in controls

### ISSUE THREAD

**Issue by tomasherceg** [riganti/dotvvm#154]
If you have a DotVVM markup control which renders class attribute (e.g. `writer.AddAttribute("class", "upload", true)` in its `AddAttributesToRender` method), and you apply a class binding on the markup control (e.g. `<cc:MyUpload class="{value: IsVisible ? 'visible' : 'hidden'}" />`), then the "upload" class is overwritten by the binding. The value should be appended instead.

**Comment by exyi** [comment]
Solved by #196
