### ISSUE TITLE
Allow HTML comment in views

### ISSUE THREAD

**Issue by MarekPokornyOva** [riganti/dotvvm#157]
Hello,
first of all, let me thank you for this great framework and you share it even for free (mostly).

Would it be possible to make recognizing of empty node configurable by a view directive and by application configuration? Without that it isn't possible to render HTML comments to HTML template sent to browser.

View example:
@viewModel DotvvmApplication1.ViewModels.DefaultViewModel, DotvvmApplication1
``<html><head></head><body><!-- Nádhera --></body></html>``

Touched code:
DotVVM.Framework.Runtime.Compilation.ControlTreeResolver
	``if (content.Any(DothtmlNodeHelper.IsNotEmpty))``
DotVVM.Framework.Parser.Dothtml.Parser.DothtmlNodeHelper
``public static bool IsNotEmpty(this DothtmlNode node)
{
	return !(node is DotHtmlCommentNode) &&
		!((node is DothtmlLiteralNode) && string.IsNullOrWhiteSpace((node as DothtmlLiteralNode).Value));
}``

DotVVM version: 0.9.0.0

Thank you
Marek Pokorny

**Comment by exyi** [comment]
@MarekPokornyOva Wow, you have to be a real wizard if you have found how it works in ControlTreeResolver :)
Anyway the check should not be here, thanks for bug report. I don't think that extensibility would have any benefits in this case, as you always want to render control's content
