### ISSUE TITLE
Make TryParseGooglebotHashbangEscapedFragment() usage configurable

### ISSUE THREAD

**Issue by MarekPokornyOva** [riganti/dotvvm#158]
Hello,
would it be possible to make TryParseGooglebotHashbangEscapedFragment() method usage configurable? Someone would find this functionality as an errornous. I understand anyone can make his own MW however from app lifecycle perspective the configuration will be better.

DotVVM version: 0.9.0.0

Thank you
Marek Pokorny

**Comment by tomasherceg** [comment]
Outdated.
