### ISSUE TITLE
Context.Authorize() works differently than [Authorize]

### ISSUE THREAD

**Issue by PavelBansky** [riganti/dotvvm#1580]
I'm using Microsoft.Identity.Web to authenticate using AzureAD

```csharp
services.AddMicrosoftIdentityWebAppAuthentication(Configuration, "AzureAd");
```
After signing out using `contoso.com/signout-oidc` and the accessing `contoso.com/` again I get a different behavior from `Context.Authorize()` and `[DotVVM.Framework.Runtime.Filters.Authorize]`

```csharp
public override Task Init()
{
    Context.Authorize();
    string user = Context.HttpContext.User.Identity.Name;

    return base.Init();
}
```
`Context.Authorize()` just passes through and `Context.HttpContext.User.Identity.Name` is `null`
The whole `User.Identity` is empty and the page is displayed in the browser.

```csharp
[Authorize]
public class DefaultViewModel : MasterPageViewModel
{
```

This works as expected, the browser is redirected to AzureAD login page / re-authentication, and `Context.HttpContext.User.Identity.Name` is filled with proper information about the user.

Chances are, that the `contoso.com/signout-oidc` is not a best way to sign out. 
However, the controllers that should be enabled by `Microsoft.Indentity.Web` are not accessible in the DotVVM project.

In razor/MVC it looks like this.
```
 <a class="nav-link text-dark" asp-area="MicrosoftIdentity" asp-controller="Account" asp-action="SignOut">Sign out</a>
```

But accesing `contoso.com/MicrosoftIdentity/Account/SignOut` in DotVVM project doesn't work :(

Environment:
.NET Core 6.0
Windows
DotVVM 4.1.0

**Comment by exyi** [comment]
Is this on Asp.Net Core or OWIN?

On Asp.Net Core the Authorize method returns Task, so in that case you are missing an `await`. The [AuthorizeAttribute](https://github.com/riganti/dotvvm/blob/main/src/Framework/Hosting.AspNetCore/Runtime/Filters/AuthorizeAttribute.cs#L68) is only calling this function, so I don't see how it could behave differently.

**Comment by PavelBansky** [comment]
It is on ASP.NET Core.

I have changed the Init method from non-async

```csharp
public override Task Init()
{
    return base.Init();
}
```

to async, and it's working fine.

```csharp
public override async Task Init()
{
    await Context.Authorize();    
    
    await base.Init();
}
```

Thanks!
