### ISSUE TITLE
Fix value type as `Validation.Target` produces weird JS error

### ISSUE THREAD

**Issue by acizmarik** [riganti/dotvvm#1583]
Collection as validation target seems to be working already (probably since DotVVM 4.0). However, when user specifies a value type, for example a `DateTime` as a validation target, a weird JS error is produced. This should be fixed.

_Originally posted by @acizmarik in https://github.com/riganti/dotvvm/issues/508#issuecomment-1427758907_

**Comment by exyi** [comment]
It currently isn't producing any error, I'll close this. It still doesn't do what you might expect (validate that one property), so I will at least add a warning.
