### ISSUE TITLE
DotVVM for Visual Studio: The 'DotvvmPackage' package did not load correctly in VS 17.5

### ISSUE THREAD

**Issue by hopix** [riganti/dotvvm#1599]
After installing recent update of VisualStudio the DotVVM extension stops working.
Tried to uinstall and then install extension, but problem persists.

VS version: 17.5.0
Extension version: 4.0.554.0

Error message from VS log:

`SetSite failed for package [DotvvmPackage]Source: 'System.ComponentModel.Composition' Description: The composition produced multiple composition errors, with 2 root causes. The root causes are provided below. Review the CompositionException.Errors property for more detailed information. 1) No exports were found that match the constraint: ContractName DotVVM.Integration.VisualStudio.Dialogs.DialogFactory RequiredTypeIdentity DotVVM.Integration.VisualStudio.Dialogs.DialogFactory Resulting in: Cannot set import 'DotVVM.Integration.VisualStudio.VsPackages.DotvvmPackageDependencies.DialogFactory (ContractName="DotVVM.Integration.VisualStudio.Dialogs.DialogFactory")' on part 'DotVVM.Integration.VisualStudio.VsPackages.DotvvmPackageDependencies'. Element: DotVVM.Integration.VisualStudio.VsPackages.DotvvmPackageDependencies.DialogFactory (ContractName="DotVVM.Integration.VisualStudio.Dialogs.DialogFactory") --> DotVVM.Integration.VisualStudio.VsPackages.DotvvmPackageDependencies 2) No exports were found that match the constraint: ContractName DotVVM.Integration.VisualStudio.Common.Licensing.ILoginProvider RequiredTypeIdentity DotVVM.Integration.VisualStudio.Common.Licensing.ILoginProvider Resulting in: Cannot set import 'DotVVM.Integration.VisualStudio.VsPackages.DotvvmPackageDependencies.LoginProvider (ContractName="DotVVM.Integration.VisualStudio.Common.Licensing.ILoginProvider")' on part 'DotVVM.Integration.VisualStudio.VsPackages.DotvvmPackageDependencies'. Element: DotVVM.Integration.VisualStudio.VsPackages.DotvvmPackageDependencies.LoginProvider (ContractName="DotVVM.Integration.VisualStudio.Common.Licensing.ILoginProvider") --> DotVVM.Integration.VisualStudio.VsPackages.DotvvmPackageDependencies`

**Comment by tomasherceg** [comment]
Unfortunately, this happens almost every time MS publishes a new VS update.
We'll publish a new version of the extension compatible with 17.5 shortly.

**Comment by tomasherceg** [comment]
We've just published a new version 4.0.556 which should work with VS 17.5.
https://www.dotvvm.com/docs/4.0/pages/dotvvm-for-visual-studio/release-notes

Closing the issue now. Feel free to reopen the issue or create a new one in case you encounter any problems.
