### ISSUE TITLE
How to do [AuthorizeForScopes] in DotVVM when using Graph API?

### ISSUE THREAD

**Issue by PavelBansky** [riganti/dotvvm#1612]
I'm trying to read user information using Microsoft Graph API.
Following the example here [2-1-Call-MSGraph/Controllers/HomeController.cs](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/master/2-WebApp-graph-user/2-1-Call-MSGraph/Controllers/HomeController.cs)
I need to specify `[AuthorizeForScopes(ScopeKeySection = "DownstreamApi:Scopes")]` in the controller.

How can I achieve that in DotVVM?

**Comment by tomasherceg** [comment]
I think you can either re-implement the attribute to inherit from DotVVM `ExceptionFilter` class - the logic should be the same - if I understand it correctly, it looks for some section in configuration, build the `AuthenticationProperties` and calls `Challenge` (they return `ChallengeResult` which we don't have in DotVVM, but you can call `context.GetAuthentication().ChallengeAsync` instead).

**Comment by exyi** [comment]
I'd close this, I don't think we can do something in DotVVM to "solve" this. The source code of Microsoft
s implementation is at https://github.com/AzureAD/microsoft-identity-web/blob/master/src/Microsoft.Identity.Web/AuthorizeForScopesAttribute.cs, feel free to ask if there is some problem with reimplementing it on DotVVM interface
