### ISSUE TITLE
Support `capture` attribute on `FileUpload`

### ISSUE THREAD

**Issue by OronDF343** [riganti/dotvvm#1616]
Currently there is no way to control the `capture` attribute on a `FileUpload` control.

The `capture` attribute is used to specify which camera on the device should be used to capture and upload an image. Possible values are: `environment`, `user`. This attribute affects mobile devices only and is ignored on desktop browsers. [More info and examples on MDN.](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/capture)

I suggest adding a property `Capture` of type `string?` to `FileUpload` which, when not null or empty, will generate the `capture` attribute on the hidden `input` element, containing the specified value. The implementation will be similar to `AllowedFileTypes`.

Does this sound OK?

**Comment by exyi** [comment]
Yes, this is definitely reasonable.
