### ISSUE TITLE
ToLower usage in ErrorsTests.cs 

### ISSUE THREAD

**Issue by MarekPokornyOva** [riganti/dotvvm#162]
Hello,
I have little note to a commit 2925a8cd (author: Ladislav Šesták on 14.3.2016 22:26:03).

His code change (begins at line 83 of src/DotVVM.Samples.Tests/ErrorsTests.cs) says:
`s.ToLower().Contains("String was not recognized as a valid Boolean.".ToLower())`

But is it really necessary to make lowercase strings? If we check String.Contains method source, we find:
```
public bool Contains(string value)
{
	return this.IndexOf(value, StringComparison.Ordinal) >= 0;
}
```
We can see it simply uses IndexOf method which has an overload with StringComparison parameter - which would be faster and resources (memory, GC) thrifty.

Suggestion 1:
Simply use `s.IndexOf("String was not recognized as a valid Boolean.",StringComparison.OrdinalIgnoreCase) >= 0;`

Suggestion 2:
Make a String extension:
```
public static class StringExtensions
{
    public static bool Contains(this string self, string value, StringComparison comparisonType)
    {
        return self.IndexOf(value, comparisonType) >= 0;
    }
}
```
Then call `s.Contains("String was not recognized as a valid Boolean.",StringComparison.OrdinalIgnoreCase)`

Well, maybe you don't care about that because it is in test.

Regards
Marek

P.S. Please let me know if I'm wrong or I missed a C# feature.

**Comment by tomasherceg** [comment]
This code appears in UI tests which are slow in general (e.g. launching the browser and loading the page under test takes at least 15 seconds), so this is really not an issue. 

But in the framework code we should of course use Contains with a StringComparison parameter, or the IndexOf, as you suggest.
