### ISSUE TITLE
Case sensitivity in routing

### ISSUE THREAD

**Issue by MarekPokornyOva** [riganti/dotvvm#163]
Hello,
how about case sensitivity in routing?

In DotVVM.Framework.Routing.DefaultRouteStrategy class, there is a GetRoutes() method which skips already registered routes by `.Where(r => !existingRouteNames.Contains(r.RouteName))`.
However in DotVVM.Framework.Routing.DotvvmRouteTable class, there is a Add(string routeName, RouteBase route) method which also checks already registered routes by `if (list.Any(r => string.Equals(r.Key, routeName, StringComparison.InvariantCultureIgnoreCase)))`.

The problem is the first method uses case sensitive check while the second one uses case insensitive. That raises runtime exception.

Marek Pokorny

**Comment by tomasherceg** [comment]
Thanks, it is a really good feedback. Since control and property names in the markup are case insensitive, I suggest we make routes and resource names case insensitive too.

**Comment by exyi** [comment]
Fixed in 98df7f2b. Is it ok now?
