### ISSUE TITLE
Add JS translations for Enumerable Sum

### ISSUE THREAD

**Issue by holajan** [riganti/dotvvm#1691]
There is support for Enumerable.Max and Enumerable.Min method but for Sum is missing.
Please add translations for:
**Enumerable.Sum<T>(IEnumerable<T> collection)** and **Enumerable.Sum<T,U>(IEnumerable<T> collection, Func<T,U> selector)** and implement dotvvm.translations.array.sum.

**Comment by exyi** [comment]
Resolved by  #1698, should be in the next 4.2 release
