### ISSUE TITLE
Dynamic hide and show the EmptyItemText in ComboBox

### ISSUE THREAD

**Issue by holajan** [riganti/dotvvm#1694]
I would like to dynamically use binding expression in the EmptyItemText property in ComboBox control to change whether or not item is displayed.
The property does not support null and defaults to string.Empty, but setting string.Empty behaves differently than if the attribute is not specified.

**Not specifying EmptyItemText:**
![image](https://github.com/riganti/dotvvm/assets/11502624/901884bd-d086-4d16-9ea8-c193537d023b)

**EmptyItemText="":**
![image](https://github.com/riganti/dotvvm/assets/11502624/39084aa9-6583-4573-9c51-486ec015f56a)

**EmptyItemText="{value: OsobaHodnoceniMesic.IDOsobaHodnoceniMesic == 0 ? "[Vyberte]" : null}":**
Error: Unable to get property KnockoutExpressionBindingProperty: Could not implicitly convert expression of type System.Object to System.String. Binding: {value: OsobaHodnoceniMesic.IDOsobaHodnoceniMesic == 0 ? "[Vyberte]" : null}. Property path: KnockoutExpressionBindingProperty, KnockoutJsExpressionBindingProperty.

**EmptyItemText="{value: OsobaHodnoceniMesic.IDOsobaHodnoceniMesic == 0 ? "[Vyberte]" : (string)null}":**
Error: Unable to get property KnockoutExpressionBindingProperty: Unexpected token 'OsobaHodnoceniMesic.IDOsobaHodnoceniMesic == 0 ? "[Vyberte]" : (string) ---->null<---- '. Binding: {value: OsobaHodnoceniMesic.IDOsobaHodnoceniMesic == 0 ? "[Vyberte]" : (string)null}. Property path: KnockoutExpressionBindingProperty, KnockoutJsExpressionBindingProperty, CastedExpressionBindingProperty.

**EmptyItemText="{value: OsobaHodnoceniMesic.IDOsobaHodnoceniMesic == 0 ? "[Vyberte]" : ""}":**
![image](https://github.com/riganti/dotvvm/assets/11502624/b6df7c9d-a578-4539-986f-b851f5d0493f)
For not OsobaHodnoceniMesic.IDOsobaHodnoceniMesic == 0 it is with empty EmptyItem but not without EmptyItem. I would like it to be like in first case when EmptyItemText is not specify.

**Comment by holajan** [comment]
In which version of NuGet is this fix?

**Comment by exyi** [comment]
It is in the  4.2.0-preview09-final version

**Comment by holajan** [comment]
In 4.2.0-preview09-final its working fine. Thanks.
