### ISSUE TITLE
Assembly in Directive is giving an error

### ISSUE THREAD

**Issue by pky00** [riganti/dotvvm#1728]
![Capture](https://github.com/riganti/dotvvm/assets/44399203/ca55698b-4c6d-42db-88d8-214649c0d63d)

I added a new view to my project and I added its URL to the configs. When I build and go to the page it gives me this error. I didn't add anything to the page, this was all generated by dotvvm. What exactly is the issue here ?

**Comment by exyi** [comment]
Looks like we cannot parse the assembly name if it contains a dash.

You can easily workaround it by deleting the assembly name from the directive, it is optional unless there is a name conflict.

```
@viewModel Web.ViewModels.Page1ViewModel
```
