### ISSUE TITLE
How do I connect a ComboBox to a DataTable in .NET ?

### ISSUE THREAD

**Issue by pky00** [riganti/dotvvm#1729]
I have a DataTable from a database, and I need display a column from that table in a Combobox, and have it select the id of that column.

**Comment by tomasherceg** [comment]
Unfortunately, `DataTable` is not serializable - you will need to convert it to a `List<T>` where T will be a normal C# class (POCO).

Then you can bind the `ComboBox` as shown in the examples here: https://www.dotvvm.com/docs/4.0/controls/builtin/ComboBox

I also recommend using GitHub issues only to report bugs or problems with the framework itself. 
For questions about using DotVVM, we have a [Community forum](https://forum.dotvvm.com) where anyone from the community can respond.
