### ISSUE TITLE
Exception when use resource and last character is &

### ISSUE THREAD

**Issue by honzakmenta** [riganti/dotvvm#1736]
When I want to show any string in page as resource and last character of this string is **&** I get exception _Index was outside the bounds of the array._ When I use value instead of resource it is ok. Similarly, if the character & is not at the end but in the middle or at the beginning, everything seems fine.

Steps to reproduce:

**View model:**
`public string Test { get; set; } = "test string &";`

**dothtml:**
`<dot:Literal Text="{resource: Test}" />`

**Comment by tomasherceg** [comment]
Thanks for the report, it looks like we are detecting HTML entities in the strings.
