### ISSUE TITLE
Invocation of static command on ViewModel does not resolve dependecies from IoC

### ISSUE THREAD

**Issue by Ropack** [riganti/dotvvm#1738]
When I create a method in my ViewModel class - class that inherits from `DotvvmViewModelBase`, I give it an `AllowStaticCommand` attribute and call it from View with `staticCommand` binding, then the dependecies in a constructor are not resolved, they are `null` instead. When the same method and dependencies are moved to separate class and I register it to the `serviceCollection`, the dependencies are resolved as expected.

DotVVM version 4.1.0
net7.0

**Comment by exyi** [comment]
This is a known problem (#809), we finally have an option to disable the bug: `DotvvmConfiguration.ExperimentalFeatures.UseDotvvmSerializationForStaticCommandArguments.Enable()`
