### ISSUE TITLE
GridView SortExpression should support property paths, not just simple property name

### ISSUE THREAD

**Issue by tomasherceg** [riganti/dotvvm#177]

**Comment by exyi** [comment]
It would be best if we could support any expression here - in the form of binding in dothtml markup and in the form of Expression<Func<T, object>> in IGridViewDataSet. Unfortunately I don't see easy way to do it without breaking compatibility. Any idea?

**Comment by exyi** [comment]
resolved by  7b0ab37

It does not support any expression, since it has to be serialized/deserialized, but I have added support for property path, which should be good enough.
