### ISSUE TITLE
Dictionary item retrieval binding throws although item exists.

### ISSUE THREAD

**Issue by MichalTichy** [riganti/dotvvm#1781]
Hi,

During postback we are filling collection and in the same request additional metadata are stored for all items inside dictionary.

Unfortunately the binding that retrieves metadata from dictionary fails during render of new items.
![image_6aace769.png](https://github.com/riganti/dotvvm/assets/5333577/123f240e-0645-4fe1-a0f8-7cb7bf172bfa)

-![image_7152a048.png](https://github.com/riganti/dotvvm/assets/5333577/7ece3c1b-1213-4323-a128-4e316ba9ec93)

With following fix everything works fine.
![image_a6d294ab.png](https://github.com/riganti/dotvvm/assets/5333577/cc904e51-dc7e-4a6d-8744-ee2b8706d363)

**Comment by tomasherceg** [comment]
I guess it is caused because the binding accessing the Dictionary is evaluated before the items get in the collection.

I think all JS methods on Dictionary should not throw any exceptions and should do null propagation instead.

**Comment by exyi** [comment]
Agreed, we should avoid throwing exception in most client-side translations. We can then use the same translation for LINQ `First` and `FirstOrDefault`, and similar cases
