### ISSUE TITLE
Pro edition setup

### ISSUE THREAD

**Issue by ndfra** [riganti/dotvvm#182]
I tried to install the package but every time the setup shows me an alert about an instance of VS 2015 already open despite of I had no instance open.
I tried on 2 pcs and I experienced the same issue.

Thanks

**Comment by tomasherceg** [comment]
Can you please look in the Task Manager and verify that there is no process called devenv.exe running?

**Comment by ndfra** [comment]
Hi,

I'm pretty sure that there were not processes called in that name... (it was my first check)

**Comment by tomasherceg** [comment]
OK, thank you, we'll check why the installer doesn't allow to continue.

Are you using local or domain account? Some users with domain accounts had similar problems installing the extension.

**Comment by ndfra** [comment]
First of all, thanks for the support.
I tried with 2 pcs, one of them with domain account and the other one with a local account

**Comment by tomasherceg** [comment]
Sorry for these issues, we'll check what's the problem and get back to you asap.

**Comment by tomasherceg** [comment]
Hi, we have published a new installer on the website - you can login and download the installer (in the My Licenses section). Please let me know whether the installation was successful.

**Comment by ndfra** [comment]
Now it works... 

Thank you
