### ISSUE TITLE
bp:ModalDialog to be adjustable in terms of overlay colour and transparency in the markup

### ISSUE THREAD

**Issue by liviriniu** [riganti/dotvvm#1842]
Please make the overlay of this control capable of being adjusted in terms of colour and transparency in the markup.

taken from here: https://forum.dotvvm.com/t/bp-modaldialog-overlay-colour-and-transparency/240

**Comment by exyi** [comment]
The overlay color (including the alpha channel) can be adjusted using the `--bp-color_base-overlay` CSS variable. It can be also set in the dothtml markup as an inline style, it has to be on the ModalDialog parent element.
