### ISSUE TITLE
Autmate Converter?

### ISSUE THREAD

**Issue by dhavalcharadva-sf** [riganti/dotvvm#1865]
Hi Team,

As we have converter online to convert ASPX code to dotvvm style. Do we have anything as SDK OR Api which can automate this process. I have files in bulk and wanted to do automation.

Any help would be helpful.

Dhaval.

**Comment by exyi** [comment]
The converter source code is available in the [dotvvm-webforms](https://github.com/riganti/dotvvm-webforms) repository, and you can run it yourself on all your files. There isn't a CLI as far as I know, but you can call the C# API directly: https://github.com/riganti/dotvvm-webforms/blob/main/website/DotVVM.Utils.AspxConverter/DotVVM.Utils.AspxConverter.UI/ViewModels/ConverterViewModel.cs.

However, the converter can only convert the basic constructs — I honestly doubt it will be able to migrate any page without any intervention anyway, so full automation isn't really feasible :/
