### ISSUE TITLE
Intellisence suggestion: automatically add parentheses after selecting command

### ISSUE THREAD

**Issue by darilek** [riganti/dotvvm#188]
Hello,
is it possible automatically add (empty) parentheses after command name selected from intellisence context menu?

**Comment by Mylan719** [comment]
I just implemented the feature. It completes function name and:
One brace in cases:
```
//_this.Function#cur# ) 
//_this.Function#cur# arg, arg)
//_this.Function#cur# arg, arg)...() 
```
No brace in case:
```
//_this.Function#cur#(arg, arg)
//_this.Function#cur#()
```
Two braces othervise.

**Comment by exyi** [comment]
@Mylan719 cool. @darilek Thanks for suggestion.

**Comment by darilek** [comment]
Nice... The development is a bit quicker now :+1: :-)
