### ISSUE TITLE
`RegisterScriptModule` obsolete

### ISSUE THREAD

**Issue by tomasherceg** [riganti/dotvvm#1887]
I just noticed that all overloads of `RegisterScriptModule` are obsolete:

https://github.com/riganti/dotvvm/blob/1b8d606c951fcbef5682488869608a1de3353365/src/Framework/Framework/ResourceManagement/ResourceRepositoryExtensions.cs#L81

Is this correct?
I would understand that the overload with the `defer` parameter is obsolete, but I do not see a reason with the other one.

**Comment by exyi** [comment]
No, this is definitely a mistake and we should remove the attribute from the first overload.

Nov 22, 2024 18:58:31 Tomáš Herceg ***@***.***>:
