### ISSUE TITLE
Boolean attributes without value

### ISSUE THREAD

**Issue by djanosik** [riganti/dotvvm#191]
In HTML you can use boolean-like attributes without specifying a value. It would be nice if .dothml could support this.
```html
<dot:Button IsSubmitButton="true" /> vs. <dot:Button IsSubmitButton />
```

**Comment by exyi** [comment]
It is quite good idea in my opinion. I'd add `Switch` property to `MarkupOptionsAttribute` which wound enable this behavior.

**Comment by tomasherceg** [comment]
Can't we just enable it on all boolean properties?

**Comment by exyi** [comment]
@tomasherceg You are right, we can. I was just afraid that it can lead to unexpected behaviour on some properties, but I have not found any in the dotvvm core. I'll implement just after 1.0
