### ISSUE TITLE
Naming of the <dot:IfAuthorized> control

### ISSUE THREAD

**Issue by tomasherceg** [riganti/dotvvm#194]
The `IfAuthorized` control name, which is now in the framework, doesn't make sense. If the user is not authorized, he won't even be allowed to open the page. The correct name would be `IfAuthenticated`, but I don't like the If in the control name.

In ASP.NET Web Forms, there was the `LoginView` control which did exactly the same thing - it had `AnonymousTemplate` and `LoggedInTemplate` properties, and it also allowed to display different content for each role. In DotVVM, we should have something similar, maybe we could preserve the naming.

```
<dot:LoginView>
    <AnonymousTemplate>
        This will be displayed to non-authenticated users.
    </AnonymousTemplate>
    <LoggedInTemplate>
        This will be displayed to authenticated users.
    </LoggedInTemplate>
</dot:LoginView>
```

The role functionality can be easily implemented by a separate control `RoleView`:

```
<dot:RoleView Roles="admin,moderator">
    This will be displayed only to the users which have the role
</dot:RoleView>
```

Also, we could have a similar control for specific app environments:

```
<dot:EnvironmentView Name="debug">
    This will be displayed only in the debug environment.
</dot:EnvironmentView>
```

Or shall the control names be `IfLoggedIn` (or `IfAuthenticated`), `IfInRole` (or `IfRoleMember`), `IfEnvironment` with templates called `TrueTemplate` and `FalseTemplate`?

Do you have another ideas?

**Comment by exyi** [comment]
I don't care about the naming much, but I'd not split it into multiple ones if they do almost the same, only difference is that one cares about roles and one not.

**Comment by Mylan719** [comment]
@tomasherceg I think naming you proposed makes much more sense. This convention looks good. Presonaly I had struggle understanding what `IfAuthorized`does. Moreover it implies there is some if-else flow control in the file, which would be... unsettling :). But maybe It would be more intuitive if you had only `AuthenticatedView` control with optional property `Roles`?

**Comment by djanosik** [comment]
Well, the `IfAuthorized` name does make sense. In fact it is mostly used for authorization and not for authentication (with exception of the login form). I am completely OK with the `If` keyword in the name (`IfAuthorized`, `IfEnvironment`, `IfAnonymous`, ...).

The `LoginView` name makes an assumption the control will only be used to show / hide a login form.  I think it isn't good idea. And we don't need a `RoleView` control :) The `IfAuthorized` control can handle this and we should move on to claims-based authorization.

I agree it might be better to use `TrueTemplate` and `FalseTemplate` instead of `IfTemplate` and `ElseTemplate`. But I don't like the `Template` suffix. It's an internal detail and should not be exposed to users / API consumers.

```html
<dot:IfAuthorized Claims="not sure">
  <True />
  <False />
</dot:IfAuthorized>
```

**Comment by tomasherceg** [comment]
I'd prefer the properties are called `TrueTemplate` and `FalseTemplate`, but we could allow also the short names True and False, same as the attribute class names in .NET behave.

Maybe it could be like this:

```
<dot:IfUser Claims="claim1">
    <True>The user has the claim1.</True>
</dot:IfUser>
```

```
<dot:IfUser Roles="role1">
    <True>The user is in role role1.</True>
</dot:IfUser>
```

```
<dot:IfUser IsLoggedIn>
    <True>The user is logged in.</True>
</dot:IfUser>
```

Which brings me to the idea that we could have the generic `<dot:If Condition="{value: expression}">` control which evaluates the expression on the server and renders only the True or False template since currently we don't have a way to tell DotVVM that it should not render something - we can only hide it using the `Visible` property, or remove it from the DOM if we set `DataContext` to null.

**Comment by djanosik** [comment]
I like the `IfUser` control. :-) But what if I don't specify any attributes? Also... I am not sure about the `Claims` attribute, because we need to specify name and value of the claim.

**Comment by exyi** [comment]
@tomasherceg And what about `<dot:While>` and `<dot:GoTo>` :P
Seriously, Value binding has to be translatable to javascript and IsLogged and HasRole is pretty badly translatable.

The `IfUser` is good idea I'm my opinion, maybe it could be `IfLogged` since you always want the `IsLoggedIn` behavior. But I don't like the TrueTemplate and FalseTemplate, I'd like something like `Authorized` and `Unauthorized` more.

@djanosik Claims could be solved by special syntax for dictionary, like `Claims="Name: whatever, Another: something"` or binding: `ClaimsCondition={value: ContainsKey("Name") && _this["Name"] == "whatever"}`. Or something similar to Param- attribute on RouteLink, like `Claim-Name="the name"`

**Comment by tomasherceg** [comment]
@exyi We could also rename `<dot:Repeater>` to `<dot:ForEach>` to be consistent... :-)
I thought that the `<dot:If>` would always evaluate the binding on the server side and provide a way to not render a part of a control tree at all because we don't have such option now.

The `<AuthorizedTemplate>` and `<UnauthorizedTemplate>` looks also good to me. Also, I really like the `Claim-Name="something"` syntax, it is a good idea.

**Comment by tomasherceg** [comment]
And about the `<dot:IfUser>` vs `<dot:IfLogged>`, the "if logged" makes sense, but in that case it should be `<dot:IfLoggedIn>` (to make it a correct phrase in English), or the `<dot:IfAuthenticated>` mentioned originally.

**Comment by quigamdev** [comment]
`<dot:If Condition="{value: expression}"> ` this piece of code looks like MSBuild :D

I prefer `AuthenticatedView` suggested by @Mylan719 
`AuthenticatedTemplate` and `AnonymousTemplate` for this component seem to me be OK. 

What about to add something like `<div RenderSettings.Render="{value: ServerEvaluatedCondition }">` or perhaps `<div CanRender="{value: ServerEvaluatedCondition }">`?
When the condition is false the element is not simply rendered.

I tried to understand why you want the <dot:ifsomehting> controls. It seem to me like dot:goto. 

About the claims. How these components will react when CurrentPrincipal is GenericPrincipal instance?

**Comment by tomasherceg** [comment]
OK, to sum this up, we just need:

* A control that renders something to an user, who is authenticated, or who is not authenticated.

* A control that renders something if the user is in some role.

* A control that renders something based on the user's claim.

* A control that renders something based on the environment (production, test, staging etc.).

* A control that renders or doesn't render something based on a server condition.

I don't want while, goto or fors in the markup, the "if" is just enough. 
I just wanted the naming to be consistent, that's why I've suggested `<dot:IfUser>`, `<dot:IfEnvironment>` and because these classes would probably inherit from some BaseIfControl, why not just add `<dot:If>` and evaluate the condition on server. This approach would solve all points I have mentioned before and the naming is consistent. Also, it would be extensible and we may later need something like `<dot:IfConfiguration>` etc. 

P.S. If you want to test the claims and the identity would be GenericPrincipal, I don't think that we should throw an exception. I'd prefer the condition to be evaluated to `false` because the generic identity has no claims.
