### ISSUE TITLE
Validator.InvalidCssClass and  Validator.ShowErrorMessageText not working with Bootstrap controls

### ISSUE THREAD

**Issue by martinsura** [riganti/dotvvm#201]
Hi,

With code 

```
Validator.InvalidCssClass="has-error" Validator.ShowErrorMessageText="true" 
```
defined on body element and html  code:

```
<bs:FormGroup LabelText="LabelTest" Validator.Value="{value: Model.Name}">
          <dot:TextBox  Text="{value: Model.Name}" placeholder="Placeholder test"></dot:TextBox>
          <dot:Validator Value="{value: Model.Name}" ></dot:Validator>
 </bs:FormGroup>
```

dot:Textbox not showing up. 

Using latest bootstrap framework and controls (1.0 RTM)

**Comment by tomasherceg** [comment]
This is the correct behavior.

`Validator.ShowErrorMessageText="true"` basically says that the contents of this element will be replaced by the error message, and it will be empty when the field is valid. You shouldn't set the Validator.ShowErrorMessageText globally. Instead, apply it to each `<dot:Validator>` control.

```
<bs:FormGroup LabelText="LabelTest" Validator.Value="{value: Model.Name}">
    <dot:TextBox  Text="{value: Model.Name}" placeholder="Placeholder test"></dot:TextBox>
    <dot:Validator Value="{value: Model.Name}" ShowErrorMessageText="true"></dot:Validator>
</bs:FormGroup>
```

If you want to apply this globally, we have an undocumented feature called Server Side Styles - in the `DotvvmStartup` you can call something like this:

```
configuration.Styles.Register<Validator>()
    .SetDotvvmProperty(Validator.ShowErrorMessageText, true);
```

**Comment by martinsura** [comment]
Yep, server side styles working fine. Thanks for help

**Comment by exyi** [comment]
Just be careful, they are undocumented and probably the API will change a bit in future ;).
