### ISSUE TITLE
Compose binding like in DurandalJS

### ISSUE THREAD

**Issue by crisim** [riganti/dotvvm#203]
I'd like to propose the compose binding just like the one in the DurandalJS framework. Here the [docs ](http://durandaljs.com/documentation/Using-Composition.html).
it's really like the ContentPlaceHolder but it can contain other views that can be linked dynamically (at runtime).
it can be usefull if you want to display a tabbed control with different content on each tab.

**Comment by exyi** [comment]
We have `ITemplate` properties that serve a similar purpose. If you'd want to set them globally, you could use server side styles. For any specific use cases, feel free to ask on our gitter channel
