### ISSUE TITLE
FormatString bug with unassigned property

### ISSUE THREAD

**Issue by MichalOberreiter** [riganti/dotvvm#204]
Hi guys,
I found a problem that I would like to solve:

HTML:
   `<dot:TextBox Text="{value: DoubleProperty}" FormatString="N2" />
   <dot:Button Text="Set value" Click="{command: SetDoubleProperty()}"></dot:Button>`

C#:
   `  public double DoubleProperty { get; set; }
      public void SetDoubleProperty()
     {
         DoubleProperty = 10.5;
     }
`
If I enter the page for the first time and click the button, DoubleProperty is correctly filled with value and I see this value in TextBox. BUT when I click to TextBox at first and then click the button, DoubleProperty is filled on server side, but NOT in client side, so I will never see value in TextBox.

It can be solved with
    `  public double DoubleProperty { get; set; } = 0;`

but it is not good solution.
Thx for help
Cheers

**Comment by exyi** [comment]
I have fixed it now, sorry for the problems and thank you for your easy to replicate report. You can try current version from git.

And by the way never ever use `if(!result) {` as null check in Javascript if the result is not object, see the [fix](https://github.com/riganti/dotvvm/commit/c138e27322b250f9f2b489982fec0168027094e1) ;)

**Comment by MichalOberreiter** [comment]
Nice :-)
Thanks for quick feedback and fix!
