### ISSUE TITLE
Repeater - add SeparatorTemplate property and _collection variable

### ISSUE THREAD

**Issue by tomasherceg** [riganti/dotvvm#205]
The `Repeater` control needs the `SeparatorTemplate`. 

Also, it would help, if you can access the current item index in the `ItemTemplate` of a `Repeater` or similar data-bound control - Knockout JS supports the `$index` observable context property which returns the index of a current item.

Inside the `ItemTemplate`, you could use the following properties:
- `_collection.Index`
- `_collection.IsFirst`
- `_collection.IsLast`
- `_collection.IsOdd`
- `_collection.IsEven`

It would also be nice if any control could extend the DataContext with these contextual variables to provide special functions.

**Comment by exyi** [comment]
`_collection` is done

**Comment by ENgateman** [comment]
@exyi Um, actually, _collection is missing the IsLast property. :)

I just noticed that while writing a UI test. I had a quick look into the 'BindingCollectionInfoExtensionParameter' class and I get that the implementation of this property is problematic. I just thought that if we're going to drop that feature, it should be mentioned in this issue.

**Comment by exyi** [comment]
@ENgateman I'm sorry, the implementation would be quite problematic, as it is not very easy to get access not only to the index but also to the collection. And it is much needed and it is worth it.
