### ISSUE TITLE
Simple TreeList/TreeView control

### ISSUE THREAD

**Issue by martinsura** [riganti/dotvvm#213]
I'd like to propose the implementation for an simple TreeList/TreeView control for recursive data. (CategoryTree etc)

**Comment by exyi** [comment]
We surely need control for hierarchical data. I think we should add at least some base class and hierarchical "repeater" in core dotvvm, smart TreeView will be probably in commercial control pack.

**Comment by martinsura** [comment]
Yep, hiearchical repeater sounds good.

**Comment by tomasherceg** [comment]
Business Pack Beta 2.0 contains HierarchyRepeater and TreeView controls. 
Based on feedback we get, we'll decide if we add this control in the framework itself - some base class for hierarchical controls could be useful.

**Comment by exyi** [comment]
We now have HierarchyRepeater in the framework.
