### ISSUE TITLE
@parent*ViewModel and @rootViewModel directives in markup controls

### ISSUE THREAD

**Issue by tomasherceg** [riganti/dotvvm#214]
Currently, there is no way to use `_parent` and `_root` bindings in the markup controls. 
We should support the `@parent1ViewModel`, `@parent2ViewModel`... and `@rootViewModel` directives to be able to reference parent contexts from the control (which is often very useful and currently we have to copy-paste lots of code because it is just not reusable).

**Comment by exyi** [comment]
I don't like this solution - It would require us to redesign a nontrivial part of the compiler and extension and it will become quite complicated when you will try to use control with such constraints. I'm not looking forward for code like:
```html
<div DataContext="{value:_root}">
<div DataContext="{value: _parent}">
<div DataContext="{value: _root.ThePopupModel}">
....
```
I'm closing this one as undoable. We have other options how to inject parts of viewModel to controls, like DotvvmProperties. They can also be inherited, so you can apply some service-like part of VM in the master page and all control would be able to use it.
