### ISSUE TITLE
Knockout if binding

### ISSUE THREAD

**Issue by crisim** [riganti/dotvvm#215]
I'd like to propose the implementation of the if binding like stated in the knockout docs [here](http://knockoutjs.com/documentation/if-binding.html).

in particular the syntax

```
    <!-- ko if: someExpressionGoesHere -->
        <li>I want to make this item present/absent dynamically</li>
    <!-- /ko -->
```

the content wil NOT be rendered until the expression goes to true.
this way i can implement a dynamic form. ;)

**Comment by tomasherceg** [comment]
Currently we have the `Visible` property which hides the content using CSS. Also, we can do something similar using the `DataContext` property - if it is null, the content is removed from the DOM.

We should add another property that indicates this binding, but we should give it a reasonable name. Any ideas?

What about `Rendered` or `IncludedInPage`? 

Also, I think there are some restrictions in Knockout which prevent using `if` and `with` together.

**Comment by crisim** [comment]
the property name should be at present tense.

`IncludeInPage` or `MustRender` or, reversing the logic, `SkipRendering`.

there's shouldn't be any problem with the `with` binding.

**Comment by tomasherceg** [comment]
`IncludeInPage` sounds good to me.

**Comment by tomasherceg** [comment]
We need mor UI tests which use complex controls like `Repeater`:

* `Repeater` rendering `tbody` wrapper tag inside `table`
* `GridView` + `EmptyDataTemplate`
* Combinations with `Visible` and `DataContext`

And we need documentation for this.

**Comment by exyi** [comment]
It seems to be covered pretty well in https://github.com/riganti/dotvvm/blob/edb0cbee22e79236769e5eb666731b9f63826cb0/src/DotVVM.Samples.Common/Views/ControlSamples/IncludeInPageProperty/IncludeInPage.dothtml
