### ISSUE TITLE
Authorization filters for custom presenters

### ISSUE THREAD

**Issue by CristianT** [riganti/dotvvm#216]
My application has a global authorization filter like this:

`config.Runtime.GlobalFilters.Add(new AuthorizeAttribute());`

As a user I understand that the authorization applies to any request handled by dotvvm but that is not the case of custom presenters:

`config.RouteTable.Add("UpdateValue", "UpdateValue/{Id?}", null, null, () => new UpdateValuePresenter());`

The attribute Authorize does not work either.

```
    [Authorize]
    public class UpdateValuePresenter : IDotvvmPresenter
```

So I have to implement the authorization myself.
If this is the intended behavior at least a comment in the documentation would be nice.

**Comment by tomasherceg** [comment]
Thanks for the feedback, it is a very good point. 
I think we should support the filters even on the presenters.

**Comment by exyi** [comment]
Done in #261
