### ISSUE TITLE
RouteLink ignores "false" value in Enabled property 

### ISSUE THREAD

**Issue by quigamdev** [riganti/dotvvm#218]
The RouteLink component ignores static boolean values. 

`<dot:RouteLink Enabled="false" RouteName="TestRoute" Text="Test" />`  - this code still allows you to redirect. 
`<dot:RouteLink Enabled="{{value: false}}" RouteName="TestRoute" Text="Test" />` - this code works properly.

**Comment by exyi** [comment]
Leave a comment
