### ISSUE TITLE
Review the exeception text when ViewModel contains non-serializable object

### ISSUE THREAD

**Issue by quigamdev** [riganti/dotvvm#220]
`System.Exception: deBase. Check out general viewMode recomedation at http://www.dotvvm.com/docs/tutorials/basics-viewmodels...`

This exception message I had gotten. Cannot clearly say what is the `deBase.`. When I copy whole the link it returns 404. 

At least, it would be nice to render the referring link as a hyperlink.

**Comment by tomasherceg** [comment]
Actually, these are two issues. One of them is the error message and missing documentation page. The second is in the error page - first letters of the actual error message are cut off.
