### ISSUE TITLE
Bootstrap controls not working with DotVVM 1.0.1

### ISSUE THREAD

**Issue by crisim** [riganti/dotvvm#223]
after 14 days 1.0.1 is out, bootstrap controls are not working (at least the datepicker, but all the ones depending on globalize). i'm sticking to 1.0.0, but i wonder when i'll be able to upgrade...

**Comment by tomasherceg** [comment]
Sorry for longer waiting, we have just published version 1.0.2 of both DotVVM and Bootstrap controls.
