### ISSUE TITLE
Route Group

### ISSUE THREAD

**Issue by parmap** [riganti/dotvvm#224]
Very nice feature is route grouping. The advantage of this feature is ability to define e.g. filters in one place, which will apply for all routes inside group. Nested groups would be fine. Of course route settings should override group settings.

What could be able to specificy: filters, route prefix, view virtual path

**Comment by exyi** [comment]
You mean something like:
```C#
routes.AddGroup(name: "Admin", prefix: "admin", virtualPath: "Views/Administration", content: adminRoutes =>
{
    adminRoutes.Add("Users", "users", "Users.dothtml"); // name = Admin_Users, path = "admin/users", virtualPath = "Views/Administration/Users.dothtml"
});
```
I agree it would be nice.
