### ISSUE TITLE
Route and QueryString parameter binding

### ISSUE THREAD

**Issue by tomasherceg** [riganti/dotvvm#229]
Currently, if you want to access the route and query string parameters in the viewmodel, you have to use the `Context.Parameters` or `Context.Query` collections and search for the parameters manually.

We need to introduce parameter binding attributes, something like this:

```
public class PageViewModel : DotvvmViewModelBase
{
    [FromRoute("id")]
    public int CustomerId { get; set; }

    [FromQuery("pageSize")]
    public int PageSize { get; set; }
}
```

The logic should be implemented in the `DotvvmViewModelBase` class in the `Init` method.

**Comment by exyi** [comment]
What about to allow constructor injection
```C#
public PageViewModel([FromRoute] string id, [FromQuery] int pageSize)
{
    if (!ValidateId(id)) throw new Exception(...);
    if (pageSize > 100) throw...;
    CustomerId = id;
}
```

**Comment by tomasherceg** [comment]
I'd delay the constructor injection to a later time because we don't know whether it is possible to integrated with DI mechanism on .NET Core.

**Comment by darilek** [comment]
What about attribute additional options, eg. Required, Regexp, DefaultValue etc.? It would be useful especially for FromQuery attr

**Comment by darilek** [comment]
It would be also nice to have:
* define custom parameter name mapping - property name != parameter name
* automatic mapping to enumeration members (values or names)

example:
```c#
public enum SortDirection 
{
  Ascending = 0,
  Descending = 1
}

[FromQuery(ParameterName="direction")]
public SortDirection {get; set;}
```

URL sample: `http://www.foo.com/bar?direction=0` or `http://www.foo.com/bar?direction=ascending`

**Comment by tomasherceg** [comment]
There are few aspects I'd like to point out:

* `[FromQuery(ParameterName = "direction")]` definitely - I'd make the ParameterName default sou you can only use `[FromQuery("direction")]`.

* We can add the `Required` property to the `FromQuery` attribute (the `FromRoute` doesn't need it because it is specified in the route table).

* I'd rather avoid adding the `RegularExpression` or other validations directly in the `FromQuery` parameter. Instead of that, I'd put there the `Constraint` property which would use the same syntax and infrastructure as the route constraints. For example, if you want something similar to `customer/edit/{Id:int}` (Id is required and integer), but using query string, the attribute would look like this:
`[FromQuery("Id", Constraint = "int", Required = true)]`.

* Also, it would be nice if the `[FromQuery]` and `[FromRoute]` attributes implemented a common interface `IParameterBindingAttribute` with a method `object BindParameter(IDotvvmRequestContext requestContext)`, so it would be easy to implement another parameters (e.g. cookies).

**Comment by exyi** [comment]
Maybe it would make sense to support query strings in routes. Something like:

* `/article?id={Id:int}&diplayComments={DisplayComments?:bool}`

It would allow you to distinguish between pages based on passed query parameters. like:
* `/articles?author={AuthorId:int}` - author's articles is different view
* `/articles` - generic list of articles

And it would be possible to add common query parameter for route group, if #224

**Comment by darilek** [comment]
@tomasherceg  I agree with `Constraint` property instead of `RegularExpression`. It looks promising. Complex parameter validations can be performed in `Init()` phase

**Comment by tomasherceg** [comment]
@exyi I won't mess the query parameters in the routes for now.
