### ISSUE TITLE
Validation in nested viewmodel not working when Validation.Target is List<T>

### ISSUE THREAD

**Issue by quigamdev** [riganti/dotvvm#230]
I have code like this:

```
<div Validation.Target="{value: SomeList}">
<dot:repeater DataSource="{value: SomeList}">
....
</dot:repeater>
<dot:Button Click="{command: _parent.Validate()}" />
</div>
```

This code generates javascript validation expression like this `()[0]().Data`, which throws error.

**Comment by tomasherceg** [comment]
Have we checked that `Validation.Target` works also on primitive types?

I am also looking forward to support tuples in `Validation.Target` - we mustn't forget about this when implementing #280.

**Comment by exyi** [comment]
Validation.Target only validates properties inside the validated object, not the property itself so there is nothing to validate inside primitive types. We can probably change that behavior but I'm afraid it is not a trivial change. If you think it's a good idea, I'd add that as separate issue.

**Comment by tomasherceg** [comment]
If it is difficult to do, we can just check that `Validation.Target` is an object and if not, throw an exception. Last week someone pointed out that on `int` it just doesn't work and no meaningful exception is reported.

**Comment by quigamdev** [comment]
I think that this behavior should be supported. I have heard from more then 3 persons that they expected that validation for only one property works.

Please create a separate issue.
