### ISSUE TITLE
FileUpload - add property for accepted files

### ISSUE THREAD

**Issue by quigamdev** [riganti/dotvvm#231]

**Comment by exyi** [comment]
This is probably already solved by @djanosik at 3e6b9b2a4da239814692f94d7c4dcba8a83e497c

**Comment by djanosik** [comment]
It's not. I didn't add AcceptedFiles property to Core FileUpload control.

**Comment by djanosik** [comment]
Fixed in d080de05c9df7afc7a9b7531e08aecc092aa1570.

- `FileUpload.AllowedFileTypes`
- `UploadedFile.FileTypeAllowed`
