### ISSUE TITLE
CssClass on GridView column dosn't work

### ISSUE THREAD

**Issue by Mitroz** [riganti/dotvvm#233]
You can try it on grid examples with alternate rows

**Comment by Sejsel** [comment]
CssClass on GridView column does work correctly. The issue was into the samples. CssClass for GridViewTextColumns is applied to <td> table cells. The samples had the styles applied to <tr>.

It is fixed now. Thank you for the report.

**Comment by Mitroz** [comment]
Is there possibility of hide columns in grid dynamically? I tried set CssClass and HeaderCssClass style to visibility: collapse by binding. For header this work correctly but for cells in the column not.
In combination with broken sample I thought it was bug.

**Comment by exyi** [comment]
@Mitroz It should be possible to do that using css class. When you look in the debug tools, is the class assigned to the td element? Could you please share with us your code, if it still does not work?

**Comment by Mitroz** [comment]
I found it :-). When inline editing is enabled, css class isn't assigned to td element. I tried disable inline editing and style works fine.

**Comment by Sejsel** [comment]
@Mitroz Alright, I fixed that as well. If you find anything else that is not working how it's supposed to, feel free to report it. Thank you :)
