### ISSUE TITLE
Getting 500.22 internal server error

### ISSUE THREAD

**Issue by paulvanbladel** [riganti/dotvvm#239]
My visual studio 2015 and local IIS  work correctly for asp.net and webform apps.
I installed dotvvm and just created a new dotvvm project without any alterations and getting:
![image](https://cloud.githubusercontent.com/assets/4886272/18339722/6d340ee2-75a1-11e6-9fe2-88059535b6d9.png)

Any idea?

**Comment by djanosik** [comment]
It looks like an issue with Web.config. Can you check your configuration?

**Comment by paulvanbladel** [comment]
Hi Dusan,
Thanks for the prompt feedback.
Just to be sure. When I install the dotvmm vs template, create a new project based on it and make no alterations whatsoever is that scenario supposed to work out of the box?

My webconfig is the one that get's installed out of the box:

```
<?xml version="1.0"?>
<configuration>
  <appSettings>
    <add key="aspnet:UseTaskFriendlySynchronizationContext" value="true"/>
  </appSettings>
  <system.web>
    <compilation debug="true" targetFramework="4.5.1"/>
    <httpRuntime targetFramework="4.5"/>
    <httpModules>
      <add name="ApplicationInsightsWebTracking" type="Microsoft.ApplicationInsights.Web.ApplicationInsightsHttpModule, Microsoft.AI.Web"/>
    </httpModules>
  </system.web>
  <system.webServer>
    <modules runAllManagedModulesForAllRequests="true">
      <remove name="ApplicationInsightsWebTracking"/>
      <add name="ApplicationInsightsWebTracking" type="Microsoft.ApplicationInsights.Web.ApplicationInsightsHttpModule, Microsoft.AI.Web"
        preCondition="managedHandler"/>
    </modules>
    <validation validateIntegratedModeConfiguration="true"/>
  </system.webServer>
</configuration>
```

**Comment by tomasherceg** [comment]
There should be ```<validation validateIntegratedModeConfiguration="false"/>```.

Weird, when I create a new project, I have `false` there and it works.

**Comment by paulvanbladel** [comment]
Many thanks that solved the problem. I definitely did not update that value manually.

**Comment by tomasherceg** [comment]
Thanks, I'll try to find out what could affect that value - maybe the application insights.
