### ISSUE TITLE
Remove DotVVM extension from Visual Studio 2015 

### ISSUE THREAD

**Issue by pemi** [riganti/dotvvm#241]
I would like to know how to uninstall this extension from VS Community 2015.
In Tools/Extensions and Updates I'm getting message that the product cannot be disabled or uninstalled and there is no uninstall icon in Control Panel Uninstall a program.
I'm running Windows 10.

**Comment by tomasherceg** [comment]
Sorry, we have found our installer had an issue which didn't create an entry in the Uninstall a program window in Control Panel.

We have fixed the issue so you can uninstall DotVVM from Visual Studio by installing our latest version from https://www.dotvvm.com :-) and then removing it from Control Panel. 

We apologize for such complicated approach. Please let us know if you have another problems so we can fine-tune the installation and uninstallation process.
