### ISSUE TITLE
Using Emmet autocomplete in .dotmaster file crashes Visual Studio 2015

### ISSUE THREAD

**Issue by mdocter** [riganti/dotvvm#242]
I'm not sure if Visual Studio natively has Emmet (aka Zen Coding) as feature or if it's added by my Web Essentials extension, but when I use it in a .dotmaster file, my Visual Studio crashes. For example when I want to add a simple Bootstrap Grid Row (div with class 'row') I type: 

    .row<tab>

 When pressing the tab key for the autocomplete to kick in VS2015 crashes and restarts.

I'm using the latest 1.4.3 version of the dotVVM extension.

**Comment by Mylan719** [comment]
It seems this feature is added by WebEssentials. So probably we do something they don't expect, or vica versa.
It is supprising that it can take whole VS down. It produces  COMException exception in WindowsBase, so  this will be an interesting bug hunt,

**Comment by mdocter** [comment]
You're welcome. I'm glad you could reproduce it.
Hope you can find what causes this, because Emmet is very convenient to have/use in HTML a-like files.

**Comment by Mylan719** [comment]
I've  just commited the fix. We will deliver it soon.

**Comment by quigamdev** [comment]
Hi, we just released a new version of DotVVM for Visual Studio, where this issue is fixed. Please let us know whether everything is ok and we can close this issue.

Thank you!

**Comment by mdocter** [comment]
Works great! 
Emmet autocompletes correctly and no more VS2015 crash. Thank you for fixing this.
