### ISSUE TITLE
Binding on GridColumn with _parent. throws DotvvmCompilationException

### ISSUE THREAD

**Issue by Mitroz** [riganti/dotvvm#249]
I'm using CssClass and HeaderCssClass for hidding columns on grid dynamically by binding.
When is binding defined as '{value: _parent.xxxxxx }'  result on DotvvmCompilationException.

DotVVM.Framework.Compilation.DotvvmCompilationException: The binding '{ValueBindingExpression: _parent.xxxxx }' is not valid!

StackTrace:
`ClassName:DotVVM.Framework.Compilation.DotvvmCompilationException
Message:The binding '{ValueBindingExpression: _parent.TechnicianNameCss }' is not valid!
Data:
InnerException:
{
ClassName:System.Exception
Message:Could not resolve identifier '_parent.TechnicianNameCss'.
Data:
InnerException:
HelpURL:
StackTraceString: at DotVVM.Framework.Compilation.Binding.UnknownStaticClassIdentifierExpression.get_Type() at DotVVM.Framework.Compilation.ControlTree.DefaultControlTreeResolver.CompileBinding(DothtmlBindingNode node, BindingParserOptions bindingOptions, IDataContextStack context)
RemoteStackTraceString:
RemoteStackIndex:0
ExceptionMethod:8 get_Type DotVVM.Framework, Version=1.0.5.1, Culture=neutral, PublicKeyToken=23f3607db32275da DotVVM.Framework.Compilation.Binding.UnknownStaticClassIdentifierExpression System.Type get_Type()
HResult:-2146233088
Source:DotVVM.Framework
WatsonBuckets:
}
HelpURL:
StackTraceString: at DotVVM.Framework.Compilation.ControlTree.Resolved.ResolvedBinding.GetExpression() at DotVVM.Framework.Compilation.BindingCompiler.<>c__DisplayClass10_0.<EmitCreateBinding>b__1() at DotVVM.Framework.Compilation.BindingCompiler.TryExecute[T](DothtmlNode node, String errorMessage, BindingCompilationRequirementType requirement, Func`1 action) at DotVVM.Framework.Compilation.BindingCompiler.EmitCreateBinding(DefaultViewCompilerCodeEmitter emitter, ResolvedBinding binding, String id, Type expectedType) at `

**Comment by martinsura** [comment]
Yep, _parent binding in GridView (Column) not working for me too

**Comment by exyi** [comment]
It only works slightly different than you'd expect and than the old deployed VS Extension thinks. HeaderCssClass, HeaderText, HeaderTemplate and few more properties are in the datacontext of GridView, not item of the data source. Try to use _this instead of _parent, it will probably work for you. If the VS Extension is claiming that it is wrong, you have too old version and we should deploy a new one.

**Comment by Mitroz** [comment]
I will try explain my design. I have abstract base viewModel with collection of items which is dataSource for grid. I need display dynamically some columns on grid for inheritors of base ViewModel. Concrete inheritor knows which columns need hide or show by overrided string properties with css class name (HeaderCss...)

It is reason why i needed access to _parent from GridView and set css class for dynamicall columns. Now I must copy css class name to every instance item(row) in grid dataSource which seems unnecessary.

**Comment by Mitroz** [comment]
And why _parent binding works for commands (for example RowDecorators) but for value bindings not? :)

**Comment by exyi** [comment]
@Mitroz I don't quite understand what is the problem in your setup. Accessing _parent should be normally possible, it works on my mashine :)
The reason why you have different context in RowDecorator and HeaderCssClass is that RowDecorator "sees" the current item from DataSource, because it is rendered for each row, but Header[...] is in the header so it is the GridView's context.

**Comment by Mitroz** [comment]
I would like to know where problem is :) 
OK, my code of marcup control:

```
@viewModel Mediaresearch.SimWeb.ForTech2.Web.ViewModels.TasksViewModelBase, Mediaresearch.SimWeb.ForTech2.Web
<dot:GridView DataSource="{value: Tasks}" class="table table-hover" InlineEditing="true">
    <RowDecorators>
        <dot:Decorator class="{value: ColorClass}" />
    </RowDecorators>
    <Columns>
        <dot:GridViewTextColumn HeaderText="Name" ValueBinding="{value: ContactName}"   IsEditable="false" />
        <dot:GridViewTextColumn HeaderText="Address" ValueBinding="{value: ContactAddress}" IsEditable="false" />
        <dot:GridViewTextColumn HeaderText="Phone number" ValueBinding="{value: _parent.PhoneNumber}" IsEditable="false" CssClass="{value: PhoneNumberCss }" HeaderCssClass="{value: _parent.PhoneNumberCss }"/>
        <dot:GridViewTextColumn HeaderText="Description" ValueBinding="{value: Description}" Width="120" IsEditable="false" />
        <dot:GridViewTextColumn HeaderText="Technician" ValueBinding="{value: TechnicianName}" AllowSorting="true" IsEditable="false" CssClass="{value: TechnicianNameCss }" HeaderCssClass="{value: TechnicianNameCss }"/>

```

Column PhoneNumber throws exception, column Technician works ok because accessing to item property. 
Maybe problems it in bindings inside controls?

**Comment by exyi** [comment]
@Mitroz I probably could not replicate your problems :(. Just make sure that using `HeaderCssClass="{value: _this.PhoneNumberCss }"` will not help. Maybe the `TechnicianNameCss` will also make some problems. Also don't look at what VS Extension says you, it is probably bit outdated.

**Comment by Mitroz** [comment]
Result with _this
DotVVM.Framework.Compilation.DotvvmCompilationException: The binding '{ValueBindingExpression: _this.PhoneNumberCss }' is not valid!

I will try prepare sample project and replicate error.

**Comment by Mitroz** [comment]
Simple example project attached

[CssClassBinding.zip](https://github.com/riganti/dotvvm/files/498742/CssClassBinding.zip)

**Comment by exyi** [comment]
@Mitroz when I turned the problematic _parent to _this it seems to work, if I understand your need correctly. I tried to explain where the properties are bound:
``` html
<dot:GridViewTextColumn ValueBinding="{value: Id}" />
<dot:GridViewTextColumn ValueBinding="{value: Column1}" />

<%-- both HeaderCssClass and CssClass are bound to the same property --%>
<dot:GridViewTextColumn ValueBinding="{value: Column2}" HeaderCssClass="{value: _this.HiddenColumnClass}" CssClass="{value: _parent.HiddenColumnClass }"/>

<%--semantically same as above--%>
<dot:GridViewTextColumn ValueBinding="{value: Column2}" HeaderCssClass="{value: _root.HiddenColumnClass}" CssClass="{value:_root.HiddenColumnClass }" />

<%--works but this is binding to grid item and i don't want this -- The HeaderCssClass is bound to _root.HiddenColumnClass, CssClass to current item's one --%>
<dot:GridViewTextColumn ValueBinding="{value: Column2}" HeaderCssClass="{value: _this.HiddenColumnClass}" CssClass="{value: HiddenColumnClass }" />
```
I hope it helps you understand how the HeaderCssClass property actually works.

**Comment by Mitroz** [comment]
Thank you very much, it is clear for me now. Can you append it to documentation and examples? 
Maybe here are some other guys same like me :-]
