### ISSUE TITLE
Allow bind commands to property "on changed" event

### ISSUE THREAD

**Issue by jechtom** [riganti/dotvvm#25]
You should be able to execute command on property change.
This is useful for any kind of "selection/value changed" binding. For example cascade combo boxes.

**Comment by tomasherceg** [comment]
Yes, we should add this functionality to the built-in controls.

**Comment by exyi** [comment]
We should add this functionality as value changed event subscriber on knockout property.

**Comment by tomasherceg** [comment]
I am still wondering if this is really necessary. 
I think there are only several controls which really need this (TextBox, CheckBox, RadioButton and DropDownList) and they can implement this kind of behavior.
Maybe we can create some common interfaces and helper methods that control developers may use when implementing this stuff.

We can start by adding TextChanged, IsCheckedChanged and ValueChanged commands to the controls named above and we'll see.
