### ISSUE TITLE
Bootstrap Responsive Navigation Container Width

### ISSUE THREAD

**Issue by AlistairClark7** [riganti/dotvvm#252]
Is there a way to make the first div inside bs:ResponsiveNavigation have a container class instead of container-fluid? As with container-fluid the left and right nav menu items go all the way to the edges of the screen, which looks odd on desktop size resolutions.

```
<nav class="navbar navbar-default navbar-fixed-top" data-dotvvm-id="c24">
    <div class="container-fluid"><!--here I want container instead of container-fluid -->
    ...
    </div>
</nav>
```

**Comment by martinsura** [comment]
https://www.dotvvm.com/docs/controls/bootstrap/Container/latest

Componet bs:Container has type property Normal | Fluid.

**Comment by tomasherceg** [comment]
The problem is that the `ResponsiveNavigation` uses container internally and has the `container-fluid` CSS class hard-coded.

I have just added the `ContainerType` property to the `ResponsiveNavigation` and when we run all tests, we'll release the version `1.0.5.2`.

**Comment by tomasherceg** [comment]
The version `1.0.5.2` has just been published. Use `ContainerType="Normal"` on the `ResponsiveNavigation` control.
