### ISSUE TITLE
dot:Validation control not working in bootstrap accordion control

### ISSUE THREAD

**Issue by martinsura** [riganti/dotvvm#253]
Hi, dot:Validatio  control not working in bootstrap CollapsiblePanel (bs:CollapsiblePanel) control
```
   <bs:Accordion>
        <bs:CollapsiblePanel IsCollapsed="false">
          <HeaderTemplate>
          Info            
         </HeaderTemplate>
          <ContentTemplate>
           <dot:Validator Value ...>
         </ContentTemplate>
```
In normal page validation works fine

**Comment by martinsura** [comment]
Maybe https://github.com/riganti/dotvvm/issues/238 this is relevat issue. Same problem in bs:Panel component

**Comment by quigamdev** [comment]
It's fixed. 
Thanks for report.
