### ISSUE TITLE
Issue with DotVVM plugin in Visual Studio

### ISSUE THREAD

**Issue by dlicht** [riganti/dotvvm#258]
We are receiving this error each time we load a .dothtml page, this is a new error the last few days it was a different error, please advise if this is the correct location for this type of bug reports:

System.Exception: Dotvvm compiler failed: 
{"ClassName":"System.TypeInitializationException","Message":"The type initializer for 'DotVVM.Compiler.ViewStaticCompilerCompiler' threw an exception.","Data":null,"InnerException":{"ClassName":"System.IO.FileLoadException","Message":"Could not load file or assembly 'DotVVM.Framework, Version=1.0.0.7, Culture=neutral, PublicKeyToken=23f3607db32275da' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)","Data":null,"InnerException":{"ClassName":"System.IO.FileLoadException","Message":"Could not load file or assembly 'file:///C:\\svn_checkouts\\Xeddco\\InsuranceDrip\\AnnuityDrip\\AnnuityDrip.WebV2\\bin\\DotVVM.Framework.dll' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)","Data":null,"InnerException":{"ClassName":"System.NotSupportedException","Message":"An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.","Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":null,"RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":null,"HResult":-2146233067,"Source":null,"WatsonBuckets":null},"HelpURL":null,"StackTraceString":"   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)\r\n   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)\r\n   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)\r\n   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)\r\n   at System.Reflection.Assembly.LoadFrom(String assemblyFile)\r\n   at DotVVM.Compiler.Program.LoadFromAlternativeFolder(String name)\r\n   at DotVVM.Compiler.Program.CurrentDomain_AssemblyResolve(Object sender, ResolveEventArgs args)\r\n   at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":"8\n_nLoad\nmscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\nSystem.Reflection.RuntimeAssembly\nSystem.Reflection.RuntimeAssembly _nLoad(System.Reflection.AssemblyName, System.String, System.Security.Policy.Evidence, System.Reflection.RuntimeAssembly, System.Threading.StackCrawlMark ByRef, IntPtr, Boolean, Boolean, Boolean)","HResult":-2146233067,"Source":"mscorlib","WatsonBuckets":null,"FileLoad_FileName":"file:///C:\\svn_checkouts\\Xeddco\\InsuranceDrip\\AnnuityDrip\\AnnuityDrip.WebV2\\bin\\DotVVM.Framework.dll","FileLoad_FusionLog":""},"HelpURL":null,"StackTraceString":"   at DotVVM.Compiler.ViewStaticCompilerCompiler..cctor()","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":"1\n.cctor\nDotVVM.Compiler, Version=1.0.0.0, Culture=neutral, PublicKeyToken=23f3607db32275da\nDotVVM.Compiler.ViewStaticCompilerCompiler\nVoid .cctor()","HResult":-2146233067,"Source":"DotVVM.Compiler","WatsonBuckets":null,"FileLoad_FileName":"DotVVM.Framework, Version=1.0.0.7, Culture=neutral, PublicKeyToken=23f3607db32275da","FileLoad_FusionLog":""},"HelpURL":null,"StackTraceString":"   at DotVVM.Compiler.ViewStaticCompilerCompiler..ctor()\r\n   at DotVVM.Compiler.Program.DoCompile(String optionsJson)","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":"1\n.ctor\nDotVVM.Compiler, Version=1.0.0.0, Culture=neutral, PublicKeyToken=23f3607db32275da\nDotVVM.Compiler.ViewStaticCompilerCompiler\nVoid .ctor()","HResult":-2146233036,"Source":"DotVVM.Compiler","WatsonBuckets":null,"TypeName":"DotVVM.Compiler.ViewStaticCompilerCompiler"}

   at DotVVM.VS2015Extension.DotvvmCompilerManager.<ExecCompiler>d__13.MoveNext() in C:\TFSBuildAgent\_work\10\s\src\Dotvvm.VS2015Extension\DotVVM.VS2015Extension\CompilerManager.cs:line 155

**Comment by dlicht** [comment]
I should say this error message pops up under the Cloud Explorer in VisualStudio "DotVVM.Compiler.exe has thrown an exception: System.Exception"  Then when we click on "Show Details" the above message is what we get.

**Comment by tomasherceg** [comment]
Will be fixed in next release of the extension.

The DotVVM.Compiler is not an essencial component that would be really required, it only makes the IntelliSense in the VS extension better.
