### ISSUE TITLE
Command in MarkupControl

### ISSUE THREAD

**Issue by exyi** [riganti/dotvvm#260]
Currently command binding seems to work fine in markup control, but it starts doing mess when the control is used multiple times on the page. Specifically it invokes the first command found on page, which is pretty ugly behaviour as it is undebugable and pretends to work "correctly".

I think we should make `command` binding working in markup controls like the `controlCommand` works, so only difference between these two will be in the default binding context. Another option is to disable command binding in markup control (a breaking change, although breaking potentially broken code) or we keep this behaviour (maybe just throw some error when two matching command binding are found on one page).

What do you think? @tomasherceg?

**Comment by tomasherceg** [comment]
More and more I think about this, it seems that the `controlProperty` and `controlCommand` bindings are a mistake and we should only have `value` and `command` bindings. 
All of them should track not only the binding context on which they are invoked, but also the markup control that declares them (uniqueControlId or something like this), so we can track the correct binding object and execute it.

Or am I getting something wrong?

**Comment by tomasherceg** [comment]
More and more I think about this, it seems that the `controlProperty` and `controlCommand` bindings are a mistake and we should only have `value` and `command` bindings. 
All of them should track not only the binding context on which they are invoked, but also the markup control that declares them (uniqueControlId or something like this), so we can track the correct binding object and execute it.

Or am I getting something wrong?

**Comment by exyi** [comment]
@tomasherceg I agree. I'll try to code it.

**Comment by Mylan719** [comment]
Actually what was the difference between `command` and `propertyCommand`? I alwais struggle which one to use.

**Comment by exyi** [comment]
@Mylan719 The only difference was that control command rendered ID of parent control, so it could find the binding correctly.
