### ISSUE TITLE
PolicyView control

### ISSUE THREAD

**Issue by djanosik** [riganti/dotvvm#264]
[Policies](https://docs.asp.net/en/latest/security/authorization/policies.html) are a neat addition in ASP.NET Core. They provide an easy way to specify custom authorization requirements. We already support them in `Authorize` attribute. And I think we should add a control that will render different content when the requirements are met and when not.

```
<PolicyView Policies="One,OrOther" HideForAnonymousUsers>
    <RequirementsMetTemplate />
    <RequirementsNotMetTemplate />
</PolicyView>
```
Unfortunately, there is no alternative solution on OWIN. It will be available only on ASP.NET Core and we need to list similar differences in docs.

**Comment by adamjez** [comment]
Added in https://github.com/riganti/dotvvm-contrib/commit/d2101e68d1e92d8d5487f52fdcc6da77159b70e7
