### ISSUE TITLE
Rename RoleView.HideNonAuthenticatedUsers

### ISSUE THREAD

**Issue by djanosik** [riganti/dotvvm#265]
We need to rename the `RoleView.HideNonAuthenticatedUsers` property to something meaningful (eg. `HideForAnonymousUsers` used in `ClaimView`). But first we need a way to make API changes in minor versions without introducing breaking changes.

- Keep both properties.
- Mark the old one with `Obsolete` attribute and show warning in VS extension.
- Mark the old one with `EditorBrowsable` (or other custom) attribute and hide it from intellisense.
- Remove the old one in next major version.

**Comment by tomasherceg** [comment]
Because these controls are relatively new and not many people use them, I'd rename it and mention it in the Breaking changes section on DotVVM blog.
