### ISSUE TITLE
Dependency Injection in controls

### ISSUE THREAD

**Issue by djanosik** [riganti/dotvvm#266]
When a control depends on a service it needs to grab it from service locator. It's a bit ugly :)
```
protected internal override void OnInit(IDotvvmRequestContext context)
{
    var provider = context.Configuration.ServiceLocator.GetService<IEnvironmentNameProvider>();
}
```
I think we should enable dependency injection in controls. Is it possible?

**Comment by exyi** [comment]
I hope it is possible, but not very simple if we want to maintain decent performance of control tree initialization.

**Comment by tomasherceg** [comment]
We should mark controls with dependencies with some attribute (e.g. `RequireDependencyInjection`) to be able to recognize them during the view compilation. 

If the class of the control has this attribute, we'll use some component (e.g. `IControlDependencyInjectionContainer`) to resolve the actual control instance. The behavior for all other control classes will remain the same.

**Comment by exyi** [comment]
Just don't forget to handle Transient and Scoped services correctly, #309

**Comment by exyi** [comment]
Resolved.

It works in two modes:
* Simple/intuitive/automatic/hipster mode - when the control does not have a parameterless constructor, it is initialized from the default `IServiceProvider`. It is used mainly for infrastructure controls that need to get some dotvvm service, for non-control DotvvmBindableObjects that need
