### ISSUE TITLE
Using DotVVM with .NET Core

### ISSUE THREAD

**Issue by rudimk** [riganti/dotvvm#268]
I went through the documentation, and it says [here](https://www.dotvvm.com/docs/tutorials/how-to-start-dnx/latest) that support for .NET Core won't be rolled out until you hit 1.0. At the same time, #87 is marked closed, but I can't make out if I can actually use .NET Core to build a DotVVM app.

If .NET Core support is done, could you give me some pointers on getting started? I'd be happy to use that and contribute docs.

PS - I'm a Python, Julia and Go guy who's playing with .NET again after leaving it be for years, so I'm bound to miss something!

**Comment by exyi** [comment]
The documentation page is a bit outdated, .NET Core support is now in beta, you can download [NuGet v1.1-beta](https://www.nuget.org/packages/DotVVM/1.1.0-beta). Check out our [blog post about .NET Core support](https://www.dotvvm.com/blog/13/DotVVM-1-1-Alpha-with-NET-Core-Support) and [1.1.0 release notes](https://github.com/riganti/dotvvm/releases).

**Comment by rudimk** [comment]
Thanks a bunch!
