### ISSUE TITLE
ExceptionFilter calls OnPageException even when OnCommandException is called

### ISSUE THREAD

**Issue by tomasherceg** [riganti/dotvvm#288]
When the exception occurs during command execution, the `OnCommandException` method on the exception filters should be called.
The `OnPageException` should be called in all other cases.

**Comment by exyi** [comment]
The `OnPageException` is called if the exception is not handled by `OnCommandException`. If you'd set `ExceptionHandled = true` the OnPageException hander would not be called.

**Comment by exyi** [comment]
The behaviour is correct IMHO

**Comment by tomasherceg** [comment]
OK, that's right. 
However, I have found one interesting behavior which I don't know is right or not.
When I apply the filter on the whole viewmodel, it works as expected:

    [MyExceptionFilter]
    public class MyViewModel {
         public void TestCommand() {
               throw new Exception();    // this calls OnCommandExceptionAsync and if it doesn't handle the error, it calls the OnPageExceptionAsync
         }
    }

But when I apply the filter only on the command, the `OnPageException` is not fired.

    public class MyViewModel {

         [MyExceptionFilter]
         public void TestCommand() {
               throw new Exception();    // this calls OnCommandExceptionAsync and if it doesn't handle the error, it calls the OnPageExceptionAsync
         }
    }

You can reproduce it in the `DotVVM.Samples.Common.ViewModels.FeatureSamples.ActionFilterErrorHandling.ActionFilterRedirectViewModel` class by moving the attribute and commenting out the `OnCommandExceptionAsync` method in the filter class in the same file.

I don't know if it is right behavior or not. What do you think?

**Comment by exyi** [comment]
This is correct behavior, only method from `ICommandActionFilter` are called when the filter is applied on command. It can't be easily changed, because command (and it's filters) are found after page filters have been invoked.

**Comment by tomasherceg** [comment]
OK, thanks, sounds legit.
