### ISSUE TITLE
Calling command in data context of dotcontrol set by value binding with _control variable does not work.

### ISSUE THREAD

**Issue by quigamdev** [riganti/dotvvm#290]
When I  have this code: 

```
<div DataContext="{value: _control.Model}">
<dot:button Text="This does not work" Click="{command: ActionInModel()}" />
</div>

```

I fixed it by this change: 
```
<div DataContext="{controlProperty: Model}">
<dot:button Text="This does not work" Click="{command: ActionInModel()}" />
</div>
```

The model is dotvvm property in dotcontrol. It's set for view like: 
`<cc:MyControl Model="{value: ModelData}" />`

The only difference is that I used `controlProperty` instead of `value: _control`. 
Please add test for this.

**Comment by exyi** [comment]
This seems to be fixed, see `FeatureSamples/MarkupControl/CommandBindingInDataContextWithControlProperty`. If it still does not work for you, could you please provide a repro sample?
