### ISSUE TITLE
Review and fix @wrapperTag and @noWrapperTag directives

### ISSUE THREAD

**Issue by tomasherceg** [riganti/dotvvm#292]
- [x]  They don't seem to be working.
- [x]  Create sample and tests for this feature.
- [ ]  The `@wrapperTag` and `@noWrapperTag` should not be combined.
- [x]  We need to support this in the VS Extension.
- [ ]  Documentation.

**Comment by exyi** [comment]
I have just written unit tests for them and it seems to work well, see d947ce53bc7929e6ecc856cb0a606c3084a261d1. The `@noWrapperTag is also used in ArticleDetail.dotcontrol and it also works.

**Comment by djanosik** [comment]
@Leeemons Will you also update docs?

**Comment by Leeemons** [comment]
@djanosik No, I didnt update docs
