### ISSUE TITLE
Refactor binding translation and runtime API.

### ISSUE THREAD

**Issue by exyi** [riganti/dotvvm#297]
Value bindings are currently translated to Javascript by a simple class called JavascriptTranslator which produces a string that can be executed inside knockout `data-bind` attribute. Similarly command bindings are translated to a Javascript expression that can be executed inside `on...` attribute. Although you can register custom translator for methods, you can't (easily) change context where the binding can be executed nor modify how specific binding will be translated.

We need more fine-grained pipeline that will produce the final expression and be more extensible.
* Rewrite the `System.Linq.Expression` from which JS will be produced, may be useful for adding support for higher level features to the translator.
* Register method translator (already supported) - a interface that translates a method invocation to Javascript expression.
* Rewrite Javascript AST - may be useful to unwrap some observable, optimize code or insert null checks (probably mostly internal usage)
* Replace parameter with custom variables - the output of translation will contain SymbolParameter nodes, that will have to replaced later - when executing inside knockout binding `KnockoutContextParameter` will become `$context` parameter, or `$parentContext` cascade if the binding was transfered to child control. Another typical is `CurrentElementParameter` that will be replaced with `this` in event attribute, `$element` in knockout event handler or whatever your variable is named when you need to invoke it manually.

Another problem is that BindingExpression contains only few properties and you can't easily extend it with another property that will came from compilation. We probably need to have a `Dictionary` inside each binding for all properties that may be needed. There will also be a service for each property, that will be able to compute the value from other properties. It could look like:
* Expression <- Parser(OriginalString)
* ResultType <- Expression.Type
* GetValueDelegate <- CompileGetDelegate(Expression)
* JavascriptValueExpression <- TranslateToJs(Expression)
* JavascriptCommandExpression <- GetCommandScript(BindingId, Expression)
* JavascriptCommandExpression <- GetStaticCommandScript(Expression)

Bindings will have requirements and services registered using a Attribute on the class and will contain some helper methods, like GetValue(DotvvmControl), GetKnockoutBinding(), ...
It would also be useful to specify additional requirements and transformation services for a property, so you will be able to run your transformation during compilation.

I have already started with implementation of the Javascript AST and forgot to put this issue on github earlier, sorry for that.

**Comment by exyi** [comment]
It's basically done, including basic docs and tests

**Comment by tomasherceg** [comment]
Where is the docs? I think we should dedicate a page in the Control Development section for the binding system.

**Comment by exyi** [comment]
Docs is waiting for review https://github.com/riganti/dotvvm-docs/pull/46
