### ISSUE TITLE
Split IGridViewDataSet in multiple interfaces

### ISSUE THREAD

**Issue by tomasherceg** [riganti/dotvvm#298]
+ `IDataSet`
+ `IPageableDataSet`
+ `ISortableDataSet`
+ `IFilterableDataSet`

**Comment by djanosik** [comment]
I think the names of interfaces should not contain the word "GridView", because we will also use it in other controls.

**Comment by tomasherceg** [comment]
Agree, but: 

1) Since the `GridViewDataSet` was present in 1.0 and it is used on many pages in almost every app, it would be a big breaking change. 
2) The `DataSet` class is already taken and it would lead to a bigger confusion. 

Maybe we could create the `DotvvmDataSet` and use type redirection, but I don't know what limitations or issues it would bring. We should do a research of this.

**Comment by djanosik** [comment]
I don't think we need one common DataSet implementation, but we need some common interfaces. We can surely keep `GridViewDataSet` and `IGridViewDataSet`. However, I think we shouldn't release this change until we know what we need from DataSets in BusinessPack.

**Comment by tomasherceg** [comment]
Ygree, we should wait with further changes until we have e.g. grouping support in Business Pack GridView.
