### ISSUE TITLE
Literal and GridViewTextColumn - add MaxLength and EllipsisText properties

### ISSUE THREAD

**Issue by tomasherceg** [riganti/dotvvm#304]
The `MaxLength` will allow to specify that only first X characters will be displayed.
If set to 0 (the default value), the whole text is displayed.

The `EllipsisText` will have the default value of `...` and will be displayed when the text was longer than the `MaxLength` property.

**Comment by tomasherceg** [comment]
1. There is nothing that prevents you to use the CSS solution.

2. If you use server rendering and `[Bind(Direction.None)]` on the property in the viewmodel, you'll save some bytes because only the rendered part is transferred.

3. The `text-overflow` doesn't work well in table cells if you don't add 5 additional CSS properties including the `max-width` on the column. If it is only about setting `text-overflow`, I wouldn't bother, but it's way more things you need to do: http://stackoverflow.com/questions/9789723/css-text-overflow-in-a-table-cell

In many cases, setting the limit to e.g. 50 characters is a good-enough way to solve the problem.

**Comment by exyi** [comment]
@tomasherceg 
1. Of course, but it is not a good idea to introduce bad practice and learn people to use it.
2. Unfortunately this can't save you more than half the amount of data, as it will be replicated in the ViewModel, it will only give a false feeling of saving data.
3. But this proposal also would not work well. And anyway it is easier to find generic-html answer on SO than to find DotVVM only solution.
