### ISSUE TITLE
F7 in .dotcontrol file should switch to c# code

### ISSUE THREAD

**Issue by ridercz** [riganti/dotvvm#307]
Pressing F7 in .dotcontrol file should open the backend c# code (if exists), like it does for .dothtml.

**Comment by Mylan719** [comment]
There is a question weather it should .control's viewmodel, which would be consistent with .dothtml behavior, or maybe it makes more sense to switch to controls code behind.

**Comment by tomasherceg** [comment]
Since the viewmodel of a user control will is likely to be an interface, it would be better to open the code behind instead (if present).

**Comment by quigamdev** [comment]
This feature is implemented. Closing this issue.
