### ISSUE TITLE
IntelliSense offers wrong attribute

### ISSUE THREAD

**Issue by ridercz** [riganti/dotvvm#308]
When entering the DataContext property by typing "DC", the extension offers Validator.InvalidCssClass by default.
![intellisense](https://cloud.githubusercontent.com/assets/5148075/22175216/0f299668-dff1-11e6-8162-3ffe3278a798.png)

**Comment by exyi** [comment]
I have just changed the implementation to use the same logic as C# completion uses. Only waiting for release of VS Extension. I just hope they won't change the Roslyn internal classes I use for it...
