### ISSUE TITLE
Scoped service in ASP.NET Core behaves like Singleton

### ISSUE THREAD

**Issue by hajekj** [riganti/dotvvm#309]
When using default DI container provided in ASP.NET Core with Scoped service, it seems to behave like a singleton instead of being Scoped to the request.

**Comment by exyi** [comment]
Probably fixed in ffb0b21a0e3c0bd10738ae5eeca009039b014869. However I have tested it only for ViewModel injection, will it cover your use case?

Sorry that it took me a bit longer to resolve, I couldn't figure out how the DI of scoped stuff actually work :).
