### ISSUE TITLE
CheckBox - CheckedItems does not clear after updating backing list, the checkboxes do.

### ISSUE THREAD

**Issue by kiraacorsac** [riganti/dotvvm#310]
I have the following View and ViewModel
```
<body>
    <p>
        Create a guest:
        <dot:TextBox Text="{value: NewGuestDrawer}" />
        <dot:Button Text="Add" Click="{command: AddNewGuestDrawer()}" />
    </p>

    <dot:Repeater DataSource="{value: Drawers }" WrapperTagName="ul">
        <ItemTemplate>
            <li>
                <dot:CheckBox Text="{value: Name}" CheckedItems="{value: _parent.PickedDrawers}" CheckedValue="{value: _this}" />
            </li>
        </ItemTemplate>
    </dot:Repeater>

        <dot:Repeater DataSource="{value: PickedDrawers }" WrapperTagName="ul">
            <ItemTemplate>
                <li>
                    {{value: _this.Name}}
                </li>
            </ItemTemplate>
        </dot:Repeater>
</body>
```

```
        public IList<Drawer> Drawers { get; set; }
        public string NewGuestDrawer { get; set; } 
        public IList<Drawer> PickedDrawers { get; set; }

        public SetupViewModel()
        {
            Drawers = new List<Drawer>();
            PickedDrawers = new List<Drawer>();
        }

        public void AddNewGuestDrawer()
        {
            Drawers.Add(new Drawer(NewGuestDrawer, new List<string>(), true));
        }        
```

I can "desychnronize" PickedDrawers and checkboxes selected when I

1. Create multiple drawers
2. Check one or more drawers
3. Create additional drawer

The PickedDrawers list will contain the drawers checked in step 1., however the checkboxes will be all unchecked, leaving them available to be checked again and creating duplicite instances of the Drawers in PickedDrawers. 

The behavior is correct (the checkboxes stays checked and the list stays filled) if I use primitive type (such as string) in place of Drawer. I would expect one of the following:

1. A mention in the docs about the primitive types and throwing an exception/warning on misuse 
2. Same behavior as when using list of strings

**Comment by tomasherceg** [comment]
This is similar to #156, we should find some unified way to compare objects.
