### ISSUE TITLE
CheckBox - CheckedValue type can differ from CheckedItems list type producing odd results

### ISSUE THREAD

**Issue by kiraacorsac** [riganti/dotvvm#311]
Given `Strings` is a list of `string`  and `Number` an `int`, I can have
```
<dot:CheckBox Text="{value: Name}" CheckedItems="{value: Strings}" CheckedValue="{value: Number}" />
```
creating nonsensical results in less trivial examples.

I would expect an exception.

**Comment by exyi** [comment]
There is a control usage validator that should now throw a compile error: https://github.com/riganti/dotvvm/blob/master/src/DotVVM.Framework/Controls/CheckBox.cs#L119
