### ISSUE TITLE
Error page links to missing pages on Github.

### ISSUE THREAD

**Issue by kiraacorsac** [riganti/dotvvm#313]
Handy buttons that should point from error page to page with code that caused the error on Github are not working. They they point to

`https://github.com/riganti/dotvvm/blob/master/src//*`

and should point to

`https://github.com/riganti/dotvvm/blob/master/src/DotVVM.Framework/*`

**Comment by exyi** [comment]
Fixed for now, but it would be cool to have online source code browser like Roslyn and .NET has - https://github.com/KirillOsenkov/SourceBrowser
