### ISSUE TITLE
DotVVM serializer should ignore property names defined by attributes

### ISSUE THREAD

**Issue by TomProkop** [riganti/dotvvm#314]
![image](https://cloud.githubusercontent.com/assets/4339668/22296399/5112508e-e31a-11e6-85fd-426a02235deb.png)

When I use a third party object in a ViewModel current behavior can be misleading.

**Comment by exyi** [comment]
On the other hand, it can be IMHO useful to rename property for client, but maybe we can ignore standard Newtonsoft.Json attribute and use only dotvvm specific one. Another problem is, that v1.1 Javascript translator does not care about it, so it does not actually work.

**Comment by tomasherceg** [comment]
We cannot use the `Newtonsoft.Json` attributes, but we should probably introduce a custom attribute for this as this concerns the binding expression translation mechanism.

Maybe `[Bind(Name = "something")]`

**Comment by exyi** [comment]
Resolved by c106f266a0acffb2e1276a426c8cc4c56f028505
