### ISSUE TITLE
Extension parameters for bindings

### ISSUE THREAD

**Issue by exyi** [riganti/dotvvm#316]
We need a way to pass additional parameters to bindings like current item index inside `Repeater` template (see #205), `_api` for API access (#282) and `_control` could use this mechanism too. This was also proposed in discussion under #195.
The parameters should be compile-time only, they will be translated to some operation on `DotvvmControl` server-side (like look for `DotvvmMarkupControl` or `DataItemContainer` in ancestors) and to operation on knockout binding context client-side (like `$context.$index`, `$context.$control` or an symbolic parameter).
The parameters should be inherited across DataContext boundary, but can be overwritten or the inheritance can be disabled.

There is an question how to access the overwritten parent parameter
* `_parent._index` - implementable, but unsystematic and I'm not sure about VS Extension (cc @Mylan719)
* `_parent_index` - I don't like it, there would be ton of them in completion.
* It does not have to be possible. 

Any other ideas or suggestions?

**Comment by tomasherceg** [comment]
TBD

- [ ] Create UI tests
- [ ] Documentation

There is a short description of features in the release notes and in the pull request description.

**Comment by exyi** [comment]
The docs exists: https://github.com/riganti/dotvvm-docs/blob/2.0/Pages/control-development-binding-extension-parameters.md. I guess we have also got some UI test, so we can close this issue since everything is done.
