### ISSUE TITLE
dot:Repeater always renders wrapper tag for empty data template

### ISSUE THREAD

**Issue by ridercz** [riganti/dotvvm#320]
The Repeater control generates `div` wrapper tag around contents of `EmptyDataTemplate` even when `RenderWrapperTag="false"`. I would expect that under these circumstances it would not render any extra tags.

**Comment by djanosik** [comment]
@exyi I is actually necessary to always render `WrapperTag` around `EmptyDataTemplate`; at least in client rendering mode. The `visible` binding cannot be used with KO comments.

**Comment by exyi** [comment]
This is pretty unfortunate, do you have any idea what to do with that? Maybe we could add support for it to knockout, but it's quite likely that they have some reason for it. Or I will have to revert the commit and leave this as wont-fix :(

**Comment by exyi** [comment]
Using `if` instead of `visible` did the trick, and it probably makes more sense. Thanks @djanosik
