### ISSUE TITLE
AddCodeControl(prefix, exampleControl) is semantically wrong. 

### ISSUE THREAD

**Issue by quigamdev** [riganti/dotvvm#323]
The name of the method should be `AddCodeControls(prefix, exampleControl)` or the method should just register only the control specified as the parameter.

**Comment by exyi** [comment]
I think we should also rename the `AddCodeControl(string tagPrefix, string namespaceName, string assembly)` overload as it also adds entire namespace of controls.

**Comment by quigamdev** [comment]
I agree.

**Comment by exyi** [comment]
resolved 1624ea0f42221c1003cba3d3949a5a033254601b
