### ISSUE TITLE
Add some option to register required resource for custom PostBackHandler

### ISSUE THREAD

**Issue by quigamdev** [riganti/dotvvm#324]
Currently there is no way to register required resource in PostBackHander. The script has to be added to page manually.

**Comment by exyi** [comment]
I'm not sure now how to do that, maybe we could a PreRender method, like controls have.
Btw similar problems have the `ActiveDotvvmProperty`, should we also add the PreRender?

**Comment by tomasherceg** [comment]
Maybe we can add a method called `OnAttached` and pass the control and request context in this method. I don't think invoking the whole lifecycle is necessary.

**Comment by exyi** [comment]
Maybe if we could do constructor injection of `IDotvvmRequestContext`, it could solve the issue too. And it will solve all similar issues with DotvvmBindableObjects in properties other than content.

**Comment by tomasherceg** [comment]
We can do this using the constructor injection (create a test for that) and describe this option in the documentation.
