### ISSUE TITLE
Unable to de-serialize an object tuple.

### ISSUE THREAD

**Issue by Compactis** [riganti/dotvvm#326]
Unable to de-serialize an object tuple.

**Comment by Arcidev** [comment]
Tuple does not have a default constructor which is the problem why you cannot deserialize it on postback. Also Tuple property values cannot be set after creation. In case I need to use any Pair like class I always create my own version of Tuple/Pair class which provides default consutor and allows to set properties at any time.

If you need only send those values to client you can use BindDirection.ClientToServer, but I recommend to actually create a little more flexible class than Tuple.

**Comment by exyi** [comment]
I think we should add support for tuples and other classes without default constructor.

**Comment by tomasherceg** [comment]
We should do this together with the decomposition. #280
