### ISSUE TITLE
SpaContentContentPlaceholder not working with GridView ?

### ISSUE THREAD

**Issue by jasin755** [riganti/dotvvm#329]
When I use GridView with SpaContentPlaceholder I got this error:
![spacontainer](https://cloud.githubusercontent.com/assets/10629189/23485866/b41cae16-fedd-11e6-83a8-cc2aa81c028a.PNG)

Visual Studio - 2017 RC
DotVVM.AspNetCore - 1.1.0-rc5

**Comment by exyi** [comment]
It seems that resource `globalize` was not loaded, could you please try to add `<dot:RequiredResource Name='globalize' />` to the (master)page? Anyway it should load it automatically, does it say anything about it in the console? Could you please provide a bit more information about it, I'm not sure if I can find out why it happens.

**Comment by jasin755** [comment]
`<dot:RequiredResource Name='globalize' /> ` not helped. Here is complete project for testing: `https://github.com/jasin755/dotvvmbug`

**Comment by tomasherceg** [comment]
I have found the issue. It will be fixed in few days.

Also, I have looked in your project and I have found the following code:

            return _dbContext
                .Invoices
                .Include(nameof(Data.Entities.Invoice.Carrier))
                .Include(nameof(Data.Entities.Invoice.InvoiceStatus))
                .Include(nameof(Data.Entities.Invoice.User))
                .Select(i => _mapper.Map<Invoice>(i));

It is not very efficient, because it might load unnecessary data. This should be better:

            return _dbContext.Invoices.ProjectTo<Invoice>();

**Comment by jasin755** [comment]
@tomasherceg thnx for fix issue and your advice :)
