### ISSUE TITLE
Bootstrap ResponsiveNavigation should allow to set HeaderLinkRouteName, not just URL

### ISSUE THREAD

**Issue by tomasherceg** [riganti/dotvvm#349]

**Comment by exyi** [comment]
What about more generic solution, adding three properties and an condition to every control that renders url sounds stupid. We already have url transformation for virtual directories and I wanted to have another for resources (#293). Something like `route://MyRouteName?Id=5` solve the problem in much eleganter way. Also value bindings for part of the value could also be useful for parameters - `route://MyRouteName?Id={{value: Id}}`.

**Comment by tomasherceg** [comment]
The route URL syntax is not very nice (long string, what about conditional parameters etc.). We should think about a better solution and maybe do a research how many of such properties we have in the framework and controls - I don't think there are so many of them.

**Comment by exyi** [comment]
I think it can be quite common scenario for user control - custom banner linking somewhere... Anyway I don't like that controls would have two properties and a property group that do the same thing.
