### ISSUE TITLE
Validation messages should not be logged on the console when Debug=false

### ISSUE THREAD

**Issue by tomasherceg** [riganti/dotvvm#350]

**Comment by exyi** [comment]
I don't agree, console is always for debug, I don't think users could be somehow frightened by it and it also does not create that much noise.

**Comment by quigamdev** [comment]
At least, there should be some option how to disable this behavior. Customers should not report these kind of "errors", but they do.

**Comment by exyi** [comment]
End users are looking to the developer console? Are we talking about the same thing? I mean the tab in (F12) dev tools - this intended for developers and in my opinion it can be quite useful for them. Mistakes connected with incidentally turned on validation on some field are quite common and already hard to find.

**Comment by quigamdev** [comment]
Yes, I'm talking about F12 developer console. This really happened. Customer told us  that we have some errors in  developer console and that we should fix it. They do not understand why it is important for us. That is reason why I think that DotVVM should have some switch that would be able to disable console output. 
But by default, DotVVM should write the output to the console as it is right now.

**Comment by tomasherceg** [comment]
In Debug mode, we can report this as error.
In Production mode, we should write this at the console as a log message, not as an error. It is not only about the end users. If you are in IE and display the status bar, you will see that there are some script errors. Also, search engines might penalize the website for an error. 

Validation is a situation that happens and that is not "error" in fact - it is a normal and expected behavior of the application. I think that the log level should be info and not error.
