### ISSUE TITLE
Wrong documenation for AzureAD authorization

### ISSUE THREAD

**Issue by PavelBansky** [riganti/dotvvm#352]
Manual page: https://www.dotvvm.com/docs/tutorials/advanced-owin-security/latest
specifies this authority to be used for AzureAD

```
var authority = new Uri("https://login.microsoftonline.com/common/");
```

This doesn't work and the code ends up in `AuthenticationFailed` section and `context` have following exception inside:

```
Exception = {"IDX10205: Issuer validation failed. Issuer: 'https://sts.windows.net/72f988bf-86f1-41af-91ab-2d7cd011db47/'. Did not match: validationParameters.ValidIssuer: 'null' or validationParameters.ValidIssuers: 'https://sts.windows.net/{tenantid}/'."}
```
Correct authority supposed to be

```
var authority = new Uri("https://login.microsoftonline.com/contoso.com/");
```

Where contoso.com is the name of the companyAD (tenant id)

**Comment by tomasherceg** [comment]
Thanks for the report! The `"common"` instead of tenant is used for multi-tenant apps (which we haven't mentioned in the docs) and you have to also include the `TokenValidationParameters = new TokenValidationParameters() { ValidateIssuer = false }`.
