### ISSUE TITLE
Update only properties specified in viewModelDiff after postback

### ISSUE THREAD

**Issue by djanosik** [riganti/dotvvm#354]
Currently, we update all properties on ViewModel after postback, not just properties that were actually changed during postback. It causes quite odd behavior. Consider the following example.

1. We have one object (**ourInstance**) in JavaScript.
2. The instance is set as value of multiple ViewModel properties (observables).
```js
{
    SelectedValue: ko.observable(ourInstance),
    Values: ko.observableArray([
         ko.observable(ourInstance)
    ])
}
```
3. Now we change `SelectedValue.Property` during postback.
4. DotVVM will deserialize the **updated ViewModel**:
    1. It will call `SelectedValue().Property(newPropertyValue)` to update the property on `ourInstance`. Because the same instance is used in `Values` it will also update the first item in the collection.
    2. The deserializer will look whether the `Values` property somehow differs from the one on the **updated ViewModel**. And it will call `Values()[0]().Property(oldPropertyValue)` to update the property to previous value.

As a result the change made to `SelectedValue` is practically ignored. It also depends on alphabetical order of ViewModel properties. But I think deserializer should not touch properties not changed in `viewModelDiff` after postback.

But maybe this is not worth fixing, because we may still run into situation when we change SelectedValue and Values in one postback and both will be in `viewModelDiff`.

**Comment by exyi** [comment]
I hope we can change it quite easily, but it is still quite unfortunate
behavior, IMHO it should not modify the second object instance in the
same time. Maybe we could prevent somehow object from being used on
multiple locations in the same time, or clone object on deserialize
(like it was immutable). Cloning object would probably have negative
impact on knockout performance as it's not prepared for that and would
refresh the entire DOM tree on every postback.

Although immutability would be nice, I'd leave that as possibility for
knockout-less DotVVM 2.0 and implement VM patching you suggested.

**Comment by tomasherceg** [comment]
How do we deal with this in Business Pack? Do the control clone the object from the collection before assigning it in SelectedValue? Because if I understand this correctly, that's the only way how to avoid the issue - not having a particular instance in the viewmodel multiple times.

**Comment by exyi** [comment]
@tomasherceg Yes, if I remember correctly what @djanosik has told, it is necesary to clone it every time. Having same instance multiple times in the viewmodel is a instant kill powder for the entire page...

**Comment by tomasherceg** [comment]
Yes, I believe too that @djanosik has made all Business Pack control to clone the items. 
We should investigate if `ComboBox` does this too - I am afraid that it doesn't and that we'll have to fix it in Knockout.

**Comment by exyi** [comment]
> We should investigate if ComboBox does this too - I am afraid that it doesn't and that we'll have to fix it in Knockout.

ComboBox from dotvvm framework does not do that (because Knockout does not do that) and I think it's correct, non-primite value are simply not supported. You would also have to define how equality should work on these types (by reference does not work, when you clone the values..., structural equality also does not work when you don't send all properties to client). It could also lead to strange behavior when you'd update the item in DataSource but not the one in the SelectedValue.

**Comment by tomasherceg** [comment]
Ah, we don't have `ItemKeyBinding` like in Business Pack - it would deal with the equality. However modifying the behavior of Knockout JS would not be so easy - the options and value bindings are quite complicated.

**Comment by exyi** [comment]
> Ah, we don't have ItemKeyBinding like in Business Pack - it would deal with the equality

It would kind of solve that, but it's much better when it's unsupported than when it can behave crazily. Because the serializer does not preserve references, changing something in the selected value or something in the collection will lead to basically invalid state of viewmodel. And when you have to choose a key of the SelectedValue, why wouldn't you choose to use the key as the SelectedValue?

**Comment by exyi** [comment]
Currently, the client-side (de)serializer updates works a little bit differently, but it should be equivalent in behavior. On the other hand, you really should not put multiple instances of the same object into the view model, as it will break anyway (when you change something or when go back to that page) and it is basically impossible to "solve".
