### ISSUE TITLE
Multiple models in one view

### ISSUE THREAD

**Issue by PavelBansky** [riganti/dotvvm#359]
I'm trying to create wizard like page [(similar to this)](https://www.panopta.com/2013/02/06/bootstrap-application-wizard-2/), and I was hoping to have multiple models on one page (switching the visibility of divs)

Problem is that command button for the first (visible) form (model) will execute validation for all of the forms (models) on the page. Is there a way to validate on specific form (model)?

I can use static commands or brake it into individual Views, but I was hoping for something more elegant...

**Comment by exyi** [comment]
You can use `Validation.Target="{value: FirstTab}"` property on the button or any ancestor element (the wrapper `div`) to restrict the validation only to this view model.
