### ISSUE TITLE
Cycle detected:    dotvvm (>= 1.0.0) -> DotVVM.AspNetCore (>= 1.1.0.1) -> DotVVM (>= 1.1.0.1).				

### ISSUE THREAD

**Issue by larcai** [riganti/dotvvm#361]
I installed the VS2017 template, created a new DotVVM Web App (.Net Core) project  and got the following messages

Cycle detected: dotvvm (>= 1.0.0) -> DotVVM.AspNetCore (>= 1.1.0.1) -> DotVVM (>= 1.1.0.1)
Unexpected dependency 'DotVVM' with no version number.

**Comment by tomasherceg** [comment]
It seems like the `DotVVM` package in in an older version than `DotVVM.AspNetCore`.

Can you please try to upgrade all packages `DotVVM.*` to the latest stable version (`1.1.1`)?
