### ISSUE TITLE
Update DOTVVM to 1.1.1. makes modal windows not working

### ISSUE THREAD

**Issue by readcom** [riganti/dotvvm#364]
Hi, after update DOTVVM to 1.1.1. my modal windows stop working.

I using this to open modal window:
Context.ResourceManager.AddStartupScript("$('div[data-id=confirm]').modal({backdrop: 'static'});");

Window load for very long time and end with this message:

![obrazek](https://user-images.githubusercontent.com/20860792/26878169-ca2d8b5c-4b8c-11e7-9063-997b698c15c0.png)

**Comment by tomasherceg** [comment]
If you run the script from the dev tools in the browser, is it working? 
Which library you use for modal dialogs? Bootstrap?

**Comment by readcom** [comment]
yes, bootstrap:

<div class="modal fade" ID="confirm" role="dialog" data-id="confirm" Validation.Enabled="false" Validator.InvalidCssClass="has-error" Validator.SetToolTipText="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Potvrzení</h4>
                </div>
...
-----------
I don't know how run this script in the browser, "open in debugger" makes browser freeze (firefox)
Chrome browser modal window does not open at all.

Return to previous working backup and new update to 1.1.1 is same result.

**Comment by tomasherceg** [comment]
We'll try to reproduce the issue. It looks like a problem with the `AddStartupScript` behavior.

**Comment by ENgateman** [comment]
Hello @readcom,
so far we've been unable to reproduce the issue. Could you please send us the call stack from the Developer Tools?

**Comment by readcom** [comment]
I don`t know if this help, if you need more info, just let me know:

`trigger (jquery-3.1.1.min.js:4)
(anonymous) (jquery-3.1.1.min.js:4)
each (jquery-3.1.1.min.js:2)
each (jquery-3.1.1.min.js:2)
trigger (jquery-3.1.1.min.js:4)
Ra (knockout:19)
I (knockout:41)
(anonymous) (knockout:107)
yd (knockout:9)
(anonymous) (dotvvm--internal:1325)`

**Comment by tomasherceg** [comment]
What is inside the modal dialog? Can you try to comment out the content and see whether the issues happens with an empty modal?

**Comment by readcom** [comment]
I have complete shrunk all project to find out where the problem is.
There are two exactly same ComboBoxes in modal window, after one combobox is deleted
everything is ok (in real project the ComboBoxes are different, but result is same).

If both comboboxes are active, AddStartupScript doesn`t work at all.
I have attached reduced project files (without Packages but compilable).

[Pozadavky.zip](https://github.com/riganti/dotvvm/files/1070878/Pozadavky.zip)

**Comment by tomasherceg** [comment]
Thank you, that's what I was afraid of. I'll fix it.

**Comment by tomasherceg** [comment]
We have just published DotVVM 1.1.2 which addresses this issue. 
If you run into any problems with freezin in combination with ComboBoxes, feel free to reopen this issue.
