### ISSUE TITLE
Bussiness Pack install, bp components are not in intelliSense

### ISSUE THREAD

**Issue by DannyRusnok** [riganti/dotvvm#365]
Hello,

after instalation BP into VS 2017 I cant use new components with syntex <bp:*.

I have latest VS 2017:
![image](https://user-images.githubusercontent.com/7890176/26916610-508e615a-4c2b-11e7-8a25-44cc50b794c9.png)

Signed in DotVVM in VS:
![image](https://user-images.githubusercontent.com/7890176/26916638-69cecb28-4c2b-11e7-8c81-86894dbfcfd7.png)

Rregistered BP in DotVMMStartup.cs:
![image](https://user-images.githubusercontent.com/7890176/26916664-7e22f482-4c2b-11e7-9298-387d3fe06aac.png)

And tried to delete cached component folder many times with restart VS and rebuild solution. But still cant use a bp components.
![image](https://user-images.githubusercontent.com/7890176/26916738-ccb3d972-4c2b-11e7-810c-a891e202d714.png).

Thank you for any advice.

Daniel

**Comment by PadreSVK** [comment]
Hi, it should be enough to add add businesspack configuration into ConfigureControls.

` private void ConfigureControls(DotvvmConfiguration config)
        {
            config.AddBusinessPackConfiguration();
        }
`

**Comment by DannyRusnok** [comment]
Thank you for advice. Now its working. But pls than fix documentation:
https://www.dotvvm.com/docs/tutorials/commercial-business-pack-install/latest

**Comment by tomasherceg** [comment]
Sorry about the issues. Sometimes (especially on .NET Core) it is not enough to rebuild the solution, you need to run the application which will refresh the VS IntelliSense to reflect the changes to the DotvvmStartup file.

Whether the `config.AddBusinessPackConfiguration` is run in the `Configure` or in the `ConfigureControls` method should not make a difference.

**Comment by PolywickStudio** [comment]
| System.NullReferenceException: Object reference not set to an instance of an object.   at DotVVM.Integration.VisualStudio.MarkupAnalysis.Intellisense.Completion.HtmlCompletionLogic.GetElementNames(DothtmlEditorContext context)   at DotVVM.Integration.VisualStudio.EditorIntellisense.HtmlCompletionProviders.TagNameCompletion.AddAndFilterDothtmlCompletions(IList`1 completions, HtmlCompletionContext context) in C:\dev\vs-extension\src\Extension\DotVVM.Integration.VisualStudio.VSShared\EditorIntellisense\HtmlCompletionProviders\TagNameCompletion.cs:line 72   at DotVVM.Integration.VisualStudio.EditorIntellisense.HtmlCompletionProviders.TagNameCompletion.FilterCompletionList(IList`1 completions, HtmlCompletionContext context) in C:\dev\vs-extension\src\Extension\DotVVM.Integration.VisualStudio.VSShared\EditorIntellisense\HtmlCompletionProviders\TagNameCompletion.cs:line 44   at Microsoft.Html.Editor.Completion.HtmlCompletionSource.<>c__DisplayClass12_2.<PopulateCompletionList>b__2()   at Microsoft.Web.Editor.Utility.GuardedOperations.InvokeExtensionPoint(Object errorSource, Action action) --- End of stack trace from previous location where exception was thrown ---    at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
-- | --

**Comment by PolywickStudio** [comment]
![snap_2018 01 27_02h09m38s_001_](https://user-images.githubusercontent.com/8903532/35454031-5356de4c-0307-11e8-9e4e-62eeca99c756.png)

**Comment by PolywickStudio** [comment]
Doesn't work. I have both Business and Bootstrap pack.

Neither <bp: nor <bs: work.

This is my DotvvmStartup -

![path](https://user-images.githubusercontent.com/8903532/35454081-8d9421b4-0307-11e8-952a-3e05e5579e43.PNG)

**Comment by tomasherceg** [comment]
Is there any log data in the Output window?

Select View / Output from the Visual Studio main menu and the "show output from" ComboBox should have an entry for DotVVM. Can you paste here the logs?

![image](https://user-images.githubusercontent.com/5599524/35455306-b29a7d7c-02d1-11e8-99a6-a5b796ded1e7.png)

**Comment by PolywickStudio** [comment]
1/27/18 2:11:30 AM: SET assemblySearchPath=C:\Users\XXXXX\Project\bin\Debug\netcoreapp2.0
01/27/18 2:11:30 AM: "dotnet" dotvvm-compiler --json "{\"WebSiteAssembly\":\"C:\Users\XXXXX\Project\bin\Debug\netcoreapp2.0\SecretTrader.dll\",\"WebSitePath\":\"C:\Users\XXXXX\Project\",\"FullCompile\":false,\"SerializeConfig\":true,\"DothtmlFiles\":[],\"OutputResolvedDothtmlMap\":true,\"CheckBindingErrors\":true}"
01/27/18 2:11:35 AM: DotVVM Compiler finished in 4875 ms.
01/27/18 2:23:17 AM: SET assemblySearchPath=C:\Users\XXXXX\Project\bin\Debug\netcoreapp2.0
01/27/18 2:23:17 AM: "dotnet" dotvvm-compiler --json "{\"WebSiteAssembly\":\"C:\Users\XXXXX\Project\bin\Debug\netcoreapp2.0\SecretTrader.dll\",\"WebSitePath\":\"C:\Users\XXXXX\Project\",\"FullCompile\":false,\"SerializeConfig\":true,\"DothtmlFiles\":[],\"OutputResolvedDothtmlMap\":true,\"CheckBindingErrors\":true}"
01/27/18 2:23:21 AM: DotVVM Compiler finished in 3875 ms.
01/27/18 2:30:13 AM: SET assemblySearchPath=C:\Users\XXXXX\Project\bin\Debug\netcoreapp2.0
01/27/18 2:30:13 AM: "dotnet" dotvvm-compiler --json "{\"WebSiteAssembly\":\"C:\Users\XXXXX\Project\bin\Debug\netcoreapp2.0\SecretTrader.dll\",\"WebSitePath\":\"C:\Users\XXXXX\Project\",\"FullCompile\":false,\"SerializeConfig\":true,\"DothtmlFiles\":[],\"OutputResolvedDothtmlMap\":true,\"CheckBindingErrors\":true}"
01/27/18 2:30:17 AM: DotVVM Compiler finished in 4203 ms.
01/27/18 2:32:37 AM: SET assemblySearchPath=C:\Users\XXXXX\Project\bin\Debug\netcoreapp2.0
01/27/18 2:32:37 AM: "dotnet" dotvvm-compiler --json "{\"WebSiteAssembly\":\"C:\Users\XXXXX\Project\bin\Debug\netcoreapp2.0\SecretTrader.dll\",\"WebSitePath\":\"C:\Users\XXXXX\Project\",\"FullCompile\":false,\"SerializeConfig\":true,\"DothtmlFiles\":[],\"OutputResolvedDothtmlMap\":true,\"CheckBindingErrors\":true}"
01/27/18 2:32:41 AM: DotVVM Compiler finished in 3813 ms.
01/27/18 2:40:36 AM: SET assemblySearchPath=C:\Users\XXXXX\Project\bin\Debug\netcoreapp2.0
01/27/18 2:40:36 AM: "dotnet" dotvvm-compiler --json "{\"WebSiteAssembly\":\"C:\Users\XXXXX\Project\bin\Debug\netcoreapp2.0\SecretTrader.dll\",\"WebSitePath\":\"C:\Users\XXXXX\Project\",\"FullCompile\":false,\"SerializeConfig\":true,\"DothtmlFiles\":[],\"OutputResolvedDothtmlMap\":true,\"CheckBindingErrors\":true}"
01/27/18 2:40:40 AM: DotVVM Compiler finished in 4250 ms.
