### ISSUE TITLE
ValidationSummaryTarget and custom error after login

### ISSUE THREAD

**Issue by DannyRusnok** [riganti/dotvvm#366]
Hello,

Iam creating a Sign in dialog and I want to show validation message after unsuccesfull login.
This is my ViewModel:
![image](https://user-images.githubusercontent.com/7890176/26925069-8f2d1d30-4c48-11e7-81ee-6be630b45228.png)

Look at row, where I am adding a new Error into list of errors and as a propertyPath I have nameof(_login).

This is my masterpage html
![image](https://user-images.githubusercontent.com/7890176/26925165-fa5abea0-4c48-11e7-89b4-d5904fbfdffb.png)

At dot:ValidationSummary I am defining Vliadation.Target as my LoginDTO object.
Problem is, require messages is showed after submit notfilled login dialog, but my custom message is not showing in summary after submit login dialog with not existing login.

Thank you for help

**Comment by tomasherceg** [comment]
The `PropertyPath` should be relative to the `Validation.Target`, so the `PropertyPath` should be  `nameof(LoginDTO.Login)`.

**Comment by DannyRusnok** [comment]
In this case, Validation.Target is object of class LoginDTO, which name is _login.

**Comment by tomasherceg** [comment]
Oh, I understand, you need the error to be related to the entire object. In that case you would need something like `$this`, but I don't think it will work. 
Does it work when you omit the `PropertyPath` property at all? It should be optional.

**Comment by DannyRusnok** [comment]
I tried it without PropertyPath. Not working.

**Comment by DannyRusnok** [comment]
The only way is not to specify validation.target, but its not correct way. 
Imagine when I have two forms at one page and similier code for both. Summary validation can show error at wrong place on the page depending where I have ValidationSummary definition.

**Comment by DannyRusnok** [comment]
Another problem is when I tried to debug the code.

**Comment by tomasherceg** [comment]
What is the problem when you debug the code?

We'll fix the PropertyPath issue - when it is not specified, it should mean the `Validation.Target` itself so it should be displayed in the `ValidationSummary`.

**Comment by quigamdev** [comment]
Closed for now. Waiting for response.
