### ISSUE TITLE
GridViewTextColumn needs a TextChanged command.

### ISSUE THREAD

**Issue by siwicgrey** [riganti/dotvvm#368]

**Comment by exyi** [comment]
In general, there is quite a lot of controls that only wrap another control, so it would be cool to support some easy way to access the inner control properties to eliminate the need to copy all of them and then handle issues (like this one) that we forgot about one.

Maybe it could be used like properties: `<dot:GridViewTextColumn TextBox.TextChanged=... />` and then copied using a simple `foreach` loop in the column.

Or the control could be accessible as a inner element property: `<dot:GridViewTextColumn><TextBox TextChanged=... /> </doty:GridViewTextColumn />`. The GridViewTextColumn.cs would look like:

```C#
[MarkupOptions(InnerElement)]
public TextBox TextBox { get; set; }

override OnInit() {
    TextBox.SetValue(TextBox.TextProperty, this.GetValueRaw(TextProperty));
    ... few other most common properties
    Children.Add(TextBox)
}

cc @djanosik

**Comment by tomasherceg** [comment]
For now, let's just add the property to the column and set it to the TextBox when the column is in the edit mode.
