### ISSUE TITLE
SecurityError Exception in deserialize properties with ProtectAttribute

### ISSUE THREAD

**Issue by MichalOberreiter** [riganti/dotvvm#371]
Hi,
I'd like to start using ProtectAttribute, but I can't get over this error: 
"Failed to deserialize viewModel encrypted values"

Try this code:
ViewModel:
```
public class ProtectAttributeTestViewModel : DotvvmViewModelBase
    {
        [Bind(Direction.ServerToClient)]
        public CustomClass ErrorMessage { get; set; }

        [Protect(ProtectMode.SignData)]
        public string PropertyTwo { get; set; }


        public void Postback()
        {

        }
    }

    public class CustomClass
    {
        public string Text { get; set; }
    }
```
dothtml:
` <dot:Button Text="Postback" Click="{command: Postback()}" Validation.Enabled="false"></dot:Button>
`
When I send postback, it throw exception.
BUT when you remove BindAttribute 
OR rename property 'ErrorMessage' to 'PropertyOne'
OR retype property 'ErrorMessage' to 'bool', it starts to work.. Very interesting :-)

Please any idea for quick solution I can do?

**Comment by exyi** [comment]
This seems to be solved now. @ENgateman do you agree? Could you please close the issue?

**Comment by ENgateman** [comment]
@exyi I agree. As far as I know, every combination of the Protect and Bind attributes in a single viewModel should behave correctly now.
