### ISSUE TITLE
Can't use nested DotvvmBindableObjects

### ISSUE THREAD

**Issue by djanosik** [riganti/dotvvm#374]
I've found an issue that makes it impossible to have a property of type `DotvvmBindableObject` on another `DotvvmBindableObject`. Consider the following code:
```csharp
public class Operator : DotvvmBindableObject 
{
   // ....
}

public class Field : DotvvmBindableObject 
{
    public List<Operator> Operators { get; set; }   
    // ...
}
```
DotVVM will try to set `Parent` of an `Operator` instance to a `Field` instance. But it will throw an exception because the `Parent` property is of type `DotvvmControl`.

Why do we care about `Parent` and `Children` in this case? We should let developers to decide what to do with simple bindable objects.

**Comment by exyi** [comment]
The problem is that `Parent` property is required on DotvvmBindableObject for inherited properties (and without DataContext bindings would not work), and its type is `DotvvmControl`. I'll change it to `DotvvmBindableObject` for 1.2, as it is a small breaking change.
