### ISSUE TITLE
Ugly syntax highlight for .cs files in Dark Theme

### ISSUE THREAD

**Issue by UlyssesWu** [riganti/dotvvm#379]
After intstalling the VS Extension, the syntax highlight for CSharp source code files becomes ugly:

![20170707141411](https://user-images.githubusercontent.com/4312781/27945537-064e6e26-6320-11e7-8b58-b4f748a1e15d.png)

How it looks like with DotVVM Extension disabled:

![20170707141858](https://user-images.githubusercontent.com/4312781/27945576-30e98378-6320-11e7-9194-ae79cba34b1f.png)

**Comment by tomasherceg** [comment]
The workaround is to switch the theme to white and back to the dark one immediately.

We have already fixed the issue in our internal builds of the extension, we are shipping the update soon.

**Comment by UlyssesWu** [comment]
Alright, thanks!
