### ISSUE TITLE
Route generation with parameters is too smart

### ISSUE THREAD

**Issue by PavelBansky** [riganti/dotvvm#381]
I have a following route:

```
config.RouteTable.Add("ScanDetail", "repository/{RepoKey}/scan/{ScanId}", "Views/Scans/scandetail.dothtml");
```

In my view I'm having following line inside of GridViewTemplateColumn, inside of GridView
```
<dot:RouteLink RouteName="ScanDetail" Param-ScanId="{value: Id}">
```
The produced link is correct, even without **Param-RepoKey** being defined. 
I do happen to have a **RepoKey** property in the ViewModel, but why is it being explicitly used??

```
http://localhost:54361/repository/84f0c7fc0e03470ca359a2501c9bb84e/scan/12
```

Is it a bug or feature?

**Comment by tomasherceg** [comment]
This is a feature. The value of the `RepoKey` parameter does not come from the viewmodel, but it comes from the route parameters of the current page.
