### ISSUE TITLE
Expose inner control properties

### ISSUE THREAD

**Issue by exyi** [riganti/dotvvm#391]
There is quite a lot of controls that only wrap another control, so it would be cool to have an easy way to access the inner control properties to eliminate the need to copy all of them to the outer control and then assign them to the inner one. And then handle issues (like like #368 ) that we forgot about one.

Maybe it could be used like attached properties: `<dot:GridViewTextColumn TextBox.TextChanged=... />` and then copy them using a simple foreach loop to the inner control.

Or the control could be accessible as a inner element property: `<dot:GridViewTextColumn><TextBox TextChanged=... /> </doty:GridViewTextColumn />`. The GridViewTextColumn definition would look like:

``` C#
[MarkupOptions(InnerElement)]
public TextBox TextBox { get; set; }

override OnInit() {
    TextBox.SetValue(TextBox.TextProperty, this.GetValueRaw(TextProperty));
    ... few other most common properties
    Children.Add(TextBox)
}
```

cc @djanosik

**Comment by djanosik** [comment]
I really like this idea but maybe it's not as necessary as I initially thought. Often when you wrap some control you don't want to expose all of its properties. So you need to copy the rest of them anyway.

**Comment by exyi** [comment]
This problem is also partially solved by control capabilities introduced in https://github.com/riganti/dotvvm/pull/535. I will probably close this issue as we merge the PR and introduce control capabilities for all controls in dotvvm.

**Comment by exyi** [comment]
I'm closing this as we decided to go for control capabilities. It's not merged yet, but we don't need many issues for the same thing
