### ISSUE TITLE
Glimpse tracing support

### ISSUE THREAD

**Issue by tomasherceg** [riganti/dotvvm#393]
Similarly to MiniProfiler, we can do an integration with [Glimpse](http://getglimpse.com/).

Please upvote if you are interesed.

**Comment by exyi** [comment]
Seems that nobody is really interested, so it's not worth the maintenance effort. There is like gazillion of tracing/debugging/monitoring tools and we can't support all we could think of. I have written a documentation page about the interface, so everybody can put those events into any monitoring think they like: https://github.com/riganti/dotvvm-docs/pull/69
