### ISSUE TITLE
ETW tracing support

### ISSUE THREAD

**Issue by tomasherceg** [riganti/dotvvm#395]
We should add an integration with ETW to be able to diagnose applications in PerfView and other tools.

**Comment by exyi** [comment]
Seems that nobody is really interested, so it's not worth the maintenance effort. There is like gazillion of tracing/debugging/monitoring tools and we can't support all we could think of. I have written a documentation page about the interface, so everybody can put those events into any monitoring think they like: https://github.com/riganti/dotvvm-docs/pull/69
