### ISSUE TITLE
VS 2017 issues, DotVVM compiler exited unsucessfully.

### ISSUE THREAD

**Issue by zulq** [riganti/dotvvm#408]
Always getting this error: _DotVVM compiler exited unsuccessfully. Maybe the app has not been built, the application DLL is unaccessible, or there is a problem with the Startup class._
Occasionally also VS freezes and I have to kill it from Task Manager or so.

**Comment by tomasherceg** [comment]
Which version of DotVVM NuGet packages are you using? 
Are you on OWIN, or on ASP.NET Core?

**Comment by zulq** [comment]
DotVVM.AspNetCore _1.1.2_ on Asp.Net Core.

**Comment by tomasherceg** [comment]
OK, this looks like the newest version. Can you share the details of the exception? 
The yellow bar doesn't prevent the application from running in most cases, it is only an informative message.

We will be releasing a new version of the VS Extension in a few days with some stability improvements.

**Comment by zulq** [comment]
Error details: _DotVVM compiler has thrown an exception: No executable found matching command "dotnet-dotvvm-compiler" -_

**Comment by tomasherceg** [comment]
Oh, I see. The latest version of the VS Extension forgets to add the following line in the CSPROJ file. 

```
  <ItemGroup>
    <DotNetCliToolReference Include="DotVVM.Compiler.Light" Version="1.1.2" />
  </ItemGroup>
```

**Comment by zulq** [comment]
@tomasherceg, I believe then this is a documentation issue and not the extension. I followed the guide for Asp.Net Core from here: **_How to Start with existing project_** https://www.dotvvm.com/docs/tutorials/how-to-start-existing-app/latest
I believe the documentation should have mention that as well i.e. to add the package:
```
<ItemGroup>
    <DotNetCliToolReference Include="DotVVM.Compiler.Light" Version="1.1.2" />
  </ItemGroup>
```

**Comment by tomasherceg** [comment]
Actually, it's both. 

The extension should add the line automatically in a new project, and in the documentation, there should be a note about projects crated in VS Extension 1.1.0.49 and older which require this line.
I will add it also in the Troubleshooting section.
