### ISSUE TITLE
Support for decorator controls

### ISSUE THREAD

**Issue by tomasherceg** [riganti/dotvvm#41]
Many controls and HTML elements do not have Click handler and it is not wise to add it to all of them. Instead a concept of Decorator should be implemented. Each BindableControl will have an option to declare whether it can be decorated or not, and when it can, one or more decorators can be applied to it. They will be allowed to wrap the control in a HTML element or add an attribute to it.
It should be easy to apply a decorator, e.g. via attached property.

Example (we consider a decorator named EventsDecorator):
```HTML
<tr Event.Click="{command: Test()}">...</tr>
```

**Comment by exyi** [comment]
I don't like that one "Control" will have multiple independent function (Click, ValueChanged, KeyPress, etc in one class). What about something like DecoratorProperty that will have some functionality (adding attributes, ...) and one DecoratorControl will wrap the decorated control and call decorator properties. Or they could be called by base RedwoodControl.

**Comment by exyi** [comment]
I have imeplemented active properties. The decorator will not be implemented
