### ISSUE TITLE
VS 2017 extension, Dark theme broken

### ISSUE THREAD

**Issue by zulq** [riganti/dotvvm#414]
After installing the DotVVM extension on VS 2017 the dark theme is broken. The workaround am using is to change the color theme to another and then revert.
![image](https://user-images.githubusercontent.com/23703598/28666409-b9295114-72b6-11e7-82e0-214cc3510c1c.png)

![image](https://user-images.githubusercontent.com/23703598/28666429-d060be08-72b6-11e7-9066-83679935faf1.png)

**Comment by Mylan719** [comment]
Sorry for that. Can I ask which exact version of the extension you are using? You can find out by going DotVVM->About. Chances are this issue has already been fixed in most recent build. We will be releasing soon.

**Comment by zulq** [comment]
@Mylan719, **_Currently installed version: 1.1.0.49_**

**Comment by Mylan719** [comment]
@zulq I believe that it is fixed in 1.1.0.54

**Comment by zulq** [comment]
@Mylan719  where can I get that release from? Because when I check for updates, below is what I get:
![image](https://user-images.githubusercontent.com/23703598/28668846-4acb8da8-72c1-11e7-88a5-b4dd409df2cd.png)

**Comment by Mylan719** [comment]
.50-.53 were internal, .54 is being tested internally, and if there are no major issues, which now looks promising, it will be released. But don't quote me on that @quigamdev  manages releases.

**Comment by martinsura** [comment]
Btw must frustrating issue around dotvvm :)

**Comment by tomasherceg** [comment]
I totally understand and apologize for the inconvenience, we'll release the new version in a few days.

**Comment by zulq** [comment]
Anytime timeline as to when this fix will be release?

**Comment by tomasherceg** [comment]
We have just released an updated version of the extension. Can you please try it?

**Comment by zulq** [comment]
Sorry for the late reply, seems to be working fine now. Being busy at work and only using it in a side project. Was trying to convince my bosses but no luck yet.

**Comment by tomasherceg** [comment]
No problem, thanks for letting us know.
