### ISSUE TITLE
Translation of .NET methods to JS

### ISSUE THREAD

**Issue by exyi** [riganti/dotvvm#417]
As we are trying to optimize DotVVM for a whole range of different use cases we are adding more and more features to the markup, especially to JS-translated binding (like REST API invocations, some methods). And as we are adding more feature to bindings to handle these use cases, we are forcing devs to write logic in the view - like direct calls to web api, conditions in static commands and so on. Not only can it be ugly, but you are still limited by the set of expressions supported by the binding parser and you can't deduplicate your code by using functions.

I'm not sure how exactly should we implement it, there are several possibilities:

* A compile-time or design-time helper, that would translate C# method to JS and register it for JavascriptTranslator.
    Seems to be easy to implement for simple methods, but I think we could have problems with properties that have a different name on server and client, we would not be able to invoke static commands or use other methods that are translatable, but registered at runtime.
* Use something like [Blazor](https://github.com/SteveSanderson/Blazor) - host a lightweight .NET runtime (interpreter) in WASM/ASM.JS and run the methods in there. But I'm not sure how to transfer the data from and to the .NET method and I'm afraid that we will have to serialize/deserialize entire ViewModel to some ugly binary form.
* Use existing .NET to JS translator - I know about JSIL, Bridge, FunScript, and Fable. I think that it would be quite easy to use Fable for a simple method, I'm not sure about things like client renamed properties. Another advantage of Fable is that it is quite powerfull (I think they are able to translate entire F# compiler to JS), but still produces readable code and supports source maps. But requires you to write the logic in F#...
* I was playing with [self-symbolic-execution](https://github.com/exyi/SymbolicInterpreter) - a magic that gets a method body from Reflection (with the help of Sigil) and does symbolic interpretation of the method, to realise what the method really does. It returns the result in form of Linq.Expression, so it could be directly passed to our JavascriptTranslator to get the translation. The advantage is that it runs runtime, so it can read the configuration and translate renamed properties, other translatable methods, and static commands correctly.

**Comment by djanosik** [comment]
Another possibility might be to use [IL2CPP](https://docs.unity3d.com/Manual/IL2CPP.html) to convert IL code to C++ code. It's used by Unity to build WebGL games that can be exported to WebAssembly.

**Comment by exyi** [comment]
@djanosik This looks quite interesting, I didn't know that something like that exists. But I'm afraid, that we will have problems with JS to WASM communication (transforming entire ViewModel to some binary layout and back, which will have similar overhead to normal postback for the client). Maybe it would be interesting to consider complete migration to WASM with the migration to VDOM, but I'm afraid that this would make the process even harder and does not have that many benefits.

**Comment by djanosik** [comment]
It looks like guys from Mono are working on WASM support.
http://www.mono-project.com/news/2017/08/09/hello-webassembly/

**Comment by djanosik** [comment]
Blazor has been rewritten to use Mono instead of the old .NET interpreter. It look really interesting.
https://github.com/aspnet/blazor

**Comment by exyi** [comment]
> Blazor has been rewritten to use Mono instead of the old .NET interpreter. It look really interesting.

Yes, we finally have a decent competitor.

> Can we use it somehow?

Certainly, but not in the DotVVM Framework. I'm afraid that we should reconsider what are the actual benefits of using DotVVM instead of Blazor.

**Comment by tomasherceg** [comment]
Well, it depends. I will ask at the MVP Summit about the plans for Blazor. It is still more an experiment than a real project, and it will certainly take at least a year until the outputs are small enough and another year until a significant number of people adopt this platform. 
Additionally, it is still MVC. I am sure there will always be a room for MVVM frameworks.

**Comment by djanosik** [comment]
Well, it looks more like Razor pages. It's closer to MVVM than to MVC. This is how components look like:
```html
<div class="my-styles">
  <h2>@Title</h2>
  @RenderContent(Body)
  <button onclick=@OnOK>OK</button>
</div>

@functions {
    public string Title { get; set; }
    public Content Body { get; set; }
    public Action OnOK { get; set; }
}
```

**Comment by djanosik** [comment]
It makes little sense to run DotVVM apps entirely on client-side but we should keep this in mind. It may be better to compile some logic to WASM instead of translating to JS.

**Comment by exyi** [comment]
On Wed, 2018-02-07 at 11:35 +0000, Tomáš Herceg wrote:
> Well, it depends. I will ask at the MVP Summit about the plans for
> Blazor. It is still more an experiment than a real project, and it
> will certainly take at least a year until the outputs are small
> enough and another year until a significant number of people adopt
> this platform.

Yes, but we are talking about future and even if Blazor itself will be
cancelled, WebAssembly will not be. And Microsoft seems to be serious
about it, I doubt they will tell you at MVP summit that they did it
only to gain few likes on twitter.

> Additionally, it is still MVC. I am sure there will always be a room
> for MVVM frameworks.

It's not MVC at all. They don't actually claim to use any "core
pattern" like that, but I think it uses a component-based approach
simmilar to React. But it supports two-way binding... Have a look at
the Steve Sanderson's demo https://www.youtube.com/watch?v=MiLAE6HMr10&
t=31m45s (it's about the older prototype, but the concept should be the
same). Anyway the MVVM buzzword does not actually mean anything in this
context...

**Comment by exyi** [comment]
On Wed, 2018-02-07 at 12:29 +0000, Dusan Janosik wrote:
> It makes little sense to run DotVVM apps entirely on client-side but
> we should keep this in mind. It may be better to compile some logic
> to WASM instead of translating to JS.

Here we have a little problem with the DotVVM design - everything is
generated on server, but for a specific request, we only have
precompiled bindings, but the components get composed at runtime. And
it's easy to string.Concat some Javascript code, but it would kill the
performance if we would invoke Emscripten on each request.

Other problem is that when you have already loaded the Mono runtime,
why would you want to compose components on server?

**Comment by tomasherceg** [comment]
Oh, I forgot that they are using Razor Pages. 
In that case, we should have a meeting or call and discuss our further strategy.

**Comment by naasking** [comment]
Just FYI, I also have a [lightweight IL analysis project](https://github.com/naasking/CIL) that's similar in spirit to your symbolic executor. It currently decompiles into LINQ expressions, but the interface is fully abstract, so you can in principle add any backend. I haven't had time to expand it further, but I plan to add a JS backend. If there's interest, I'd totally pick it up again and polish off the rough edges.

**Comment by exyi** [comment]
@naasking That look really nice - we actually use System.Linq.Expression as a intermediate representation of bindings, so our `JavascriptTranslator` can translate it directly into Javascript (with the right knockout unwraps and so on). Do you think it will be possible/easy to migrate it to netstandard? I'd like to play with that sometime - I think that creating a simple translator based on that would be pretty straignforward.

Btw, I am also looking at integration with Blazor/WebAssembly which looks pretty promising.

**Comment by naasking** [comment]
I've been in the process of porting my libs to .NET standard, so I just did quick pass over this one and easily updated to .NET standard 2.0. Unfortunately, some of the methods and types currently used only became available in .NET standard as of 2.0, so I'd have to take more time to look into whether it's possible to push the version lower.

**Comment by exyi** [comment]
Cool, I'll have a look at it. DotVVM is netstandard2.0 anyway, so that's not an issue.

**Comment by exyi** [comment]
@naasking I have tried your decompilation library and it's in principle very similar to my symbolic execution experiment, except it does not do any branching and expresion simplification. I don't say it's not useful, but I think that the use case for translating .NET method is very limited by this. Anyway, I can try to publish this as a dotvvm-contrib package and see if it will be useful for anyone.

**Comment by tomasherceg** [comment]
We've decided that this concept is outdated and we don't plan to implement this feature.
