### ISSUE TITLE
DotvvmInterrupRequestExecutionException during Redirect

### ISSUE THREAD

**Issue by zulq** [riganti/dotvvm#426]
Am doing a `Context.RedirectToUrl("Url")` and get the exception in the title. The route is registered and working fine. I have also tried with `Context.RedirectToUrl("/Url")` and `Context.RedirectToRoute("/Url")` but keep getting same error. 
No related how do I transfer a value between page requests?

**Comment by exyi** [comment]
As the name indicates, this exception is used to interrupt the request and redirect you. More info at https://www.dotvvm.com/blog/1/Why-I-am-getting-the-DotvvmInterruptRequestExecutionException-

To transfer a value between page requests you will have to route parameter or query parameter.
