### ISSUE TITLE
TextBox UpdateAfterKeyDown change doesn't fire when the user clicks on the clear icon in the textbox

### ISSUE THREAD

**Issue by tomasherceg** [riganti/dotvvm#430]
In some browsers, the `input` controls have the clear icon (cross) on the right side, but when you click on it, the change event is not fired even when `UpdateAfterKeyDown` is set to `true`.

**Comment by djanosik** [comment]
And it shouldn't because clearing the input is not "keydown". We should rename the property to `UpdateTextOnInput` and use `textInput` binding instead.

**Comment by tomasherceg** [comment]
Can we close this?

**Comment by djanosik** [comment]
No. It is not yet fixed.
