### ISSUE TITLE
IHttpRequest is missing some properties which are present in Url

### ISSUE THREAD

**Issue by tomasherceg** [riganti/dotvvm#432]
The `Host` property is missing from `IHttpRequest`, but the other properites like `QueryString` are there.
We should either remove all of them and keep `Uri` only (which is a breaking change), or add the missing ones.

**Comment by Rumbeer** [comment]
Is there a reason why `Path`, `PathBase`, `Query`... properties in Owin implementation are set in the constructor and not from `OriginalRequest` like .Net core implementation or other properties in this class?

**Comment by exyi** [comment]
Done in #465
