### ISSUE TITLE
VS 2015 extension 1.1.0.58 broken?

### ISSUE THREAD

**Issue by MichalOberreiter** [riganti/dotvvm#436]
Hi,
is anyone have issues with this new extension for VS 2015?
After install, VS is incompatible with existed Dotvvm project, can't create new Dotvvm project (dissapeared from menu) and it says that installed version 1.1.0.57.

We tried to uninstall extension, clear VS cache, but nothing works.
Any other ideas to get it work?
Thx for help

**Comment by tomasherceg** [comment]
It looks like an issue with DotVVM installer. Can you try to run the installer again and repair the installation?

**Comment by MichalOberreiter** [comment]
Installer has only options "Upgrade", "Uninstall", "No action" 
and upgrade function can't install newer version 1.1.5.8. 
Upgrade ends successfully, but installed version is still 1.1.5.7 (Tried install from VS and from installer in Dotvvm website)

**Comment by MichalOberreiter** [comment]
Is there any option to download previous versions of dotvvm installer? So we could try install other version

**Comment by smolda74** [comment]
I have the same problem. 
VS2015 offers an update at 1.1.0.58. 
I downloaded, installed, and I will not open the project again. 
Installer "DotvvmInstaller.1.1.0.58.exe" says "Current DotVVM version: 1.1.0.57". 
Even the uninstallation and install again (DotvvmInstaller.1.1.0.58.exe) did not help. The project can now be opened but DotVVM is not working. VS 2015 does not even offer project templates and pages. :-(

**Comment by quigamdev** [comment]
Hi, what was the latest version you had installed before 1.1.0.58?

**Comment by smolda74** [comment]
I do not know. In the morning, the VS2015 offered me an update and I let go. I do not know what version I had before.

**Comment by quigamdev** [comment]
Ok. I'm working on a simulation of the crash and I am going to release the fix as soon as possible.

**Comment by smolda74** [comment]
I do not know for sure, but the previous was probably 1.0.4.4. No guarantee.

**Comment by quigamdev** [comment]
@smolda74 @MichalOberreiter Are you in Insider program?

**Comment by smolda74** [comment]
No.

**Comment by tomasherceg** [comment]
Can you please attach the installation log file? It should be located at `c:\ProgramData\DotVVM for Visual Studio\Logs`.

**Comment by smolda74** [comment]
[2017-08-16.txt](https://github.com/riganti/dotvvm/files/1228080/2017-08-16.txt)

**Comment by quigamdev** [comment]
I released new version of our extension. The latest version is 1.1.0.59.
Please let us know whether this new version fixed the problem.

**Comment by smolda74** [comment]
Excellent. Thank you!

**Comment by MichalOberreiter** [comment]
Works now, perfect.
