### ISSUE TITLE
AuthenticationManager is obsolete

### ISSUE THREAD

**Issue by tomasherceg** [riganti/dotvvm#440]
They made AuthenticationManager obsolete: https://github.com/aspnet/Security/issues/1310

We need to decide whether we change the API too, or whether we adapt the new infrastructure to the existing interface we already have.

**Comment by exyi** [comment]
The `GetAuthentication(...) -> AuthenticationManager` method is added in https://github.com/riganti/dotvvm/commit/d623ae5ddf57ecf3617eb68454d546f675b64496 It returns a simple wrapper around the new authentication extension methods.
