### ISSUE TITLE
Dropping support for ASP.NET Core 1.x and moving to ASP.NET Core 2.0

### ISSUE THREAD

**Issue by tomasherceg** [riganti/dotvvm#441]
Recently, we have found a lot of breaking changes that make practically impossible to support both ASP.NET Core 1 and ASP.NET Core 2 without making separate NuGet packages.
Most of the breaks are in the authentication and authorization packages.

Since ASP.NET Core 2 is RTM now and many companies were waiting with the adoption of .NET Core, so they will start with 2.0 and just skip the first version, I suggest to *drop support for ASP.NET Core 1.x immediately and concentrate on 100% compatibility with ASP.NET Core 2.0*.
Supporting both versions would require a lot of effort and nasty code full of dynamic and reflection, and I'd rather invest the effort into something meaningful.

This should be a high priority issue for now and we should also release *DotVVM 1.1.6* as soon as possible, because 1.1.5 doesn't work with ASP.NET Core 2.0 libraries well.

_Please, let us know if you are on ASP.NET Core 1.0 and cannot migrate._

**Comment by EmbraceUnity** [comment]
Looks like this is done and can be closed.
