### ISSUE TITLE
ShouldSerialize* or other kind of programmatical way to tell which properties shall be serialized

### ISSUE THREAD

**Issue by tomasherceg** [riganti/dotvvm#445]
The `Newtonsoft.Json` library allows to use a special properties with the `ShouldSerialize` prefixes.
Our serialized doesn't support this behavior, we only have the `Bind` attribute to modify the serialization settings. 

We should provide a programmatical way to specify which property will be transferred to the client. 
Is there anything like that already in the framework? @exyi

**Comment by exyi** [comment]
Do you mean the serializer configuration API introduced in #262?
