### ISSUE TITLE
Use History API to do SPA instead of hashbang

### ISSUE THREAD

**Issue by tomasherceg** [riganti/dotvvm#449]

**Comment by GusBeare** [comment]
I nearly started building an SPA with DotVVM but was put off by the use of hashbang. Would really leap at it once the History API is available.

**Comment by tomasherceg** [comment]
If you use the `RouteLink` controls to create links between pages, you won't need to change the application when we introduce the History API - it will just work.
And we will make backwards compatible so if there is a link with hashbang, it will work too.
