### ISSUE TITLE
Cannot change email address for profile on dotvvm.com

### ISSUE THREAD

**Issue by EmbraceUnity** [riganti/dotvvm#452]
I'd like to update my email address, but that doesn't seem possible on the profile screen.

**Comment by tomasherceg** [comment]
Please contact us at info@dotvvm.com, we will update it for you.

**Comment by symbiogenesis** [comment]
@tomasherceg  I've tried to email that address from both accounts, but it was denied just now.

**Comment by tomasherceg** [comment]
Sorry, we have some DNS issues right now. Can you please try the [contact form](https://www.dotvvm.com/support/contact-us)? It should work. Sorry for the inconvenience.
