### ISSUE TITLE
Live example of controls in documentation

### ISSUE THREAD

**Issue by ganzikk02** [riganti/dotvvm#453]
As it may seem useless for advanced web designers, it would be nice to have live example of each control in _Usage & Scenarios_ area. Is is quite annoying to go to bootstrap documentation link and it is even worse in business pack documentation where only text description is available. Would you consider QoL like this?

**Comment by tomasherceg** [comment]
Thank you for the suggestion, in fact we are already working on the live samples, they should be available in a few weeks.
