### ISSUE TITLE
Remove synchronous methods from GridViewDataSet

### ISSUE THREAD

**Issue by djanosik** [riganti/dotvvm#467]
Remove synchronous methods like `GoToNextPage` from `GridViewDataSet`. They may cause deadlocks in classic ASP.NET applications.

**Comment by symbiogenesis** [comment]
Will this include LoadFromQueryable?

**Comment by djanosik** [comment]
I don't think so. This method is not causing deadlocks and there is no Async alternative.

**Comment by exyi** [comment]
We should only mark them as obsolete and remove them in next major version.

**Comment by djanosik** [comment]
Agreed. Marking them as obsolete is good enough for now.
