### ISSUE TITLE
Rename GridViewDataSet to DotvvmDataSet

### ISSUE THREAD

**Issue by djanosik** [riganti/dotvvm#468]
`GridViewDataSet` was created to be used in GridView but I am sure it will be used elsewhere. Therefore I think we should rename it to `DotvvmDataSet`.

- [ ] Replace `GridView` with `Dotvvm` in all related classes and interfaces.
- [ ] Replace `Row` with `Item` in eg. `IRowEditGridViewDataSet` or `IRowEditOptions`.

We may keep the old classes, interfaces and properties and mark them as obsolete.

**Comment by symbiogenesis** [comment]
For compatibility, couldn't you have a wrapper to preserve the GridViewDataSet syntax, which is closer to XAML. I agree that the code could be shared, though.

**Comment by djanosik** [comment]
The syntax will stay the same. I want to change only names, to make it more universal.

**Comment by exyi** [comment]
Unfortunately, I don't see a way to make this change backward compatible and the DataSet is used a lot in applications, do you really think it's worth it? Upgrade tool could help but IMO, it will not be easy to ship and apply on all projects.

**Comment by djanosik** [comment]
I've discussed it with @exyi and he is right. There is no good way to rename it in backward compatible manner. I will just make sure it looks consistent in inherited data sets.
