### ISSUE TITLE
Warn when comma (,) is used in Property value of decimal type

### ISSUE THREAD

**Issue by Mylan719** [riganti/dotvvm#473]
It appears that using comma (,) instead of decimal dot (.) is a common mistake.  
When you write:
```
<cc:Test DoubleProperty="2,1">
```
Your expectation could be that `TestProperty` would be assigned with value `2.1` wheres in reality the value would be `21`.
Problem is that numeric values in framework are treated as input in human language and not as in C#.
This may lead to hard to debug errors. I suggest that usage of comma in property values of numeric type is forbidden.

**Comment by quigamdev** [comment]
@tomasherceg  @exyi  @djanosik @martindybal  What do you think? 

I agree to use only dot.

**Comment by tomasherceg** [comment]
Only dot. I would reserve comma to be used in the future, to e.g. provide to coordinates or collections of values.

**Comment by djanosik** [comment]
I agree. We should exclude `AllowThousands` from `NumberStyles` when parsing numbers.

**Comment by Mylan719** [comment]
I have already implemented warning like this to VisualStudioExtension, which is show if number was parsed as valid numeric type and it contains comma:
`Comma in numeric value act as thousands separator, not as decimal mark. Is this what you've intended?`

**Comment by tomasherceg** [comment]
I would just put there a simple error message `The value is not in a correct numeric format.`
I don't like these special validation cases.
