### ISSUE TITLE
UpdateProgress don't generate display none attribute

### ISSUE THREAD

**Issue by martindybal** [riganti/dotvvm#474]
The UpdateProgress shows up and then is hiding by JavaScript.

Workaround 

    <dot:UpdateProgress style="display: none;">

This should be default behavior

**Comment by exyi** [comment]
It depends. If you think of initial page load as an update, then the behavior is correct. If it would be named PostbackProgress, then I'd definitely agree, but I'm not sure here.

**Comment by quigamdev** [comment]
@martindybal It would be breaking change. Some web sites expect that UpdateProgress is displayed even for loading of page.

**Comment by quigamdev** [comment]
We can add an attribute (something like DisabledWhenLoadingPage) that would disable showing the UpdateProgress during the loading page time.

**Comment by djanosik** [comment]
Do we really need this? `UpdateProgress` does not have default UI. You need to style it yourself. Is it such big deal to add another CSS property?

**Comment by exyi** [comment]
@djanosik I agree with you, I think that reimplementing things that can be done using CSS is a road to hell, see WebForms for more context...

**Comment by quigamdev** [comment]
As a result of this conversation I think we can close this issue.
