### ISSUE TITLE
Setting default SortingOptions prior to GetDataFromQueryable breaks sorting

### ISSUE THREAD

**Issue by symbiogenesis** [riganti/dotvvm#480]
Following the example in the documentation here:

https://www.dotvvm.com/docs/controls/builtin/GridView/latest

If I do what it says in the GetData method, and apply paging and sorting at that point, it will successfully sort on an initial load, but you will no longer be able to sort through clicking the column headers.

However, if you move the same two sorting options to the overrided Init method, after the creation of the GridViewDataSet, then everything works.

This seems to be a bug, rather than a documentation error.

**Comment by tomasjurasek** [comment]
After discussion with @symbiogenesis we found where was a problem. That was  bad usage SortOptions.

For example in method GetData (https://www.dotvvm.com/docs/controls/builtin/GridView/latest).
`private GridViewDataSetLoadedData<Customer> GetData(IGridViewDataSetLoadOptions gridViewDataSetLoadOptions)
        {
            var queryable = FakeDb();
            // You must check if sort expression is null, otherwise you ovveride default sort expression from GridView Column where you set 'AllowSorting' property
           if(gridViewDataSetLoadOptions.SortingOptions.SortExpression == null)
           {
               gridViewDataSetLoadOptions.SortingOptions.SortExpression = "Id";
           }
            return queryable.GetDataFromQueryable(gridViewDataSetLoadOptions);
        }`
