### ISSUE TITLE
SortAscendingHeaderCssClass and SortDescendingHeaderCssClass can't be set on GridView itself

### ISSUE THREAD

**Issue by symbiogenesis** [riganti/dotvvm#482]
In the sorting section of the [GridView documentation page](https://www.dotvvm.com/docs/controls/businesspack/GridView/latest) it says the following:

> You can also set these properties on the GridView control instead of declaring them for each column separately, using GridViewColumn.SortAscendingHeaderCssClass="value"

This doesn't seem to work, only works per-column.

**Comment by djanosik** [comment]
Thank you. It will be fixed in Business Pack 1.1.7.
