### ISSUE TITLE
Find a new solution for temporarily fixed GridViewDataSet sync deadlocks

### ISSUE THREAD

**Issue by quigamdev** [riganti/dotvvm#484]
https://github.com/riganti/dotvvm/pull/481 In this PR, there are temporarily fixed GridViewDataSet sync deadlocks. 
It is necessary to find a better solution than Task.Result.

**Comment by exyi** [comment]
I think that the GridView should not load the data, the load operation should be initialized by ViewModel. This way, the data-set works only when GridView populates it, which means that the ViewModel is dependent on the View, which is pretty messy.

**Comment by tomasherceg** [comment]
Yes, I also don't agree with the concept of `OnLoadingData` delegate, but once it is in the framework, we should keep it and make it work.

**Comment by exyi** [comment]
Do you have any way to make it work correctly? I'm afraid that it's impossible without `Wait`ing the `Task`.

**Comment by djanosik** [comment]
We have removed the `OnLoadingData` delgates from `GridViewDataSet` in #509.
