### ISSUE TITLE
Dropdownlist component not working in Mozzila browser

### ISSUE THREAD

**Issue by marthrusk** [riganti/dotvvm#485]
In Mozzila browser it's not possible to select item from dropdown component. Selected item is always null.

**Comment by djanosik** [comment]
Do you mean DropDownList from Business Pack? Can show me your markup?

**Comment by marthrusk** [comment]
Yes, its business pack component. Below is markup code. 
`<bp:DropDownList class="eControlGroup_left"
                 SelectedValue="{{value: Organization}}"
                 DataSource="{{value: Organizations}}" 
                 ItemKeyBinding="{{value: Id}}" 
                 ItemTextBinding="{{value: Name}}" >
</bp:DropDownList >`

**Comment by djanosik** [comment]
I can't reproduce the issue. There is a chance the issue is already fixed. We will release a new version soon.

**Comment by djanosik** [comment]
@marthrusk Can you confirm the issue is fixed in the latest version of BusinessPack (1.1.8)?
