### ISSUE TITLE
ViewModelValidationError requires the PropertyPath to be in the Knockout format

### ISSUE THREAD

**Issue by ENgateman** [riganti/dotvvm#488]
I wrote a sample to illustrate what I mean by that. It's in the 1.1.0 branch and its name is CustomValidation.

Basically, instead of using a string like this one: "Detail.Name" you have to use "Detail().Name" which is unexpected and annoying.

Also would it be possible to infer the PropertyPath from an Expression?

**Comment by djanosik** [comment]
I think this solved in master branch. You can use expression to specify property path.

**Comment by exyi** [comment]
There is a helper `viewModel.AddModelError(v => v.MyObject.PartOfTheForm.Property3, "It's invalid")`.  to generate these "strange" paths.

**Comment by ENgateman** [comment]
@djanosik @exyi Thank you both. That's good enough for me. I'm closing the issue.
