### ISSUE TITLE
Include polyfill for ES6 Promise

### ISSUE THREAD

**Issue by djanosik** [riganti/dotvvm#495]
We need to include polyfill for ES6 Promise in 2.0, because we still need compatibility with IE11. Is it good idea to also include polyfills for common ES6 functions?

**Comment by exyi** [comment]
We also need a polyfill for `fetch` that is used by REST API bindings. And I think it's not a bad idea to have a basic polyfill bundle, that will be loaded always when at least one required feature is missing (<=> browser is IE11, but it's feature detection). What function do you mean? I suggest:

* Promise (required by new postbacks, [supported by all decent browsers](https://caniuse.com/#feat=fetch))
* Fetch (required by rest api bindings, [supported by all decent browsers](https://caniuse.com/#feat=fetch))
* Iterators (currently not required by anything, but nice ;), [supported by all decent browsers](https://caniuse.com/#feat=es6-generators))

**Comment by djanosik** [comment]
Yes, we definitely need to include Fetch as well. But I was talking about utilities like string.padStart/padend, etc. Do we want to include them?
