### ISSUE TITLE
Dotvvm Feed in .net core mac ox

### ISSUE THREAD

**Issue by direstrepo24** [riganti/dotvvm#497]
How do I make the file confiration Nuget.config in asp.net core, fora add DotVVM Private NuGet Feed?

**Comment by tomasherceg** [comment]
The easiest way is to edit `Nuget.config` using `Nuget.exe`. On Mac OS or Linux, you will need Mono for that. 

```
nuget sources Add -Name "Dotvvm Feed" -Source "https://www.dotvvm.com/nuget/v3/index.json" -UserName "YOUR EMAIL ADDRESS" -Password "YOUR PASSWORD"
```

Or you can edit the file manually, but you will need to add the credentials section too: https://docs.microsoft.com/en-us/nuget/schema/nuget-config-file#packagesources

**Comment by direstrepo24** [comment]
excuseme, you helpme with a example the file manually?

**Comment by direstrepo24** [comment]
Hi, i have this error: "error :   Encryption is not supported on non-Windows platforms."
Mi configuration is:
<packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
    <add key="aspnet-contrib" value="https://www.myget.org/F/aspnet-contrib/api/v3/index.json" />
   <add key="DotvvmFeed" value="https://www.dotvvm.com/nuget/v3/index.json" />
  </packageSources>
  <packageSourceCredentials>
    <DotvvmFeed>
        <add key="Username" value="direstrepob@hotmail.com" />
        <add key="Password" value="12345" />
    </DotvvmFeed>
</packageSourceCredentials>

**Comment by Sejsel** [comment]
This might be caused because your NuGet client is outdated. This was likely fixed in [this commit in NuGet](/NuGet/NuGet.Client/commit/680fcc2f4aa2b0cc53afd477e25a289d1be3b88e). NuGet 3.5 and newer should work.

**Comment by direstrepo24** [comment]
Thanks, in Nuget.config I solved them like this:
`
<packageSources> <add key="DotvvmFeed" value="https://www.dotvvm.com/nuget/v3/index.json" /> </packageSources> <packageSourceCredentials> <DotvvmFeed> <add key="Username" value="email@cuentaDotvvm.com" /> <add key="ClearTextPassword" value="pasword" /> </DotvvmFeed> </packageSourceCredentials>`
