### ISSUE TITLE
DotVVM Business Pack for asp.net core?

### ISSUE THREAD

**Issue by direstrepo24** [riganti/dotvvm#498]
Hi, i have "Unable to find a stable package DotVVM.BusinessPack with version" in my project asp.net core, I get an error when configuring Unable to find a stable package DotVVM.BusinessPack with version : error: Package 'DotVVM.BusinessPack' is incompatible with 'all' frameworks in project

**Comment by djanosik** [comment]
@direstrepo24 What TargetFramework do you use? BusinessPack is compatible with netstandard2.0 and net451.

**Comment by direstrepo24** [comment]
Thanks, I solved them like this:
`<packageSources>
   <add key="DotvvmFeed" value="https://www.dotvvm.com/nuget/v3/index.json" />
  </packageSources>
  <packageSourceCredentials>
    <DotvvmFeed>
        <add key="Username" value="direstrepob@hotmail.com" />
        <add key="ClearTextPassword" value="Isabella7824" />
    </DotvvmFeed>
</packageSourceCredentials>`

**Comment by djanosik** [comment]
@direstrepo24 I guess this is related to #497, isn't it? Or is the issue with target frameworks solved?
