### ISSUE TITLE
GridViewExportExcel how export excel?

### ISSUE THREAD

**Issue by direstrepo24** [riganti/dotvvm#502]
How i can export to excel?, as in the example of "Bussines Editor" in https://themes.dotvvm.com/editor, i tried:
 ````
var exporter = new  GridViewExportExcel<Customer>(new GridViewExportExcelSettings<Customer>());
            var gridView = Context.View.FindControlByClientId<DotVVM.BusinessPack.Controls.GridView>("data", true);

            using (var file = exporter.Export(gridView, Customers))
            {
                Context.ReturnFile(file, "excel.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
            }
````
but I can not find the space name "GridViewExportExcel", i have Bussinespack 
trial version. help me please?

**Comment by djanosik** [comment]
@direstrepo24 The Excel export package is not available in the trial version. I am sorry about that. Please allow me some time to see whether we can make it available for you. I will let you know soon.

**Comment by djanosik** [comment]
@direstrepo24 You should be able to install the `DotVVM.BusinessPack.Export.Excel` package including the `GridViewExportExcel` class. Please let me know how it works for you.

**Comment by direstrepo24** [comment]
Hi, get this warning: 'DotVVM.BusinessPack.Export.Excel 1.1.5-rc1' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project.

**Comment by djanosik** [comment]
Excel export depends on `System.Drawing` and requires full .NET Framework running on Windows. Your application should target `net451` or higher. It may also work on Mono, but it is not tested. 

For now, it doesn't work in xplat .NET Core application. We will definitely fix that in future releases.

**Comment by direstrepo24** [comment]
thanks, us working new project with asp.net core and i need implement with this library.

**Comment by djanosik** [comment]
I am afraid I can't help you right now. We are going to make the Excel export xplat when the EPPlus or any similar library is compatible with `System.Drawing.Common`.

**Comment by direstrepo24** [comment]
ok, thanks.

**Comment by djanosik** [comment]
@direstrepo24 Can you use CSV export instead of Excel export?

**Comment by tomasherceg** [comment]
@djanosik What about `CoreCompat.System.Drawing`?

**Comment by djanosik** [comment]
@tomasherceg I would rather not take a dependency on this library. Official cross-platform `System.Drawing` is already available on NuGet.

**Comment by direstrepo24** [comment]
the idea is generate a report in excel.  I can place in a button event of dotvvm call a function of for example Epplus or another library to export to excel? Could you give me a simple example? This is important because all applications and businesses are based on reports. thanks

**Comment by djanosik** [comment]
I am not sure I understand. You can generate the Excel file yourself with any library you want. Or you can use our CSV export for now. CSV files can also be opened in Excel.

**Comment by direstrepo24** [comment]
excuseme, what is your .cvs export, any example?

**Comment by djanosik** [comment]
It works the same way as `GridViewExportExcel`. You just need to use `GridViewExportCsv` class from the `DotVVM.BusinessPack.Export.Csv` package.
```csharp
var exporter = new GridViewExportCsv<Customer>(new GridViewExportCsvSettings<Customer> { Separator = ";" });
var gridView = Context.View.FindControlByClientId<DotVVM.BusinessPack.Controls.GridView>("data", true);

using (var file = exporter.Export(gridView, Customers))
{
    Context.ReturnFile(file, "Report.csv", "text/csv");
}
```

**Comment by direstrepo24** [comment]
Hi, have this exception:
an exception of type 'DotVVM.Framework.Controls.DotvvmControlException' occurred in DotVVM.Framework.dll but was not handled in user code: 'The control with ID 'data' was found, however it is not an instance of the desired type 'DotVVM.BusinessPack.Controls.GridView'.'
   at DotVVM.Framework.Controls.DotvvmControl.FindControlByClientId[T](String id, Boolean throwIfNotFound), my page is: `<dot:GridView ID="data" DataSource="{value: Customers}" InlineEditing="true" >` and button event is: `<dot:Button Text="Export" Click="{command: Export()}" />`

**Comment by djanosik** [comment]
You need to use `<bp:GridView ...>` in markup code instead of `<dot:GridView ...>`.

**Comment by direstrepo24** [comment]
Excuseme, i follow this example https://www.dotvvm.com/docs/controls/businesspack/GridView/latest , in the  public BusinessPackDataSet<Customer> Customers { get; set; }
but "BusinessPackDataSet" does not appear in the namespace.

**Comment by djanosik** [comment]
Yes, the docs are written for newer version than you have currently. Try to use `BpGridViewDataSet`.

**Comment by direstrepo24** [comment]
Excuseme, last question, i have excepction to load data: `'System.NullReferenceException' occurred in DotVVM.BusinessPack.Export.dll but was not handled in user code: 'Object reference not set to an instance of an object.'` this ocurred in line --->: 
` public void Export()
        {
                var exporter = new GridViewExportCsv<Customer>(new GridViewExportCsvSettings<Customer> { Separator = ";" });
                var gridView = Context.View.FindControlByClientId<DotVVM.BusinessPack.Controls.GridView>("data", true);

(exception)      --->       using (var file = exporter.Export(gridView, Customers))
                {
                    Context.ReturnFile(file, "Report.csv", "text/csv");
                }
        }`

Thanks for you helpme.

**Comment by djanosik** [comment]
Show me the stack trace. Where is the exception thrown?

**Comment by direstrepo24** [comment]
in line: using (var file = exporter.Export(gridView, Customers))

**Comment by djanosik** [comment]
I don't think it's possible. Show me the stack trace.

**Comment by direstrepo24** [comment]
excepción: CLR/System.NullReferenceException
An exception of type 'System.NullReferenceException' occurred in DotVVM.BusinessPack.Export.dll but was not handled in user code: 'Object reference not set to an instance of an object.'
   at DotVVM.BusinessPack.Export.GridViewExportBase`1.GetOrderedGridViewUserSettings(GridView gridView)
   at DotVVM.BusinessPack.Export.Csv.GridViewExportCsv`1.Export(GridView gridView, GridViewDataSet`1 dataSet)
   at electroweb.ViewModels.ViewModelCustomer.Export() in /Users/torrefuertesas/dev/electro/electroweb/ViewModels/ViewModelCustomer.cs:line 75
   at DotVVM.Framework.Binding.Expressions.CommandBindingExpression.Evaluate(DotvvmBindableObject control, DotvvmProperty property, Object[] args)
   at DotVVM.Framework.Runtime.Commands.CommandResolver.<>c__DisplayClass1_0.<GetFunction>b__0()
   at DotVVM.Framework.Hosting.DotvvmPresenter.<ExecuteCommand>d__28.MoveNext()
PROBLEMAS
SALIDA
CONSOLA DE DEPURACIÓN
TERMINAL
      Request starting HTTP/1.1 GET http://localhost:5000/dotvvmResource/globalize---/globalize---  
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 96.372ms 200 text/javascript
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 POST http://localhost:5000/___dotvvm-spa___/Elementos application/json 2696
Step into: Stepping over non-user code 'electroweb.ViewModels.Customer..ctor'
Exception thrown: 'System.NullReferenceException' in DotVVM.BusinessPack.Export.dll

**Comment by djanosik** [comment]
Can you please format the stack trace to make it readable? Or just post a screenshot?

**Comment by direstrepo24** [comment]
I use Spa page, and button "Export": 
`"  at DotVVM.BusinessPack.Export.GridViewExportBase`1.GetOrderedGridViewUserSettings(GridView gridView)\n   at DotVVM.BusinessPack.Export.Csv.GridViewExportCsv`1.Export(GridView gridView, GridViewDataSet`1 dataSet)\n   at electroweb.ViewModels.ViewModelCustomer.Export() in /Users/torrefuertesas/dev/electro/electroweb/ViewModels/ViewModelCustomer.cs:line 75\n   at lambda_method(Closure )\n   at DotVVM.Framework.Binding.Expressions.CommandBindingExpression.Evaluate(DotvvmBindableObject control, DotvvmProperty property, Object[] args)\n   at DotVVM.Framework.Runtime.Commands.CommandResolver.<>c__DisplayClass1_0.<GetFunction>b__0()\n   at DotVVM.Framework.Hosting.DotvvmPresenter.<ExecuteCommand>d__28.MoveNext()"`

**Comment by djanosik** [comment]
Try to set the `UserSettings` property on the `GridView` to a `GridViewUserSettings` instance you create in your ViewModel.

**Comment by direstrepo24** [comment]
Excuse me, do not you understand can you give me some code?

**Comment by djanosik** [comment]
It's explained in docs: https://www.dotvvm.com/docs/controls/businesspack/GridView/latest

**Comment by direstrepo24** [comment]
![image](https://user-images.githubusercontent.com/8570276/33347044-9194db9a-d45f-11e7-9462-8c2ae445fda1.png)

**Comment by djanosik** [comment]
The property is called `UserSettings`. Take a look at docs please.

**Comment by direstrepo24** [comment]
Hi, i have this error, set Usersetting, but : 
![image](https://user-images.githubusercontent.com/8570276/33348281-c95aa736-d463-11e7-8f8e-3597df8ddda1.png)

**Comment by djanosik** [comment]
https://github.com/riganti/dotvvm/issues/426

**Comment by direstrepo24** [comment]
i see this: 
![image](https://user-images.githubusercontent.com/8570276/33348425-67f5cf4c-d464-11e7-811b-71489845ae7d.png)

**Comment by djanosik** [comment]
This is probably unrelated to DotVVM or this issue. How does the stack trace look?

**Comment by direstrepo24** [comment]
![image](https://user-images.githubusercontent.com/8570276/33349241-4e7d87be-d467-11e7-89f5-d24157bdb836.png)
and : 
![image](https://user-images.githubusercontent.com/8570276/33349299-78f39970-d467-11e7-8900-a72bb9f4aa94.png)

**Comment by djanosik** [comment]
Hmm, I need stack trace of the "Timeouts are not supported on this stream." exception.

**Comment by direstrepo24** [comment]
![image](https://user-images.githubusercontent.com/8570276/33350241-c05d9d34-d46b-11e7-9a7b-283870540049.png)

**Comment by djanosik** [comment]
I can't read the stack trace, can you? But if this is where the exception is thrown, its not a problem at all. You are accessing unsupported properties in debugger. Or is it also thrown at runtime? Please, try to make it easier for me to help you.

**Comment by direstrepo24** [comment]
hi, thanks for you help, this in time execution, when click in Export, go to the viewModel this :
![image](https://user-images.githubusercontent.com/8570276/33350739-63489010-d46e-11e7-98f7-117d81b3644c.png)

**Comment by djanosik** [comment]
I've already told you the `DotvvmInterrupRequestExecutionException` should be thrown. It's not an issue. Are you able to download the returned file or not?

**Comment by direstrepo24** [comment]
no, it goes to the exception:

![image](https://user-images.githubusercontent.com/8570276/33350872-0ffcf3f0-d46f-11e7-9b4a-c5386979c79f.png)

**Comment by djanosik** [comment]
I know and it's the correct behavior. Please, turn off the debugger and try to download the file.

**Comment by direstrepo24** [comment]
but, if turn off the debugger dont run app web , i'm run in vscode in a mac ox

**Comment by djanosik** [comment]
Use `dotnet run` from command line. Or just skip the exception and continue.

**Comment by CharanSaradaSSD** [comment]
This seems to be outdated Can you provide documentation or sample code that is updated?

**Comment by mrnustik** [comment]
@CharanSaradaSSD 
Hi, 
which version of Bussiness Pack are you using? I will provide you with the sample code for the version. We are currently working on better documentation for the export but it is not ready yet.

**Comment by CharanSaradaSSD** [comment]
> @CharanSaradaSSD
> Hi,
> which version of Bussiness Pack are you using? I will provide you with the sample code for the version. We are currently working on better documentation for the export but it is not ready yet.

2.5.3

**Comment by CharanSaradaSSD** [comment]
2.5.3 This is the version I am working on

**Comment by mrnustik** [comment]
@CharanSaradaSSD 
This code should do the trick. Just put it inside of your command and it will generate the Excel file and return it to the user.

```
public class GridViewExportViewModel : DotvvmViewModelBase
{
    private readonly BindingCompilationService bindingService;

    public BusinessPackDataSet<CustomerData> CustomersDataSet { get; set; } = new BusinessPackDataSet<CustomerData>() { PagingOptions = { PageSize = 5 } };

    public GridViewExportViewModel(BindingCompilationService bindingService)
    {
         this.bindingService = bindingService;
    }

    public void Export()
    {
         var gridView = Context.View.FindControlByClientId<BusinessPack.Controls.GridView>("CustomersGridView", true);
         var gridViewExportExcel = new GridViewExportExcel<CustomerData>(bindingService);
         using (var exportStream = gridViewExportExcel.Export(gridView, customersDataSet))
         {
                  Context.ReturnFile(exportStream, "export.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
         }
     }
}
```

**Comment by mrnustik** [comment]
Just a note in the 3.0.0 version we have managed to make the Excel export much better. It provides support for all of Excel data types and extensibility points. 

Right now the 3.0.0 version is in preview, but the Excel export should be stable. We are currently working on the documentation for it so it should be available soon.

**Comment by CharanSaradaSSD** [comment]
> @CharanSaradaSSD
> This code should do the trick. Just put it inside of your command and it will generate the Excel file and return it to the user.
> 
> ```
> public class GridViewExportViewModel : DotvvmViewModelBase
> {
>     private readonly BindingCompilationService bindingService;
> 
>     public BusinessPackDataSet<CustomerData> CustomersDataSet { get; set; } = new BusinessPackDataSet<CustomerData>() { PagingOptions = { PageSize = 5 } };
> 
>     public GridViewExportViewModel(BindingCompilationService bindingService)
>     {
>          this.bindingService = bindingService;
>     }
> 
>     public void Export()
>     {
>          var gridView = Context.View.FindControlByClientId<BusinessPack.Controls.GridView>("CustomersGridView", true);
>          var gridViewExportExcel = new GridViewExportExcel<CustomerData>(bindingService);
>          using (var exportStream = gridViewExportExcel.Export(gridView, customersDataSet))
>          {
>                   Context.ReturnFile(exportStream, "export.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
>          }
>      }
> }
> ```

Seems like BusinessPack.Controls type name Controls  does not exists in Type BuisnessPack are we missing anything....

**Comment by CharanSaradaSSD** [comment]
> @CharanSaradaSSD
> This code should do the trick. Just put it inside of your command and it will generate the Excel file and return it to the user.
> 
> ```
> public class GridViewExportViewModel : DotvvmViewModelBase
> {
>     private readonly BindingCompilationService bindingService;
> 
>     public BusinessPackDataSet<CustomerData> CustomersDataSet { get; set; } = new BusinessPackDataSet<CustomerData>() { PagingOptions = { PageSize = 5 } };
> 
>     public GridViewExportViewModel(BindingCompilationService bindingService)
>     {
>          this.bindingService = bindingService;
>     }
> 
>     public void Export()
>     {
>          var gridView = Context.View.FindControlByClientId<BusinessPack.Controls.GridView>("CustomersGridView", true);
>          var gridViewExportExcel = new GridViewExportExcel<CustomerData>(bindingService);
>          using (var exportStream = gridViewExportExcel.Export(gridView, customersDataSet))
>          {
>                   Context.ReturnFile(exportStream, "export.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
>          }
>      }
> }
> ```

DotVVM.Framework.Hosting.DotvvmInterruptRequestExecutionException: 'Request interrupted: ReturnFile (export.xlsx)

Stack Trace:

   at DotvvmRequestContextExtensions.ReturnFile(IDotvvmRequestContext context, Stream stream, String fileName, String mimeType, IEnumerable`1 additionalHeaders, String attachmentDispositionType)
   at GridTest.ViewModels.GridViewTestViewModel.Export() in C:\00Source\GridTest\ViewModels\GridViewTestViewModel.cs:line 75
   at DotVVM.Framework.Binding.BindingHelper.Evaluate(ICommandBinding binding, DotvvmBindableObject control, Func`2[] args)
   at DotVVM.Framework.Runtime.Commands.CommandResolver.<>c__DisplayClass1_0.<GetFunction>b__0()
   at DotVVM.Framework.Hosting.DotvvmPresenter.<ExecuteCommand>d__29.MoveNext()

**Comment by mrnustik** [comment]
@CharanSaradaSSD This is not an error. As described in the conversation above this is an internal exception of the DotVVM framework which is used for interrupting the current request and returning the file from it. Just skip it and your exported excel file should download after.

**Comment by CharanSaradaSSD** [comment]
> @CharanSaradaSSD This is not an error. As described in the conversation above this is an internal exception of the DotVVM framework which is used for interrupting the current request and returning the file from it. Just skip it and your exported excel file should download after.

**Thanks @mrnustik  it works Do you have a similar way by any chance for CSV, word and Pdf.**

**For csv I used**
 public void ExportCSV()
        {
            var gridView = Context.View.FindControlByClientId<DotVVM.BusinessPack.Controls.GridView>("CustomersGridView", true);
            var gridViewExport = new GridViewExportCsv<Customer>(bindingService, new GridViewExportCsvSettings<Customer> { Separator = ";" });
            using (var exportStream = gridViewExport.Export(gridView, Customers))
            {
                Context.ReturnFile(exportStream, "export.csv", "text/csv");
            }
        }
**I am ending up with exception**
   at DotVVM.BusinessPack.Export.Csv.GridViewExportCsv`1.<PrepareLineData>b__6_0(String d)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.String.Join(String separator, IEnumerable`1 values)
   at DotVVM.BusinessPack.Export.Csv.GridViewExportCsv`1.CreateLine(IEnumerable`1 lineData)
   at DotVVM.BusinessPack.Export.Csv.GridViewExportCsv`1.CreateHeader(GridView gridView, List`1 getGridViewColumnSettings)
   at DotVVM.BusinessPack.Export.Csv.GridViewExportCsv`1.Export(GridView gridView, IBusinessPackDataSet`1 dataSet)
   at GridTest.ViewModels.GridViewTestViewModel.ExportCSV() in C:\00Source\GridTest\ViewModels\GridViewTestViewModel.cs:line 79

**Thanks for your Prompt reply...**

**Comment by mrnustik** [comment]
@CharanSaradaSSD 
Can you please also provide me with the message and type of the thrown Exception? I will look into it.

**Comment by CharanSaradaSSD** [comment]
> @CharanSaradaSSD
> Can you please also provide me with the message and type of the thrown Exception? I will look into it.

System.NullReferenceExceptionObject reference not set to an instance of an object.


@line   **var exportStream = gridViewExport.Export(gridView, Customers**

**Comment by CharanSaradaSSD** [comment]
> @CharanSaradaSSD This is not an error. As described in the conversation above this is an internal exception of the DotVVM framework which is used for interrupting the current request and returning the file from it. Just skip it and your exported excel file should download after.

We found our own ways to get the grid data but this exception at return file from context is not allowing us to do another operation with an error "Postback interrupted". Please let us know if have an option to come out of it.
![image](https://user-images.githubusercontent.com/83955913/120430086-1c29a700-c394-11eb-987b-7a0ce0736fd4.png)
