### ISSUE TITLE
Validation doesn't work when Target is a Collection

### ISSUE THREAD

**Issue by adamjez** [riganti/dotvvm#508]
When I bind Validation.Target to a **Collection** in a ViewModel, client validation ignores the collection entirely, however, server validation yields errors correctly.

Objects in the collection have the following shape:
```C#
public class PersonalDataDTO
{
    [Required(ErrorMessage = "I am required")]
    public string Name { get; set; }
}
```
The interesting is that every next client validation fails quietly (ValidationSummary doesn't show anything).

IMHO we are dealing with 2 different bugs:
* One is the lack of support for arrays in client validation
* Second is connected to the `dotvvm.validation.errors` array in dotvvm js: 
    * It contains errors that should have been cleared before the postback

Thanks to @ENgateman and @exyi for advice with this bug.

**Comment by tomasherceg** [comment]
We should add at least some error message here - currently, it just fails on postback and writes an error in the console.
Also, it would be nice to catch this on the view compilation so the extension could catch it, but since it is an attached property, I am not sure if it is possible.

**Comment by acizmarik** [comment]
Collection as validation target seems to be working already (probably since DotVVM 4.0). However, when user specifies a value type, for example a `DateTime` as a validation target, a weird JS error is produced. This should be fixed
