### ISSUE TITLE
cannot be tracked GridView edit

### ISSUE THREAD

**Issue by direstrepo24** [riganti/dotvvm#510]
hi, when intent edit my entity, say that no because another instance with the same key value for {'Id'} is already being tracked, i used asp.net core and DotVMM gridView, already inject my repositoy class, and return ok the list in GridView, but no can edit, How make this action?

pd: i use this example: https://www.dotvvm.com/docs/controls/businesspack/GridView/latest

**Comment by tomasherceg** [comment]
Are you using Entity Framework entities in the GridView? You shouldn't do it.

You should convert the entities to DTOs (data transfer objects) - plain C# objects with no relation to Entity Framework, only with the columns you actually need. You can use AutoMapper to convert between entities and DTOs.

**Comment by direstrepo24** [comment]
Yes i used Entity Framework entities, I will try with automapper and I will be informing you if it worked. Thanks

**Comment by direstrepo24** [comment]
Excuseme your hava any example automapper with DotnetVVM ?

**Comment by quigamdev** [comment]
You can check out https://github.com/riganti/dotvvm-samples-northwind 

Class NorthwindStore.App.Installers.AutoMapperInstaller contains registration of automapper. There is used IOC/DI container which you probably do not need. But the principe is same. 

The main thing you need is just this piece of code.
```
Mapper.Initialize(mapper=>{

     mapper.CreateMap<FromEntity, ToDTO>();
     mapper.CreateMap<FromDTO, ToEntity>();

}); 
```
Just make sure that automapper initialization is called at Startup.ConfigureServices.

**Comment by direstrepo24** [comment]
Hi, this is my code, i use Automapper and I was able to obtain the elements in gridview, but there is a problem to edit, 
` public void EditEmpresa(EmpresaDto empresa)
        {
            Empresas.RowEditOptions.EditRowId = empresa.Id;
            IsEditing = true;
        }

        public void UpdateEmpresa(EmpresaDto empresa)
        {
             var modeledit= _IEmpresaRepository.GetSingleAsync(m=>m.Id==empresa.Id).Result;
            
           //context.Empresa.Update(empresaedit);
            var model = _mapper.Map<EmpresaDto, Empresa>(empresa);
           if(modeledit!=null){
             
                modeledit.Nit=empresa.Nit;
                modeledit.Nombre=empresa.Nombre;
                modeledit.Telefono=empresa.Telefono;
                modeledit.Direccion=empresa.Direccion;
               // lecturaedit.Id=id;*/
                 _IEmpresaRepository.EditAsync(model);
               
                }
            CancelEdit();
        }`
This is the error: " The connection is already in state 'Executing'", please helpme, thanks

**Comment by tomasherceg** [comment]
I don't know what the repository does, the error is coming from there, but I suspect that you are calling async methods without await.

**Comment by direstrepo24** [comment]
this error: The instance of entity type 'Empresa' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.
my code is: `public async Task<EmpresaDto> getEmpresa(EmpresaDto empresa){
         
            
            var modeedit=await _IEmpresaRepository.GetSingleAsync(m=>m.Id==empresa.Id);
            var model = _mapper.Map<Empresa, EmpresaDto>(modeedit);
            return model;
        }
        public async Task UpdateEmpresa(EmpresaDto empresa)
        {
            var modeledit =await getEmpresa(empresa);
     
           if(modeledit!=null){
             
                modeledit.Nit=empresa.Nit;
                modeledit.Nombre=empresa.Nombre;
                modeledit.Telefono=empresa.Telefono;
                modeledit.Direccion=empresa.Direccion;
               // lecturaedit.Id=id;*/
               var model = _mapper.Map<EmpresaDto, Empresa>(modeledit);
               await  _IEmpresaRepository.EditAsync(model);
               
                }
            CancelEdit();
        }`

**Comment by tomasherceg** [comment]
You cannot have two objects with the same Id in Entity Framework. You need to map the DTO to existing entity - Mapper.Map(dto, entity) should do the trick.

**Comment by direstrepo24** [comment]
Ok, already works, the problem is that now when exporting: `public void Export()
        {
                     var exporter = new GridViewExportCsv<EmpresaDto>(new GridViewExportCsvSettings<EmpresaDto> { Separator = ";" });
                var gridView = Context.View.FindControlByClientId<DotVVM.BusinessPack.Controls.GridView>("data", true);
               
  EXCEPTION---> HERE   using (var file = exporter.Export(gridView,  Empresas))
                {
                    Context.ReturnFile(file, "Report.csv", "text/csv");
                //Context.ReturnFile(file, "export.pdf", "application/pdf");
                }
        }`

How i can mapper this?

**Comment by direstrepo24** [comment]
already works, but having another column without data does not allow export:
` <bp:GridViewTemplateColumn ColumnName="Edit">
            <ContentTemplate>
                <dot:Button Text="Edit" Click="{command: _parent.EditEmpresa(_this)}"/>
            </ContentTemplate>
            <EditTemplate>
                <dot:Button Text="Save" Click="{command: _parent.UpdateEmpresa(_this)}"/>
                <dot:Button Text="Cancel" Click="{command: _parent.CancelEditEmpresa()}"/>
            </EditTemplate>
        </bp:GridViewTemplateColumn>`

**Comment by quigamdev** [comment]
Closing this issue, because it is not an issue in dotvvm. For discussion please use gitter or stackoverflow.
