### ISSUE TITLE
DotVVM js files minification 

### ISSUE THREAD

**Issue by adamjez** [riganti/dotvvm#512]
DotVVM is serving **not minified** js files even when `Debug` option is set to **false**. Is there any good reason to not minify these files (specifically `DotVVM.js`)?

I minified some files to find out file size difference between **minified** / not minified files:
* `DotVVM.js`: **52KB** / 125KB
* `DotVVM.Bootstrap.js`: **27KB** / 59KB

**Comment by exyi** [comment]
> Is there any good reason to not minify these files (specifically
> `DotVVM.js`)?
Yes, noone did that...

If you want, you can try to setup a JS minifier and compile put files
into the embedded resource. For debug purposes, there is registered a
direct path to the Dotvvm.js file on a file system, so you don't have
to worry about that.
