### ISSUE TITLE
Call a controller 

### ISSUE THREAD

**Issue by direstrepo24** [riganti/dotvvm#518]
Hi, i have a controller in asp.net core that export to pdf, this manner:
` [HttpGet]
        [Route("/exportpdf")]
        public async Task<IActionResult> ExportPdf([FromServices] INodeServices nodeServices)
        {
            HttpClient hc = new HttpClient();
            var htmlContent = await hc.GetStringAsync($"http://{Request.Host}/report.html");

            var result = await nodeServices.InvokeAsync<byte[]>("./Node/pdf", htmlContent);

            HttpContext.Response.ContentType = "application/pdf";
            
            HttpContext.Response.Headers.Add("x-filename", "report.pdf");
            HttpContext.Response.Headers.Add("Access-Control-Expose-Headers", "x-filename");
            HttpContext.Response.Body.Write(result, 0, result.Length);
            return new ContentResult();
        }`
How call this with button from the viweModel in dotVVM? thanks

**Comment by exyi** [comment]
> You don't need button - you can just link to the URL of the web API - <a href="/exportpdf">, or you can redirect to the URL.
As @tomasherceg responded on gitter.
