### ISSUE TITLE
Server Error, HTTP 500: Unhandled exception occured

### ISSUE THREAD

**Issue by Dio313Dio** [riganti/dotvvm#522]
DotVVM Debugger: Error 500: Internal Server Error, Server Error, HTTP 500: Unhandled exception occurred.
when i click add order item on your OrderManagementApp sample.

i just download dotvvm and i want to explore your framework but i have problem running your demo samples both the OrderManagementApp sample and the dotvvm-samples-northwind-master that won't build on my visual studio.
i will appreciate if you can tell me a way around this issues.

**Comment by tomasherceg** [comment]
Is there more details in the error message?

**Comment by Dio313Dio** [comment]
**DotVVM Debugger: Error 500: Internal Server Error**

Server Error, HTTP 500: Unhandled exception occured
System.Exception: Unhandled exception occured in the command!


System.InvalidOperationExceptionSequence contains no elements
> { ... }
System.Linq.Enumerable.First<TSource>(IEnumerable`1 source)
OrderManagementApp.ViewModels.OrderDetailViewModel.AddOrderItem() C:\Dio\Learn\dotvvm-samples-order-management-master\src\OrderManagementApp\ViewModels\OrderDetailViewModel.cs +60
60: 	        EditedOrder.OrderItems.Add(new OrderItemDetailDTO()
Source File: C:\Dio\Learn\dotvvm-samples-order-management-master\src\OrderManagementApp\ViewModels\OrderDetailViewModel.cs
lambda_method(Closure )
DotVVM.Framework.Binding.Expressions.CommandBindingExpression.Evaluate(DotvvmBindableObject control, DotvvmProperty property, Object[] args) 
DotVVM.Framework.Runtime.Commands.CommandResolver+<>c__DisplayClass1_0.<GetFunction>b__0() 
DotVVM.Framework.Hosting.DotvvmPresenter+<ExecuteCommand>d__28.MoveNext() 
System.ExceptionUnhandled exception occured in the command!
> { ... }
DotVVM.Framework.Hosting.DotvvmPresenter+<ExecuteCommand>d__28.MoveNext() 
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() 
DotVVM.Framework.Hosting.DotvvmPresenter+<ProcessRequestCore>d__26.MoveNext() 
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
DotVVM.Framework.Hosting.DotvvmPresenter+<ProcessRequestCore>d__26.MoveNext() 
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
DotVVM.Framework.Hosting.DotvvmPresenter+<ProcessRequest>d__25.MoveNext() 
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
DotVVM.Framework.Hosting.Middlewares.DotvvmRoutingMiddleware+<Handle>d__3.MoveNext() 
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
DotVVM.Framework.Hosting.Middlewares.DotvvmRoutingMiddleware+<Handle>d__3.MoveNext() 
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() 
DotVVM.Framework.Hosting.DotvvmMiddleware+<Invoke>d__5.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
DotVVM.Framework.Hosting.Middlewares.DotvvmErrorPageMiddleware+<Invoke>d__6.MoveNext()

**Comment by exyi** [comment]
That's obviously a bug in your viewmodel, you are calling `First` on an empty collection in method `AddOrderItem`.

**Comment by tomasherceg** [comment]
@exyi I think this is our sample app: https://github.com/riganti/dotvvm-samples-order-management

It looks like there is nothing in the Products table in the database, that's why the page is crashing. I'll fix this.
