### ISSUE TITLE
Always add defer attribute to script resources

### ISSUE THREAD

**Issue by symbiogenesis** [riganti/dotvvm#528]
As suggested by exyi in this [comment](https://github.com/riganti/dotvvm/pull/464#issuecomment-354357901)

This may offer some performance wins at almost no cost, and at minimum may improve Google PageSpeed rankings for DotVVM sites.

This should be the default behavior, but we could also offer a way to toggle this off.

**Comment by exyi** [comment]
I totally agree, maybe we could also try using `<link rel="preload" ...` for faster resource loads.

**Comment by exyi** [comment]
This is basically resolved by #614
