### ISSUE TITLE
BusinessPack MultiSelect keypress timer

### ISSUE THREAD

**Issue by filipveskrna** [riganti/dotvvm#532]
Hello everybody,
I've just experienced a weird behavior of the **MultiSelect** control from **DotVVM BusinessPack**. It is not a regular bug, but my personal user experience with the control is bad. _Usecase_ is as following:
1. I have a collection of Tags added in the past and I want add a new one.
2. So I write a new Tag as a new element and I press enter.
3. If the time between pressing the last character of the Tag and pressing the Enter key afterward is lower by approx 200 ms the new Tag is not added and it just behaves completely unexpectedly. 
4. If the action described in the 3. part is done repeatively then every second Tag is not added to the list.

The issue is depicted on the following image:
![image](https://user-images.githubusercontent.com/19222006/34919034-c8f0cb12-f95d-11e7-94b3-bd6f9b85c75c.png)

DotVMM version: 1.1.9-pre01

Thanks for your reply.
Regards, Filip

**Comment by djanosik** [comment]
@filipveskrna Yes, I know about this issue. I think it works as expected but we should definitely improve UX.

**Comment by djanosik** [comment]
I've made some changes to improve searching behavior in BP v1.1.10.
