### ISSUE TITLE
AddBusinessPackConfiguration method not found.

### ISSUE THREAD

**Issue by ronnieoverby** [riganti/dotvvm#533]
I'm following these instructions: https://www.dotvvm.com/docs/tutorials/commercial-business-pack-install/latest

Calling `config.AddBusinessPackConfiguration();`, I get an error.

> Error	CS1061	'DotvvmConfiguration' does not contain a definition for 'AddBusinessPackConfiguration' and no extension method 'AddBusinessPackConfiguration' accepting a first argument of type 'DotvvmConfiguration' could be found (are you missing a using directive or an assembly reference?)	

I've checked in every namespace in all `dotvvm` assemblies. Where is this method?

![image](https://user-images.githubusercontent.com/101028/35054067-c08aa7d6-fb79-11e7-98a4-b0dc6c59b2ac.png)

**Comment by djanosik** [comment]
You need to install `DotVVM.BusinessPack` package. The `Core` package only contains some common types.

**Comment by ronnieoverby** [comment]
I see. So, I was expecting to see it in the private feed, but it's not showing up. According to the site I can get trials for VS plugin and business pack. But I don't seem to have the license for the business pack. I wonder how to get that?

**Comment by PolywickStudio** [comment]
There isn't any trial. You have to buy ... :/

**Comment by ronnieoverby** [comment]
![image](https://user-images.githubusercontent.com/101028/35439237-e5e0c890-0267-11e8-8073-5356358d8c5b.png)

**Comment by tomasherceg** [comment]
Sorry about that, we will fix the issue.

**Comment by tomasherceg** [comment]
@ronnieoverby Fixed, the beta program should be working again.
We will deliver trial for both Bootstrap and Business Pack controls soon.

**Comment by ronnieoverby** [comment]
A trial for business pack would be a big win. Dotvvm is compelling, but I'm not willing to recommend our company shell out for multiple dev licenses without being able to try business/bootstrap.
