### ISSUE TITLE
Please add a menu-option.

### ISSUE THREAD

**Issue by PolywickStudio** [riganti/dotvvm#536]
Now you can use F7 and Shift-F7 to switch from the markup to the code and back.

I have tried several keyboard schemes, Visual C++ 6, Visual Basic 6, Default.

Please add a menu-option. This doesn't work.

**Comment by djanosik** [comment]
@PolywickStudio What version of DotVVM package do you use? What verison of DotVVM VS Extension? Are there any errors in .dothtml editor?

**Comment by adamjez** [comment]
In Visual studio you can go to `Options > Environment > Keyboard` to change shortcut settings. Commands which corresponds with switching from the markup to the code an back are:
* `View.ViewCode`
* `View.ViewDesigner`

**Comment by tomasherceg** [comment]
The menu options are present in Visual Studio and they are working on my machine. 
Can you please try them?

![image](https://user-images.githubusercontent.com/5599524/35448710-5bdd8a44-02bb-11e8-9f7b-684512b164f9.png)

**Comment by PolywickStudio** [comment]
I see it now... it doesn't do anything (or maybe it does something but maybe not what I expect it to do.)

**Comment by exyi** [comment]
I'm pretty sure that this is basically the same problem as all other reported problems with VS Extension - it is simply completely broken for some reason. Closing it as a duplicate of #537
