### ISSUE TITLE
Licensing mix-up? Trial and commecial

### ISSUE THREAD

**Issue by PolywickStudio** [riganti/dotvvm#537]
Please see attached.

I am unsure if the Intellisense works?

![Uploading c1.PNG…]()

I have a trial and brought a business pack license. There seems to be licensing mix-up?

**Comment by exyi** [comment]
Note that the uploaded image does not work.

Anyway, BussinessPack and VS Extension licenses should not interfere in any way and there should be no difference between trial and bought VS Extension license. It is probably a bug in the Extension, but we probably can't reproduce that without more info. Could you please share steps to reproduce the issue?

**Comment by PolywickStudio** [comment]
![c1](https://user-images.githubusercontent.com/8903532/35407208-287cbadc-0246-11e8-9a15-d64c70c32c9b.PNG)

**Comment by quigamdev** [comment]
Is this problem even in version 1.1.86.0?

**Comment by quigamdev** [comment]
If the problem persists, feel free to re-open this issue.
