### ISSUE TITLE
Allow Trial of Bootstrap and Business Pack, and get rid of license-mixing.

### ISSUE THREAD

**Issue by PolywickStudio** [riganti/dotvvm#538]
1) Please allow businesses to trial Bootstrap and Business Pack.
There seems to be no way to do so.

2) While is trial, I purchased DotVVM for VS (Pro) and it still says trial.
Get rid of it. It's confusing. Extended intellsense doesn't work (or not sure?) and F7 doesn't work.

**Comment by tomasherceg** [comment]
1. We are working on providing the trial versions of all of our products. 

2. When you buy the professional version and have active trial, the license starts immediately after the trial ends so you won't lose the remaining days of the trial.
The trial should have exactly same features as the professional license, so if the IntelliSense doesn't work, the issue will be somewhere else. 

I have contacted you via e-mail - would you be able to have a Skype call with us so we can look what's wrong with the extension?

**Comment by PolywickStudio** [comment]
2. I didn't receive any email. Did you get my chat message - it contains my Skype ID.

**Comment by tomasherceg** [comment]
Can you please try to delete all files in the directory `%localappdata%\Riganti\DotVVM\` and restart Visual Studio? The extension should display the welcome window and allow you to sign in again.
