### ISSUE TITLE
Use-case error: How to install DotVVM Bootstrap into an existing project?

### ISSUE THREAD

**Issue by PolywickStudio** [riganti/dotvvm#539]
How do you install DotVVM Bootstrap to an existing project?

There doesn't seem to be any way to.

**Comment by exyi** [comment]
Add it as a Nuget package. Note that it's not on the public NuGet feed, you'll have to add the dotvvm private feed. https://www.dotvvm.com/docs/tutorials/commercial-dotvvm-private-nuget-feed/latest

**Comment by PolywickStudio** [comment]
I did. Your instructions say:
https://www.dotvvm.com/docs/tutorials/commercial-bootstrap-for-dotvvm/latest

Install-Package Bootstrap

What's the command to obtain private-feed dot-vvm bootstrap?

**Comment by djanosik** [comment]
@PolywickStudio Did you check the previous [link](https://www.dotvvm.com/docs/tutorials/commercial-dotvvm-private-nuget-feed/latest)? It's explained there.

**Comment by djanosik** [comment]
@PolywickStudio You can use NuGet package manager to find the package manually. Or you can try:
```
Install-Package DotVVM.Controls.Bootstrap
```
