### ISSUE TITLE
Install Bootstrap - installs BS4, DotVVM Bootstrap uses BS3.

### ISSUE THREAD

**Issue by PolywickStudio** [riganti/dotvvm#540]
Please kindly give instructions...

https://www.dotvvm.com/docs/tutorials/commercial-bootstrap-for-dotvvm/latest

This uses BS4, the NuGet updates the project to BS4.

**Comment by tomasherceg** [comment]
Thank you for the report, Nuget adds the latest version of Bootstrap automatically. 
For now, you need to manually downgrade the Bootstrap package to 3.3.7. 

The issue will be fixed in the next release of Bootstrap for DotVVM.

**Comment by PolywickStudio** [comment]
![error](https://user-images.githubusercontent.com/8903532/35442326-d2382a48-02e1-11e8-806b-e778de3ee408.PNG)

Please fix. I'm using your bootstrap-dotvvm which has no trial.

There seems to be errors due to BS3/BS4 alpha on distribution.

**Comment by tomasherceg** [comment]
You need to right-click the project, select Manage Nuget Packages, go to the Installed tab and change the version of Bootstrap package to latest 3.x.x release.

**Comment by PolywickStudio** [comment]
I did. I changed it to bs3 release now.

**Comment by exyi** [comment]
Docs are fixed by riganti/dotvvm-docs@ddec0c9874a1ee3fd95770b965e8bbd9e83cd27f
