### ISSUE TITLE
BusinessPack.css downloads zero-byte CSS

### ISSUE THREAD

**Issue by PolywickStudio** [riganti/dotvvm#541]
![zero](https://user-images.githubusercontent.com/8903532/35442782-6ba2384e-02e3-11e8-8ff8-dc499f427862.PNG)

i'm trying the theme editor and it returns zero byte CSS

**Comment by tomasherceg** [comment]
What is the version of your browser?

**Comment by exyi** [comment]
> What is the version of your browser?

Tomas, have you tried that? It does not work in the latest Chrome.
What's worse, this is probably a known and *fixed* bug from 11/18/17.
Just noone deployed the fixed version...

**Comment by PolywickStudio** [comment]
I'm using Firefox (latest)

**Comment by quigamdev** [comment]
@PolywickStudio Please try it again. I have published bugfix.

**Comment by PolywickStudio** [comment]
it works now.
