### ISSUE TITLE
How to add DotVVM-boostrap to an existing project?

### ISSUE THREAD

**Issue by PolywickStudio** [riganti/dotvvm#543]
How do you add dot-vvm to an existing DotVVM project?

There is no instruction to add to existing.

The only way how is File > New Project > Wizard > [x] DotVVM Bootstrap.

**Comment by djanosik** [comment]
Closing as duplicate of #539.

**Comment by djanosik** [comment]
@PolywickStudio Please take a look at instructions in #539 .
