### ISSUE TITLE
intellisense for Business Pack, bootstrap not working

### ISSUE THREAD

**Issue by PolywickStudio** [riganti/dotvvm#544]
Hi,
I created new project, pressed Ctrl+Space in editor, there is no bsp:, no bs: on drop-down list.

Any ideas how to fix intellisense error?

I am editing dothtml page. I am trying to get intellisense to work.

**Comment by djanosik** [comment]
Take a look at #365. Does it help?

**Comment by PolywickStudio** [comment]
please see #365 - closing duplicate.
