### ISSUE TITLE
Request for live demos what it looks like

### ISSUE THREAD

**Issue by PolywickStudio** [riganti/dotvvm#545]
https://www.dotvvm.com/docs/controls/businesspack/GridView/latest

Can you provide screenshots of what the grid looks like after adding code.

The docs are empty on that regard.

**Comment by quigamdev** [comment]
Hello, I would like to let you know about a progress of this issue. 
We are preparing new live samples of Business Pack components and new docs for version 2.0. 
It should be release shortly after DotVVM 2.0.
