### ISSUE TITLE
Sort, Filter available for BS grid?

### ISSUE THREAD

**Issue by PolywickStudio** [riganti/dotvvm#546]
1. Please provide more info on sorting features for the BS grid.
https://www.dotvvm.com/docs/controls/bootstrap/GridView/latest

2. Please make example of BS Grid + Pager.

**Comment by tomasherceg** [comment]
The features of Bootstrap `GridView` and `DataPager` are basically the same as the features of the built-in controls, you can refer to the examples from the following pages:

https://www.dotvvm.com/docs/controls/builtin/GridView/latest
https://www.dotvvm.com/docs/controls/builtin/DataPager/latest

**Comment by PolywickStudio** [comment]
I think you should put that in the docs...

**Comment by tomasherceg** [comment]
Moving to our internal issue tracker (taskpool for DotVVM docs) and closing.
