### ISSUE TITLE
CodeMirror example

### ISSUE THREAD

**Issue by PolywickStudio** [riganti/dotvvm#547]
Please make example or demo for integrating DotVVM with CodeMirror.
https://codemirror.net/

**Comment by exyi** [comment]
We already have quite a few samples of custom controls, have a look at https://github.com/riganti/dotvvm-contrib/. Hovewer, we simply can't make a wrapper for anything you'd like, I'm sorry. Anyway, if you'd have any concrete problem with writing the dotvvm control, of course, feel free to ask.
