### ISSUE TITLE
Bootstrap sticky footer doesn't stick.

### ISSUE THREAD

**Issue by PolywickStudio** [riganti/dotvvm#548]
Example:
https://codepen.io/ondrejsvestka/pen/gWavOv
/bootstrap/bootstrap-4.0.0/docs/4.0/examples/sticky-footer-navbar/index.html

![test1](https://user-images.githubusercontent.com/8903532/35471403-707ee828-0395-11e8-9d0a-555c56f5662e.PNG)

Sticky footer doesn't work with feature. "dot:Content".

<dot:Content ContentPlaceHolderID="Main">
</dot:Content>

Can you post an example host to force the BS footer to stick to the bottom.

**Comment by adamjez** [comment]
It looks like that it's not bug in DotVVM. If you think so, please describe the issue more. 
Otherwise, please use the [gitter](https://gitter.im/riganti/dotvvm) to solve your problem.
