### ISSUE TITLE
How data-pager works?

### ISSUE THREAD

**Issue by PolywickStudio** [riganti/dotvvm#549]
https://www.dotvvm.com/docs/controls/builtin/DataPager/latest

How does data-pager work?
If you put grid with 500 items the data-pager does not work..., it shows 500 items as is.

**Comment by PolywickStudio** [comment]
Also, update Customers.PageSize - it gives warning it's obsolete.

Customers.PagingOptions.PageSize = 10;

**Comment by PolywickStudio** [comment]
This doesn't work either - 
https://www.dotvvm.com/docs/controls/businesspack/DataPager/latest

The Customers.PagingOptions.PageSize = 10; feature doesn't work.

If you have 100 items, the data-pager does not generate anything...

**Comment by PolywickStudio** [comment]
There is a bug. First time, it shows all the item list. If I click the data-page, then it works.

So... you need to make the data-pager force to work on page load.

**Comment by PolywickStudio** [comment]
I think I need help... Data-page doesn't work.

**Comment by exyi** [comment]
I'm sorry, but I can't help you without any more details. This simply works for me. You can have a look at https://github.com/riganti/dotvvm/blob/master/src/DotVVM.Samples.Common/Views/ControlSamples/GridView/GridViewPagingSorting.dothtml for a more complete example.

I think that you have some error in the data loading, are you sure that when the data is loaded, the page size is already set?
