### ISSUE TITLE
Value Binding fails, if a property name equlas the enum name

### ISSUE THREAD

**Issue by damjik** [riganti/dotvvm#557]
Value Binding fails, if a property name is similar to the enum name (v1.1.8.2). Maybe give a hint in the [docu](https://www.dotvvm.com/docs/tutorials/basics-value-binding/latest) or make this safe.

Example:
`public enum UploadType { Pdf, Image }`

.dothtml contains @import Namespace.To

Will FAIL:
Visible="{value: UploadType == UploadType.Image ? true : false}"

OK:
Visible="{value: UT == UploadType.Image ? true : false}"
Visible="{value: UploadType == Namespace.To.UploadType.Image ? true : false}"

**Comment by exyi** [comment]
On Wed, 2018-02-07 at 04:59 -0800, damjik wrote:
> Value Binding fails, if a property name is similar to the enum name.
> Maybe give a hint in the
> [docu](https://www.dotvvm.com/docs/tutorials/basics-value-
> binding/latest)

It feels totally intuitive to me and we probably don't want to pollute
the docs with a list of extreme cases nor a formal specification of the
language semantics.

> or make this safe.

This is IMO safer than implementing "strange rules" to support name
conflicts.

I know that C# has some magic rules to mitigate these problems, but 1.
I don't want to implement it, 2. it breaks the simple intuition behind
the semantic model of the language. F#, for example, does not implement
anything like that, so it behaves almost exactly the same as dotvvm
bindings in this situation.

**Comment by exyi** [comment]
I'm sorry, but are probably not going to support these "name conflicts". We want to keep the binding language as simple (and useful) as possible, I believe that this is just a slight inconvenience, that it's pretty easy to understand what is wrong and how to fix the problem.
