### ISSUE TITLE
Optimize away redundant control-tree initializations

### ISSUE THREAD

**Issue by exyi** [riganti/dotvvm#559]
* Repeater and GridView initialize the content two times (Load and PreRender) even though the collection has not changed.
* Repeater and GridView initialize the full content even when they are in client-side rendering mode. This is probably required for postback, but certainly not page loads.
* The entire control-tree is initialized on every Postback, which usually pretty useless. Unfortunatelly it seems to be quite tricky to determine when it's going to be useless and when not.

Although the control tree initialization does not seem to be a huge bottleneck the subsequent operations like LifecycleEvent and tree walking to find command are pretty expansive.

**Comment by tomasherceg** [comment]
I remember that we've added memoization in the `Repeater` recently. 
Is there anything else that you think is reasonable to do?

**Comment by exyi** [comment]
Part of the issue is solved by memoization, the other part will be tracked in #1073
