### ISSUE TITLE
 System.MissingMethodException on blank DotVVM project.

### ISSUE THREAD

**Issue by JustinMinnaar** [riganti/dotvvm#560]
I created a new DotVVM sample project.
I changed the default connection string to use my local SQL server and database.
I ran the program and received this error. 
I upgraded all NuGet packages and the error persisted. 
I was surprised to receive this on a new sample project and hope it can be resolved.

System.MissingMethodException
  HResult=0x80131513
  Message=Method not found: 'System.IServiceProvider Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(Microsoft.Extensions.DependencyInjection.IServiceCollection)'.
  Source=DotVVM.Framework
  StackTrace:
   at DotVVM.Framework.Configuration.ServiceLocator.BuildServiceProvider()
   at Owin.AppBuilderExtensions.UseDotVVM(IAppBuilder app, String applicationRootPath, Boolean useErrorPages, Boolean debug, Action`1 options)
   at Owin.AppBuilderExtensions.UseDotVVM[TStartup](IAppBuilder app, String applicationRootPath, Boolean useErrorPages, Boolean debug, Action`1 options)
   at DotvvmApplication1.Startup.Configuration(IAppBuilder app) in C:\repos\DotvvmApplication1\DotvvmApplication1\Startup.cs:line 29

**Comment by djanosik** [comment]
Can you check what libs are actually referenced? Because it looks like your app runs against some old binaries.

**Comment by quigamdev** [comment]
DotVVM on full .NETFramework requires dlls in this versions: 
```
Microsoft.Extensions.DependencyInjection (>= 1.0.0)
Microsoft.Extensions.Options (>= 1.0.0)
```
The method `System.IServiceProvider Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(Microsoft.Extensions.DependencyInjection.IServiceCollection)` is missing in Microsoft.Extensions.DependencyInjection version 2.0.0. 

Please check you reference assemblies for version 1.0.0.

We fixed the project template and will be released with next version of DotVVM for Visual Studio (extension for VS).

**Comment by quigamdev** [comment]
Fix already released.
