### ISSUE TITLE
Not rendering DOM element using Visible property

### ISSUE THREAD

**Issue by marthrusk** [riganti/dotvvm#562]
Is it possible in DotVVM to not render some DOM elements in html page when using Visible attribute? Right now it just adds css style 'Display: none;', but I am not sure if this is good aproach, Isn't it much better to not render it at all?  For example, when I use button component and got Visible property of this component binded to bool property in my vm, but no matter what, it will always be in rendered page.

**Comment by djanosik** [comment]
It's possible in DotVVM 2.0. See https://github.com/riganti/dotvvm/issues/215.
