### ISSUE TITLE
Async commands?

### ISSUE THREAD

**Issue by naasking** [riganti/dotvvm#564]
I'm working through a prototype using DotVVM, and I think I have a handle on the lifecycle via async Init/Load/Post, but it seems strange that commands can't be async.

For instance, [your samples have save commands that write to a database](https://github.com/riganti/dotvvm-samples-checkbook/blob/master/src/CheckBook.App/ViewModels/PaymentViewModel.cs#L178), which presumably would take just as long as the init/load commands that read from the database. This a perfect application of async for improved scaling, so even though most commands perhaps don't need async support, this seems like an important use case.

**Comment by tomasherceg** [comment]
Async commands work - any method you are calling with command binding can be `async Task` and it will work. We weren't using this in most of our samples as we didn't want to complicate things.

I have also checked the documentation and there is a mention about that. https://www.dotvvm.com/docs/tutorials/basics-command-binding/latest

**Comment by naasking** [comment]
Thanks, I was mainly perusing the docs for Button which doesn't mention this.

**Comment by tomasherceg** [comment]
Thanks for the feedback, we should add this there too.
