### ISSUE TITLE
Documentation lacks links, packages and/or namespaces

### ISSUE THREAD

**Issue by naasking** [riganti/dotvvm#567]
Just working through a basic setup and the documentation is a little frustrating. For instance, the [authentication docs](https://www.dotvvm.com/docs/tutorials/advanced-aspnetcore-authentication/latest) mention DotvvmAuthenticationHelper but I have no idea where that is.

I found this class under the source code for a project titled "DotVVM.Framework.Hosting.AspNetCore". Of course, there's no nuget package for that, it's instead inside a package named DotVVM.AspNetCore.

Nowhere that I can see are any of the AspNetCore or Owin packages or their namespaces mentioned in the discussion of authentication, nor are links to the nuget packages that are needed mentioned.

**Comment by tomasherceg** [comment]
Thank you for the feedback - we are aware of this issue. In the upcoming weeks, we will review the entire documentation and prepare it for DotVVM 2.0. 
During this process, I will make sure all namespaces and Nuget packages are listed there.

**Comment by acizmarik** [comment]
Documentation has been revised and updated. However, if there are further issues feel free to open a new issue.
