### ISSUE TITLE
Null reference exception in CollapsiblePanel binding (within repeater)

### ISSUE THREAD

**Issue by martinsura** [riganti/dotvvm#571]
Hello,

I found bug in CollapsiblePanel (bootstrap) binding.

`
<dot:Repeater DataSource="{value: Model.Collection}">
    <ItemTemplate>
      <bs:CollapsiblePanel IsCollapsed="{value: Item != null}">
        <HeaderTemplate>
...
        </HeaderTemplate>
        <ContentTemplate>
..
        </ContentTemplate>
        <AdditionalContentTemplate>
...
        </AdditionalContentTemplate>
      </bs:CollapsiblePanel>
    </ItemTemplate>
  </dot:Repeater>`

Got null reference exception in IsCollapsed value binding.

DotVVM: 1.1.8.2 (owin)

Bootstrap Controls: 1.1.2.0

**Comment by adamjez** [comment]
Thank you for reporting the bug. It will be fixed in **DotVVM.Controls.Bootstrap 1.1.7.1**
