### ISSUE TITLE
ValueBinding in Code

### ISSUE THREAD

**Issue by dotfelixb** [riganti/dotvvm#574]
What is the best way to instantiate a new ValueBindingExpression, I need to build a gridviewcolumn in code
```cs
new GridViewTextColumn { HeaderText = "Id", ValueBinding = new ValueBindingExpression() }
```
what should be pass to the  
```cs 
new ValueBindingExpression()  
``` 
or is there a better way to implement this?

**Comment by tomasherceg** [comment]
See DotVVM Dynamic Data library for an example how to do it: https://github.com/riganti/dotvvm-dynamic-data/blob/master/src/DotVVM.Framework.Controls.DynamicData/DynamicDataContext.cs

S pozdravem
Tomáš Herceg

RIGANTI s.r.o. | DOTNETCOLLEGE s.r.o. | DotVVM
www.riganti.cz | www.dotnetcollege.cz | www.dotvvm.com
________________________________

**Comment by exyi** [comment]
@tomasherceg is right, you can create a binding like this:

```C#
var properties = new object[]
{
   new BindingParserOptions(typeof(ValueBindingExpression)),
   dataContextStack,
   new OriginalStringBindingProperty(expression)
};

return new ValueBindingExpression(BindingCompilationService, properties);

```

You can get the dataContextStack from some existing control using `control.GetDataContextType()`, `BindingCompilationService` can be obtained from DI (`context.Services` or constructor injection). Also note that the initialization of binding can be pretty expansive (the expression is parsed, compiled, ...) so you are supposed to cache the instances.

**Comment by exyi** [comment]
You can also have a look at a page about the binding system - https://github.com/riganti/dotvvm-docs/blob/88693e8b8a335b8f1ced6cc7531714b30acd3af9/Pages/control-development-binding-extensibility.md

**Comment by quigamdev** [comment]
Closing this issue. If you have any question feel free to re-open it.
