### ISSUE TITLE
Handling 404 page 

### ISSUE THREAD

**Issue by marthrusk** [riganti/dotvvm#576]
I currently working on handling url adresses which are not in RouteTable. I found sample with NancyFX framework and I want to create my own custom error page. Problem is, when I define name of my view which should be rendered, my dothtml view is never found since it cannot recognize .dothtml files. 

//this should render my view
var response = viewRenderer.RenderView(context, "/Errors/" + (int)statusCode + ".dothtml");

when I changed suffix to .html, my view was found.  But I dont want to load only html pages. Is there a way how to handle this?

**Comment by marthrusk** [comment]
So I found working solution to this. its enough when I added this into webconfig 

    <httpErrors errorMode="Custom" existingResponse="Replace">
      <remove statusCode="404" subStatusCode="-1" />
      <error statusCode="404" path="call your route configured in dotvvmStartup" responseMode="Redirect"/>
    </httpErrors>

**Comment by exyi** [comment]
You can use standard Asp.Net Core error handling (https://docs.microsoft.com/en-us/aspnet/core/fundamentals/error-handling):

```C#
app.UseStatusCodePagesWithReExecute("/error/{0}");
```
