### ISSUE TITLE
.dothtml cannot be opened

### ISSUE THREAD

**Issue by Rasovsky** [riganti/dotvvm#579]
Hello,

**texteditor for .dotvvm files is broken. It cannot be opened. Here is record from ActivityLog.xml**

_<entry>
    <record>2550</record>
    <time>2018/03/12 11:31:41.006</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.MissingMethodException: Method not found: &apos;System.String Microsoft.Web.Core.Text.ITextProvider.GetText(Int32, Int32)&apos;.&#x000D;&#x000A;   at DotVVM.Integration.VisualStudio.ContentTypes.DothtmlContentTypeHandler.&lt;&gt;c__DisplayClass19_0.&lt;GetNodes&gt;b__0()&#x000D;&#x000A;   at System.Lazy`1.CreateValue()&#x000D;&#x000A;   at System.Lazy`1.LazyInitValue()&#x000D;&#x000A;   at System.Lazy`1.get_Value()&#x000D;&#x000A;   at DotVVM.Integration.VisualStudio.MarkupAnalysis.Caching.DotVVMProcessedFilesCache.&lt;&gt;c__DisplayClass8_0.&lt;AddOrUpdateFileCache&gt;b__1(String key, FileContentData oldValue)&#x000D;&#x000A;   at System.Collections.Concurrent.ConcurrentDictionary`2.AddOrUpdate(TKey key, Func`2 addValueFactory, Func`3 updateValueFactory)&#x000D;&#x000A;   at DotVVM.Integration.VisualStudio.MarkupAnalysis.Caching.DotVVMProcessedFilesCache.AddOrUpdateFileCache(String fullFileName, Lazy`1 text, Int32 version)&#x000D;&#x000A;   at DotVVM.Integration.VisualStudio.ContentTypes.DothtmlContentTypeHandler.GetNodes(ITextProvider text) in C:\dev\vs-extension\src\Extension\DotVVM.Integration.VisualStudio.VSShared\ContentTypes\DothtmlContentTypeHandler.cs:line 131&#x000D;&#x000A;   at DotVVM.Integration.VisualStudio.ContentTypes.DothtmlDirectiveProcessor.GetArtifacts(ITextProvider text, ArtifactCollection artifactCollection) in C:\dev\vs-extension\src\Extension\DotVVM.Integration.VisualStudio.VSShared\ContentTypes\DothtmlContentTypeHandler.cs:line 271&#x000D;&#x000A;   at Microsoft.Html.Core.Artifacts.ArtifactCollection.Build(ITextProvider textProvider)&#x000D;&#x000A;   at Microsoft.Html.Editor.Classification.HtmlClassifier.get_ArtifactCollection()&#x000D;&#x000A;   at DotVVM.Integration.VisualStudio.Classification.DothtmlClassifierProvider.&lt;&gt;c__DisplayClass8_0.&lt;GetClassifier&gt;b__0() in C:\dev\vs-extension\src\Extension\DotVVM.Integration.VisualStudio.VSShared\Classification\DothtmlClassifierProvider.cs:line 44&#x000D;&#x000A;   at DotVVM.Integration.VisualStudio.Classification.DothtmlClassifier.GetClassificationSpans(SnapshotSpan span) in C:\dev\vs-extension\src\Extension\DotVVM.Integration.VisualStudio.VSShared\Classification\DothtmlClassifier.cs:line 61&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Classification.Implementation.ClassifierTagger.&lt;GetTags&gt;d__5.MoveNext()&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.&lt;GetTagsForBuffer&gt;d__39.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)</description>
  </entry>_

![erroropeningdothtml](https://user-images.githubusercontent.com/15172295/37281738-4ea706b6-25f2-11e8-8212-8fa64eb037c8.PNG)

![erroropeningdothtml2](https://user-images.githubusercontent.com/15172295/37281742-50576730-25f2-11e8-81fd-fbfab4959532.PNG)

**Comment by Rasovsky** [comment]
![erroropeningdothtml](https://user-images.githubusercontent.com/15172295/37281727-47361dcc-25f2-11e8-9620-228fa27976cf.PNG)

**Comment by exyi** [comment]
VS 15.6 (the latest release) had some significant breaking changes in the API, so the only the latest dotvvm extension supports the latest release. Make sure that both your VS and DotVVM Extension is updated.

If this does not fix the issue feel free to reopen the issue
