### ISSUE TITLE
Add support for title attribute in ComboBox

### ISSUE THREAD

**Issue by adamjez** [riganti/dotvvm#583]
Currently, there is no way to render `title` attribute in option with `ComboBox`:
```html
<select>
  <option value="1" title="Desired Title">Text 1</option>
  <option value="2" title="Desired Title">Text 2</option>
</select>
```
We are using knockout.js [**options** binding](http://knockoutjs.com/documentation/options-binding.html) which lacks support of this scenario. 

Any idea how could we resolve it? @exyi @djanosik

**Comment by exyi** [comment]
On Tue, 2018-03-20 at 08:59 +0000, Adam Jež wrote:
> Any idea how could we resolve it? @exyi @djanosik 

You can hack it using foreach https://stackoverflow.com/questions/12733
430/knockoutjs-how-to-add-title-to-options-in-select
