### ISSUE TITLE
Bootstrap Reponsive Menu Collapsed glyphicon  not displaying in the button.

### ISSUE THREAD

**Issue by ssau** [riganti/dotvvm#590]
When using  <bs:ResponsiveNavigation IsResponsivelyCollapsing="true" ContainerType="Normal" > The default button floats right and to the left there is this html # 'class="icon-bar">' When you resize so the button appears its outline is to the left and displays the menu fine. When you add a  <CollapseButtonTemplate> it always displays to the left and outside the button.  It displays always.  

I have DotVVM.Controls.Bootstrap 1.1.83 along with DotVVM.Core 1.19 and DotVVM.Owin 1.1.9 installed.

**Comment by MichalTichy** [comment]
Hello, sorry, but we have not been able to reproduce this bug.
Can you please provide entire dothtml markup for ResponsiveNavigation?

If I understand correctly, you are trying to insert HTML tag a into Right/Left item template of ResponsiveNavigations.This scenario is not supported because you should always use Navigation Item as an item in responsive navigation item.

```DOTHTML
    <bs:ResponsiveNavigation IsResponsivelyCollapsing="true" ContainerType="Normal">
        <RightAlignedItemsTemplate>
            <bs:NavigationItem Text="TEST 1" NavigateUrl="http://www.google.com" />
        </RightAlignedItemsTemplate>
        <LeftAlignedItemsTemplate>
            <bs:NavigationItem Text="TEST 2" NavigateUrl="http://www.google.com" />
        </LeftAlignedItemsTemplate>
    </bs:ResponsiveNavigation>
```

**Comment by ssau** [comment]
Thanks for responding.
I paste your code into my master page and get the following results.
Larger View Port:
![larger_portal](https://user-images.githubusercontent.com/123454/38675251-f085694c-3e0b-11e8-9950-c2e3ead8231e.png)
Smaller View Port:
![smaller_portal](https://user-images.githubusercontent.com/123454/38675255-fab7f4ac-3e0b-11e8-8d23-aa6113037959.png)

Notice the extra mark up which is to the left.  In the Smaller View Port the collapsed version shows the button to the right.

I have this markup on the master page now:
@viewModel AtScore.Ko.ViewModels.MasterPageViewModel, AtScore.Ko
@import AtScore.Ko.Resources
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title>AtScore.Ko</title>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" type="text/css" href="~/Content/bootstrap.css" />
    <link rel="stylesheet" type="text/css" href="~/Content/bootstrap-theme.css" />
    <link rel="stylesheet" type="text/css" href="~/Content/Site.css" />
</head>
<body>
    <bs:ResponsiveNavigation IsResponsivelyCollapsing="true" ContainerType="Normal">
        <RightAlignedItemsTemplate>
            <bs:NavigationItem Text="TEST 1" NavigateUrl="http://www.google.com" />
        </RightAlignedItemsTemplate>
        <LeftAlignedItemsTemplate>
            <bs:NavigationItem Text="TEST 2" NavigateUrl="http://www.google.com" />
        </LeftAlignedItemsTemplate>
    </bs:ResponsiveNavigation>

   <dot:ContentPlaceHolder ID="MainContent" />



</body>
</html>

I am using:
DotVVM v1.1.9
DotVVM.Controls.Bootstrap 1.1.8.3
DotVVM.Core v1.1.9
DotVVM.Owin v1.1.9
Bootstrap v3.3.7

**Comment by ssau** [comment]
Sorry I didn't get the code in right.  Here is the markup again.
`@viewModel AtScore.Ko.ViewModels.MasterPageViewModel, AtScore.Ko
@import AtScore.Ko.Resources
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title>AtScore.Ko</title>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" type="text/css" href="~/Content/bootstrap.css" />
    <link rel="stylesheet" type="text/css" href="~/Content/bootstrap-theme.css" />
    <link rel="stylesheet" type="text/css" href="~/Content/Site.css" />
</head>
<body>
    <bs:ResponsiveNavigation IsResponsivelyCollapsing="true" ContainerType="Normal">
        <RightAlignedItemsTemplate>
            <bs:NavigationItem Text="TEST 1" NavigateUrl="http://www.google.com" />
        </RightAlignedItemsTemplate>
        <LeftAlignedItemsTemplate>
            <bs:NavigationItem Text="TEST 2" NavigateUrl="http://www.google.com" />
        </LeftAlignedItemsTemplate>
    </bs:ResponsiveNavigation>

   <dot:ContentPlaceHolder ID="MainContent" />



</body>
</html>`

**Comment by ssau** [comment]
I'll just put the file in.

[MasterPage.zip](https://github.com/riganti/dotvvm/files/1902984/MasterPage.zip)

**Comment by ssau** [comment]
@MichalTichy 
I can close this issue I figured out the issue.  
I have to use DotVVM version 1.1.8.2 instead of version 1.1.9.  So the bug is probably an incompatibility between 1.1.9 and bs 1.1.8.3.  bs 1.1.8.3 states it can use >=1.1.7 but it can't use 1.1.9 it looks like.
