### ISSUE TITLE
DataContextChange issue on commands

### ISSUE THREAD

**Issue by tomasherceg** [riganti/dotvvm#592]
I have a custom control with DotVVM property of type `Command`. I used data context change attributes on it, but it seems like they are not respected.

```
public class DraggableList : ItemsControl
{
   ...
           [ControlPropertyBindingDataContextChange(nameof(DataSource))]
        [CollectionElementDataContextChange(1)]
        public Command ItemDropped
        {
            get { return (Command)GetValue(ItemDroppedProperty); }
            set { SetValue(ItemDroppedProperty, value); }
        }
        public static readonly DotvvmProperty ItemDroppedProperty
            = DotvvmProperty.Register<Action, DraggableList>(c => c.ItemDropped, null);
   ...
}
```

```
<cc:DraggableList DataSource="{value: Tasks}"
    ItemDropped="{staticCommand: _api.ApiTasksMoveByIdPost(Id, _parent.Date)}">
```

`Id` is a property defined in `TaskDTO`.
`Date` is a property defined on an object which also declares the `Tasks` collection.

When I launch the page, I get the following exception:
![image](https://user-images.githubusercontent.com/5599524/38916718-c5ea2380-42e8-11e8-8ce2-c205923ffc6b.png)

The repro can be found in the https://github.com/riganti/dotvvm-samples-weeklyplanner repo:
- clone
- update submodules
- run Update-Database
- set launch URL to http://localhost:6806/ (it won't work on other ports as I am using Azure AD authentication)

**Comment by tomasherceg** [comment]
If that's supported on `IBinding`, that's OK and it totally makes sense. Please add the exception so this is clear.

However, when I have changed the property type to `ICommandBinding`, I am getting the following error: 

Could not find DataContextSpace of binding '{StaticCommandBindingExpression`1: _api.ApiTasksMoveByIdPost(_this.Id, _parent.Date)}'.

What is DataContextSpace? Shouldn't it be DataContextStack?

**Comment by exyi** [comment]
> Could not find DataContextSpace of binding '{StaticCommandBindingExpression`1: _api.ApiTasksMoveByIdPost(_this.Id, _parent.Date)}'.

This actually seems to be the error we were trying to prevent. It seems that you are using the binding in a different context than what it was compiled for.

> What is DataContextSpace? Shouldn't it be DataContextStack?

DataContextStack is the class that represents type of data context, space is the space where this context type is valid.

**Comment by tomasherceg** [comment]
OK, what is the correct way of using the binding in a different context?

I managed to build the target `DataContextStack` using the following code: 

```
var collectionItemTypeDescriptor = new ResolvedTypeDescriptor(GetDataSourceBinding().ResultType).TryGetArrayElementOrIEnumerableType() as ResolvedTypeDescriptor;
                var dataContextStack = DataContextStack.Create(collectionItemTypeDescriptor.Type, this.GetDataContextType());
```

Is there a nicer way to do that? Basically, I need to resolve DataContextChanges on the DataSource property.

Then I need to adjust the binding so it can work in the context of DataSource collection item. I have tried this, but apparently I need to pass another properties.

```
var command = GetCommandBinding(ItemDroppedProperty).DeriveBinding(dataContextStack);
binding.Add("onItemDropped", KnockoutHelper.GenerateClientPostBackScript(nameof(ItemDropped), command, this));
```

I am getting the following exception: `Could not resolve binding property 'DotVVM.Framework.Binding.Properties.OriginalStringBindingProperty', resolver not found.`

Is there any other control in which we are changing data context for commands? 
I have looked at GridView SortChanged property, but it doesn't change data context, it adds a string parameter to the command, which is a different case.

**Comment by djanosik** [comment]
@tomasherceg You don't need to change the binding in any way. The issue is in `DraggableList` on line [104](https://github.com/riganti/dotvvm-samples-weeklyplanner/blob/master/src/WeeklyPlanner/Controls/DraggableList.cs#L104). You are passing `this` to the `GenerateClientPostBackScript` function.  However `this` has a different data context than the binding. You need to pass a control with correct data context.

We use the following function in BP to make it working:
```c#
private DotvvmControl GetDataContextTarget(DotvvmControl control, DotvvmProperty property)
{
    var controlDataContextType = control.GetDataContextType();
    var propertyDataContextType = property.GetDataContextType(control);

    if (!Equals(controlDataContextType, propertyDataContextType))
    {
        var tempContainer = new DataItemContainer { Parent = control, DataContext = null };
        tempContainer.SetDataContextType(propertyDataContextType);
        return tempContainer;
    }

    return control;
}
```

Maybe we need a better way to avoid or handle this issue.

**Comment by tomasherceg** [comment]
@djanosik Awesome! Thank you, I haven't noticed this method. I tried to build the control using this way, but forgot to call `SetDataContextType`.

After the release of 2.0, we should document how controls are built and how to deal with bindings in these cases.

**Comment by exyi** [comment]
> OK, what is the correct way of using the binding in a different context?

The point is that it is always invalid behavior, you can't do that. You can however, as @djanosik has pointed out, create a different control with the expected data context.

> Maybe we need a better way to avoid or handle this issue.
I think that this behavior is the fundamental feature (or flaw...) of the 2.0 binding system. In case you really want to use a binding that does have a different data context that the control where it's used, I think that creating the temporary control is a reasonable cost.

**Comment by tomasherceg** [comment]
OK, the solution with a temporary control is fine, I just wanted to make sure that there is no other way meant to do that. 
We just need to describe it in the documentation.
