### ISSUE TITLE
Can't add StylesheetResource to Head, it is already rendered

### ISSUE THREAD

**Issue by djanosik** [riganti/dotvvm#595]
Some of our controls (eg. `Repeater`) are adding controls to `Children` in the `Render` method. When any of the added controls require a new resource it will fail with an exception like *"Can't add StylesheetResource to Head, it is already rendered"*.

We need to always build the control tree before the control is rendered (eg. in `OnLoad` method).

**Comment by tomasherceg** [comment]
I am afraid this is not possible - `Repeater` needs to create a dummy control so it can render the template, and even in #592 the recommended way of working with bindings is creating a dummy control (in the rendering stage).

I think that we should not throw this exception.

**Comment by djanosik** [comment]
Yes, but `Repeater` can surely create this control in `OnLoad` or `OnPreRender`. And the temporary control used in #592 is never added to children.

**Comment by tomasherceg** [comment]
Well, I don't like having dummy controls in the control tree in these stages where the user can still interact with it - from this point of view, render phase is much safer. 
But whatever - let's do this.

**Comment by djanosik** [comment]
Hmm. The solution I was thinking about won't work. Because it would break `PostBack.Update` (see [PostBackUpdateRepeater](https://github.com/riganti/dotvvm/blob/master/src/DotVVM.Samples.Common/Views/FeatureSamples/PostBack/PostbackUpdateRepeater.dothtml) sample). For this to work we need to keep server rendered items in Children after `OnPreRender` even if we do client-side rendering, right?

**Comment by djanosik** [comment]
Nevermind, it's pretty easy to solve. It will work.

**Comment by djanosik** [comment]
The PR is not yet merged. And we also need to fix this issue in GridView.

**Comment by JaskaRoman** [comment]
I have just encountered this problem in a <dot:GridView> on DotVVM.AspNetCore 2.3.1
Scenario:
Auto-registered CodeOnly control in a TemplateColumn

```
// Control
protected override void OnInit(IDotvvmRequestContext context)
{
   context.ResourceManager.AddRequiredResource("foo");
   base.OnInit(context);
}
```
