### ISSUE TITLE
GridView DataSet updated with fresh data way too late in DotVVM 2.0

### ISSUE THREAD

**Issue by Mylan719** [riganti/dotvvm#597]
I have foloving code to work with my dataset. I have sorting enabled and a datapager control on same dataset:
```csharp
public override Task Init()
        {
            if (!Context.IsPostBack)
            {
                DataSet = new GridViewDataSet<TGridDto>()
                {
                    PagingOptions =
                {
                    PageSize = 10
                },
                    SortingOptions = new SortingOptions
                    {
                        SortExpression = "Name"
                    }
                };
            }
            return base.Init();
        }

        public async override Task Load()
        {
            await ExecuteSafeAsync(async () =>
            {
                if (!Context.IsPostBack || DataSet?.IsRefreshRequired == true)
                {
                    await ReloadDataAsync();
                }
                await base.Load();
            });
        }
```
When I click on grid header to sort the entries or when I click on the pager to go to next page the change is not present in DataSet in the Load method. It does not take effect until PreRender. I remember that it was common practice to fill the grid in Load method. Isn't this a breaking change?

**Comment by tomasherceg** [comment]
This is correct and it was always like this. Data should be always loaded in PreRender.

S pozdravem
Tomáš Herceg

RIGANTI s.r.o. | DOTNETCOLLEGE s.r.o. | DotVVM
www.riganti.cz | www.dotnetcollege.cz | www.dotvvm.com
________________________________
