### ISSUE TITLE
KnockoutHelper - useless parameter

### ISSUE THREAD

**Issue by Leeemons** [riganti/dotvvm#603]
I found useless parameter `DotvvmProperty property` in extension method. What is it used for?
https://github.com/riganti/dotvvm/blob/2d8e6c1fbae2e88655817b16a56f1b6072a671b4/src/DotVVM.Framework/Controls/KnockoutHelper.cs#L49

**Comment by exyi** [comment]
It's there for historical reasons, I have just added a default value and explanation.
