### ISSUE TITLE
Static page generation - finalize this

### ISSUE THREAD

**Issue by tomasherceg** [riganti/dotvvm#607]
We should finalize the static page generation which was started more than 1 year ago. 

This would allow building serverless applications with DotVVM - static HTML files on a CDN and Azure Functions or similar technology for logic.

**Comment by exyi** [comment]
> We should finalize the static page generation which was started more than 1 year ago. 

Finalize... Maybe we could rather figure out how could this feature make any sense with the DotVVM paradigma.
Controls, ViewModels, Postbacks are build on the dynamic backend and I don't think you can go without it.

> This would allow building serverless applications with DotVVM - static HTML files on a CDN and Azure Functions or similar technology for logic. 

It could make sense to run the app on Azure function/Lambda/... In principle it could be trivial - just deploy a container with DotVVM app.

**Comment by tomasherceg** [comment]
Closing. 

Lazy CSRF tokens are already part of DotVVM 2.4, and other features that can help with static websites in DotVVM should have separate issues.
