### ISSUE TITLE
Textbox validation not working when using staticCommand

### ISSUE THREAD

**Issue by kakoskin** [riganti/dotvvm#609]
I have a textbox tied to range validation. Validation is not working when
I'm calling static command service in Changed-event. 
I'm not assigning returned value to this textbox but to other texbox. If I use command in Changed event then validation works.

**Comment by exyi** [comment]
The validation handler is turned off for staticCommands.
It is impossible to validate the view model that is not sent to server, thus staticCommands can not satisfy the contract of DotVVM validation - so we have rather turned it off entirely.


I think that it would be nice to have some other way to validate the view model with staticCommands, but it would require designing a new API...
