### ISSUE TITLE
Create HTML page for Invalid CSRF token

### ISSUE THREAD

**Issue by adamjez** [riganti/dotvvm#611]
As @exyi pointed out in https://github.com/riganti/dotvvm/pull/610#pullrequestreview-125889737 simple page with more information instead single message would be nice.

> Maybe it would be even nicer to show some more info than just "invalid token". What about a simple page that would explain that it's probably caused by new keys on the server (for devs/admins) and that it's not a big deal and you can just clear cookies (with a button to do that, for users of the broken apps)

**Comment by exyi** [comment]
This is probably unnecessary, since DotVVM can now automatically fetch new token when the validation fails. Note that it will try to do that even though the experimental feature "lazy CSRF tokens" is not enabled.
