### ISSUE TITLE
Wrong assembly name in Page.dothtml template

### ISSUE THREAD

**Issue by ppech** [riganti/dotvvm#618]
In item template for Page.dothtml is used Default namespace instead of Assembly name in @viewModel directive.

**Comment by quigamdev** [comment]
Thank you for report. This issue will be fixed in next release of extension.

**Comment by Mylan719** [comment]
I have tested creating new pages on all supported Visual Studio versions. It appears the issue  has been fixed in previous versions and is working correctly in present version of DotVVM Extension. Closing the issue. If you experience this problem again feel free to open a new issue.
