### ISSUE TITLE
Add ability to clear all validation errors from PostBack

### ISSUE THREAD

**Issue by adamjez** [riganti/dotvvm#627]
It would be nice to have an ability to clear all validation errors from `PostBack`. 

Eg. Form with a submit and cancel button. The user clicks on the submit button and gets a validation error. After that user click on the cancel button, which has `Validation.Enabled="false"` and data in the form resets and validation errors disappear.

**Comment by exyi** [comment]
I think that we can actually clear the error every time a new validation is invoked to fix this kind of problem - https://github.com/riganti/dotvvm/pull/585/files

**Comment by ENgateman** [comment]
Seems to me this issue has been fixed. Feel free to reopen it if I'm wrong.
