### ISSUE TITLE
DotVVM for Visual Studio extension creates invalid project with Business Pack controls

### ISSUE THREAD

**Issue by vstribrny** [riganti/dotvvm#632]
The generated DotVVM project (for ASP.NET Core) contains incorrect registration of Business Pack controls in DotvvmStartup for DotVVM 2. There is `config.AddBusinessPackConfiguration();` in Configure method but it should be `options.AddBusinessPack();` in ConfigureServices.

I have latest version of VS extension.

**Comment by tomasherceg** [comment]
I've just tested new project creation with Business Pack, and both OWIN and .NET Core version work for me - I think we can safely close this.

**Comment by Mylan719** [comment]
In the current version of DotVVM Extension  for Visual Studio template for  Business Pack generates configuration correctly using `options.AddBusinessPack()` as described [here](https://www.dotvvm.com/docs/tutorials/commercial-business-pack-install/2.0).
