### ISSUE TITLE
Incorrect ObsoleteAttribute annotation on ValueType property at TextBox.

### ISSUE THREAD

**Issue by vstribrny** [riganti/dotvvm#634]
Now, `ObsoleteAttribute` is specified for `TextBox.ValueType` property and says: 

> ValueType property is no longer required, it is automatically inferred from compile-time type of Text binding.

But `ValueType` property is still very useful and required when the value is bound to `Object` property. It works well: based on the `ValueType`, the text is automatically converted to Int64, Double, Datetime, String, etc.  With that said, the `ValueType` property cannot be removed in the future so I think the ObsoleteAttribute is placed there incorrectly.

I understand that if bound to strictly-typed property, the `ValueType` property does not need to be specified (I guess it is ignored in that case) - so I suggest to move the information from ObsoleteAttribute to property's `<summary>` and documentation.

**Comment by exyi** [comment]
You are right that there technically exists a case when the `ValueType` property is useful, but in most cases it's usage is redundant and may lead to strange behavior, so it's IMO better to mark it everywhere with the green squiggle. Second point is that polymorphism in view model is not supported anyway, so you are not supposed to bind anything to `System.Object`.

**Comment by vstribrny** [comment]
Just to make it clear what is my use case. I have a custom code control (derived from `ItemsControl`) and I am templating each `DataSource`'s item based on some configuration data where is also an information about data type. So I bound `TextBox`'s Text to an object and setting the `ValueType` property appropriately from control's rendering code.... Works great!
