### ISSUE TITLE
Business Pack ComboBox does not display selected value after the Repeater/GridView’s DataSource is changed

### ISSUE THREAD

**Issue by vstribrny** [riganti/dotvvm#638]
There is a `bp:ComboBox` in `dot:Repeater`. When I change a Repeater's DataSource (using Static Command Service), the selected value in ComboBox disappears.

Framework's `dot:ComboBox` works as expected in the same scenario.

See repro here: https://github.com/vstribrny/DotVVM-issues-repro/tree/master/src/BpGridViewAndMarkupControl. Just change "DataSource" ComboBox to "DataSource 2". Interesting is that the correct behavior can be reproduced when you select "Clear Items" first before changing to "Data Source 2".

**Comment by martinbojnansky** [comment]
@vstribrny Thank you for your report. We've identified the issue and it will be fixed in the next release of BusinessPack controls.

**Comment by martinbojnansky** [comment]
@vstribrny You can temporarily fix the issue by using a higher alphabet name of the SelectedValue property than the name of the DataSource property. For example: use "Number" and "SelectedNumber".

**Comment by quigamdev** [comment]
Fix for this issue should be already released. If the issue persists feel free to reopen it.
