### ISSUE TITLE
Error while trying to initialize ComboBox 's DataSource from code-behind of Markup Control

### ISSUE THREAD

**Issue by vstribrny** [riganti/dotvvm#639]
Unable to initialize `ComboBox` 's `DataSource` from code-behind of Markup Control.  `DataSource` is bound to control property. Business Pack ComboBox also does not work in this scenario. I'm Using DotVVM 2.

Please see repro here:
https://github.com/vstribrny/DotVVM-issues-repro/tree/master/src/InitComboInMarkupControl

@adamjez 's comment on gitter about this problem:

>The issue is with `ItemTextBinding` and `ItemValueBinding`. We currently expect observable value to be bound so we render `optionsText: (function(i) { return ko.unwrap(i).Text(); })`. Knockout tries to invoke Text and TypeError is thrown: `ko.unwrap(...).Id is not a function`. I'll try to fix this bug soon. IMO currently there is no workaround to this issue.

**Comment by adamjez** [comment]
@vstribrny we released new preview version **2.03-preview01-final** which contains the fix.
