### ISSUE TITLE
Setting date value using prop(e.date) creates null value

### ISSUE THREAD

**Issue by nflawson** [riganti/dotvvm#640]
I'm building a wrapper for a Bootstrap datepicker - not the one in the sample but the one available at [https://github.com/uxsolutions/bootstrap-datepicker](url) as it is more powerful.

The code for updating the ViewModel is almost exactly the same as for the sample...
```js
.on("changeDate", function (e) {
  var prop = valueAccessor();
  var val = viewModel.Enddate();
  if (ko.isObservable(prop)) {
    prop(e.date);
    }
  })
 update: function (element, valueAccessor, allBindingsAccessor, viewModel, bindingContext) {
  var value = ko.unwrap(valueAccessor());

  if (value && typeof value === "string") {
    value = toUSDate(value);
    }
  if (value) {
    $(element).datepicker("setDates", value);
    }
  }
```
Enddate in my ViewModel is a date and the locale is en-AU. 

When my ViewModel is populated the Update method sets the date in the date picker which triggers a "changedate" event. When I look at the variable 'val' before the call to prop(e,date) I see the date that came from the server in DotVVM string format. Likewise e.date is a JS Date and it is the same value as on the server. 

At the end of the "changedate" event if I go back and get the Enddate value again it is empty and the field fails validation.

I have tried converting e.date to a string, to UTC, to an ISO string, to a DOTVVM formatted string and the value is still null after the update. Am I missing something here...?

**Comment by adamjez** [comment]
Hi, I tried to reproduce the problem you are referring but I was not able to. My **BindingHandler** looks like this: https://pastebin.com/sng5KXan . Can you share full repro for us (eg. in GitHub repository)?

**Comment by tomasherceg** [comment]
DotVVM stores the dates as strings to prevent unwanted time zone conversions. There are function `dotvvm.serialization.serializeDate` for converting Date to string and `dotvvm.globalize.parseDate` to convert it back.
We also have `dotvvm.globalize.format` function that can format the date using specified locale

**Comment by nflawson** [comment]
I ham sorry for the delay, I'm only working part-time ATM.

I had already tried the Dotvvm serialization function but I tried adamjez's code and ir doesn't work. I am suspecting either that your View Model defines the dates as strings or that the en-AU globalization is affecting the data.

I can set the value using viewModel.Enddate(dotvvm.serialization.serializeDate(e.date)) and the value works but I have a couple of datepickers and so I can't do this without knowing which property of the View Model the datepicker is bound to and I haven't (yet) found a way of figuring this out dynamically.

If anyone has a working version I'd be grateful for your insights into how you made it work.

I should also mention that I am using Dotvvm V2 and AspNetCore v2.1.

The code isn't in GitHub and my organisation wouldn't like me to share too much of it, I have attached a copy of my JS and CS wrapper code and the View Model CS. 

[datepicker.zip](https://github.com/riganti/dotvvm/files/2368783/datepicker.zip)

**Comment by exyi** [comment]
>  I am suspecting either that your View Model defines the dates as strings or that the en-AU globalization is affecting the data.

You are almost right - DotVVM is storing all dates as string in Javascript in order to prevent confusion with timezones and stuff like that. If you want to access the data, you have to converting back and forth yourself. It's of course possible to do in the binding handler, like this:

```js
var prop = valueAccessor();
  if (ko.isObservable(prop)) {
    prop(dotvvm.serialization.serializeDate(e.date));
    }
  })

```
