### ISSUE TITLE
ModalDialog

### ISSUE THREAD

**Issue by hippieZhou** [riganti/dotvvm#644]
Hi，I want to implement a modal dialog box，but I want to know that how can  I use  ModalDialog by DotVVM.Framework.Controls.Bootstrap4，the package hasn't this namespace.Can you give me a demo .tks!

**Comment by quigamdev** [comment]
The namespace used in DotVVM Bootstrap4 is the same as in DotVVM Bootstrap3. It means that all controls are included in `DotVVM.Framework.Controls.Bootstrap`.

**Comment by hippieZhou** [comment]
Tks
