### ISSUE TITLE
Update default template for dotvvm Project in Visual Studio 2017

### ISSUE THREAD

**Issue by PadreSVK** [riganti/dotvvm#656]
_DotVVM for Visual Studio version 2.0.11.0_

Please replace the `services.AddDotVVM()` call in the `Startup.ConfigureServices` method with `services.AddDotVVM<DotvvmStartup>()`. 
Non-generic `services.AddDotVVM()` doesn't call `ConfigureServices(IDotvvmServiceCollection options)` from `DotvvmStartup`.

**Comment by PadreSVK** [comment]
Bug is also in CLI template dotvvm.templates.2.0.3

**Comment by Mylan719** [comment]
The issue appears to be fixed in the current version. Both in the extension and in the CLI tool.
