### ISSUE TITLE
PWA Service worker

### ISSUE THREAD

**Issue by mashbrno** [riganti/dotvvm#659]
I am curious if you're thinking about Progressive Web App (PWA) support. I'm evaluating your solution and based on what I read about DotVVM, it shouldn't be too difficult to add a quite sophisticated service worker, as lifetime of every part (pages, view models, commands, etc.) is known at compile time.

**Comment by tomasherceg** [comment]
Yesterday, we've had a discussion about this topic. 
There is one thing that prevents us from caching the pages, and that's the CSRF token - it is generated on the server-side and included in every page, however it should not be difficult to remove it and acquire it before the first postback. 
After we're done with this feature, we can try to generate a service worker and create a project template for PWAs.

**Comment by tomasherceg** [comment]
One of the DotVVM team members implemented an extension for DotVVM called DotVVM PWA which helps with implementing a service worker in DotVVM apps.
https://github.com/Rumbeer/dotvvm-pwa
We already have support for lazy-loaded CSRF tokens in the framework which allow the DotVVM pages to be safely cached.
Feel free to create a new issue if you try the DotVVM PWA implementation and find out any issues.
