### ISSUE TITLE
ValidationSummary performance

### ISSUE THREAD

**Issue by adamjez** [riganti/dotvvm#663]
`dot:ValidationSummary` can take up to **seconds** to update knockout data binding.

The issue mainly shows up when complex page contains `ValidationSummary` with complex ViewModel target and option: `IncludeErrorsFromChildren` set to `true`.  Each ViewModel deserialization in that page triggers `dotvvm.validation.getValidationErrors` lot of times.

eg.:
![image](https://user-images.githubusercontent.com/656406/51681023-b074e980-1fe3-11e9-83f0-2108eea6695c.png)

**Comment by ENgateman** [comment]
PR #729 Should fix this issue. Feel free to reopen it in case it doesn't.
