### ISSUE TITLE
Bootstrap4 / DateTimePicker - today's date is not highlighted

### ISSUE THREAD

**Issue by ppech** [riganti/dotvvm#675]
Please add highlight for today's date in Bootstrap 4 DateTimePicker.

Thanks

**Comment by MichalTichy** [comment]
Today date is highlighted (it uses dotvvm-bootstrap-DateTimePicker-today class)
![image](https://user-images.githubusercontent.com/5333577/61540027-0c717580-aa3d-11e9-92c4-2a2c23cb9f32.png)
