### ISSUE TITLE
Literal control became sealed in 2.2

### ISSUE THREAD

**Issue by vstribrny** [riganti/dotvvm#682]
I have a control derived from `DotVVM.Framework.Controls.Literal`. Upgrading to DotVVM 2.2 broke it because `Literal` control became `sealed`. Please make that class non-sealed again. What was the reason you've decided to do so?

**Comment by exyi** [comment]
We have changed how the Literal is rendered, which improves performance of pages with large Grids by tens of percent. But, it does not take inheritance into account, so we had to make it sealed.

The Literal control does not provide many extensibility point, why do you need to inherit from it?

**Comment by vstribrny** [comment]
I added there a property (something like composite/ resource key) for easier localization of texts (quite complex). I think `OnInit` is great extensibility point - there, I am setting `Text` property based on that additional property.

I think making such base control `sealed` is really bad approach.

**Comment by exyi** [comment]
I don't see why you need to use inheritance for this. `OnInit` is in every dotvvm control, IMHO you want to almost always **use** `Literal`, not **be** Literal.

**Comment by exyi** [comment]
Maybe, if you just loading the `Text` and want to preserve all the other behavior of the control, you may consider to put this logic into a binding in the `Text` (you can invoke any method from `resource` binding)

**Comment by vstribrny** [comment]
Unfortunately, I cannot use `resource` binding in my case, but thanks for a hint. Anyway, I still feel it's quite normal to inherit from a control and add there some additional properties. If it's essential for you to keep it sealed, I will try to wrap Literal control instead of inheriting it. Or, I will copy-paste it's implementation if necessary.
