### ISSUE TITLE
BusinessPack / DateTimePicker - FormatString is not assigned in CreateTimePicker()

### ISSUE THREAD

**Issue by ppech** [riganti/dotvvm#689]
In DateTimePicker from BusinessPack is missing assignment for FormatString in CreateTimePicker() method. 

I declared DateTimePicker with custom FormatString:
```html
<bp:DateTimePicker SelectedDateTime="{value: ValidFrom}" 
                   FormatString="{resource: "ddMMMyy HH:mm"}" />
```
But picker shows Hours (0-11), Minutes and AM/PM dials insted of Hours (0-23) and Minutes dials.

**Comment by martindybal** [comment]
Hi, which version of BP do you have?

**Comment by ppech** [comment]
I'm sorry, I forgot.... version is 2.1.0-preview09-final. I tested it on version 2.2.0-preview07-final, but it is the same.

**Comment by martindybal** [comment]
Thank you. I fixed, it'll be in next build
