### ISSUE TITLE
Nullable vs nonullable type in RadioButton 

### ISSUE THREAD

**Issue by martindybal** [riganti/dotvvm#692]
I have a enum TeamStatus. In viewmodel I have a property of type Nullable TeamStatus I want to use in radio button like this: 

    <dot:RadioButton Text="Active" GroupName="Status" CheckedValue="{resource: TeamStatus.Active}" CheckedItem="{value: TeamStatus}" />

But I get an exception: 

    DotVVM.Framework.Compilation.DotvvmCompilationException: CheckedItem type 'System.Nullable`1[TeamStatus]' must be same as CheckedValue type 'TeamStatus.

Is it bug or bad usage?

**Comment by exyi** [comment]
Technically, it's bad usage, the type simply has to be the same regardless any implicit conversions.

Maybe we could "fix" that, but what other conversions do we want to support? e.g. Should `CheckedValue="{resource: 'Active'}"` work as well? And `CheckedValue="Active"`?

Also, I don't really know how to implement that. Maybe we could simply try to do implicit conversion from `CheckedValue` to `CheckedItem` to  at runtime in the `RadioButton`.

**Comment by tomasherceg** [comment]
We should definitely support some implicit type conversions. I think we have `ReflectionUtils.ConvertValue` which should handle most of them and it is being used widely in the framework. We can create a similar method that would detect whether the types are compatible and can be converted implicitly, and use the method here.

**Comment by exyi** [comment]
@tomasherceg It'd not that easy, AFAIK the `CheckedValue` can be a binding and `ReflectionUtils.ConvertValue` does not handle that. We'd have to convert the binding at runtime.

**Comment by tomasherceg** [comment]
I thought that we can detect the return type of the binding at the view compilation time. Of course, it won't work if the binding type is `object`, but I don't think it is such a big deal.

**Comment by exyi** [comment]
We have agreed with @tomasherceg that we can specifically allow the case when `CheckedItem` is of type `T?` and `CheckedValue` is of type `T`. We work with boxed values anyway, so the `Nullable<T>` wrapper should not make any difference. We can't allow it in the other direction, however as that would lead to assignment of null value into a non-null property.

We will also make similar change to related control - `CheckBox` and `ComboBox` in the framework and others in BP.
