### ISSUE TITLE
FallbackLocation renders script that rewrites the whole html of current page

### ISSUE THREAD

**Issue by quigamdev** [riganti/dotvvm#702]
FallbackLocation renders script with a condition like this `condition || document.write("load html")`
In case that resource is requested via postback and not available then the whole HTML is rewritten by the script element and all content disappears. 

The rendering of this condition has to be more sophisticated. There are 2 scenarios. 
1) The resource is requested when the page is rendered by GET request.
2) The resource is requested via postback and this resource is rendered by script in dotvvm--internal

**Comment by ENgateman** [comment]
Couldn't reproduce. Issue #715 needs to get fixed before this one.
