### ISSUE TITLE
DotvvmInterrupRequestExecutionException during Redirect

### ISSUE THREAD

**Issue by daveechols** [riganti/dotvvm#707]
![image](https://user-images.githubusercontent.com/7514545/60337796-08889100-9972-11e9-824c-92192a740fe8.png)

This was discussed in Item #426, and I looked at the article written by Tomáš. As you can see by the image, I have the box unchecked for this particular exception. I also tried the alternate option suggested in the article. Visual Studio still breaks on this exception. I am using Visual Studio Enterprise 2019 version 16.1.4. I have looked through most of your code samples and do not see any examples of wrapping the Context.RedirectToRoute call in a try/catch block. This error essentially means you cannot debug a DotVVM project.  I really like the way DotVVM works, but if projects cannot be properly debugged, it makes it useless. Are there any white papers/articles on working with DotVVM in the Visual Studio debugger?

**Comment by tomasherceg** [comment]
I am sorry, we know that it is annoying, but there is no other way of doing this. 

There are two things you can do:
* Press F5 and the debugging will continue.
* Uncheck the "Enable Just My Code" item in Tools > Options > Debugging menu.

**Comment by tomasherceg** [comment]
Closing. Feel free to reopen the issue if you have additional questions or bug reports.
