### ISSUE TITLE
New OWIN..NET Project Errors

### ISSUE THREAD

**Issue by daveechols** [riganti/dotvvm#709]
I am trying to create a new OWIN .NET Framework project and am getting errors during the process. The error dialog is attached.

![DotVVM New Project Error](https://user-images.githubusercontent.com/7514545/60587226-eb810300-9d61-11e9-8bac-4d790b49b44c.png)

I am setting up the project with the BusinessPack and Bootstrap checked. When I check the Nuget installed packages, the Bootstrap and BusinessPack packages are not installed. I then add them manually. When I open the default.dothtml and the MasterPage.dotmaster and add content, the <bs:> and <bp:> namespaces are not available.

![DotVVM Bootstrap Error](https://user-images.githubusercontent.com/7514545/60587787-5121bf00-9d63-11e9-880a-3f7b40cb5b4e.png)
![DotVVM BusinessPack Error](https://user-images.githubusercontent.com/7514545/60587795-54b54600-9d63-11e9-918b-fb61f9b6dcc7.png)

**Comment by tomasherceg** [comment]
Can you please contact us at info@dotvvm.com about the NuGet package? The DotVVM feed shows only packages for which you have license - it seems that this specific version is not available to you. 

About the second issue, if the DLLs restore correctly, the Visual Studio extension should resolve the controls. Sometimes you may need to run the application so the extension will be able to load all configuration info (it needs to actually run the application).

**Comment by tomasherceg** [comment]
Does this issue still persist?

**Comment by tomasherceg** [comment]
Closing. Feel free to reopen the issue if the problem still persists.
