### ISSUE TITLE
Bindings to the Enabled property of a button within a markup control do not get rendered

### ISSUE THREAD

**Issue by jasho** [riganti/dotvvm#716]
I'm having an issue with binding a value to the Enabled property of a button which is inside of a markup control.
I have a markup control which contains 2 buttons and their respective Enabled properties are set to binding to to a control property (a DotvvmProperty). The value gets set correctly, but if it changes, it doesn't update until I reload the page.
It seems that the binding for the Enabled property doesn't get rendered as part of the knockout binding for the control from what I can see.

The sample code to reproduce this issue is:
```
<div>
    <dot:Button ButtonTagName="button"
                Text="On"
                Enabled="{value:  _control.Enabled}">
    </dot:Button>
    <dot:Button ButtonTagName="button"
                Text="Off"
                Enabled="{value: !_control.Enabled}">
    </dot:Button>
</div>
```

**Comment by ENgateman** [comment]
I attempted to reproduce this issue with a sample in the `fix/button-enabled-in-markup-controls` branch but was unsuccessful so far.

**Comment by ENgateman** [comment]
The problem was caused by a stray `RenderSettings.Mode="Server"` which caused the `dotvvmEnabled` binding to not render. Problem could be fixed either by setting `RenderSettings.Mode` to `Client` or by setting `PostBack.Update` to true.
