### ISSUE TITLE
It's not possible to have two SpaContentPlaceHolder on page

### ISSUE THREAD

**Issue by martindybal** [riganti/dotvvm#719]
It's not able to have two `SpaContentPlaceHolder` in one page. I think this is not a bug it's design decision. But I except some exception when I have a page with two `SpaContentPlaceHolder`.

**Comment by tomasherceg** [comment]
This is by design - there can be only one `SpaContentPlaceHolder` on a page. 
We should check whether a proper and meaningful exception is produced.

**Comment by acizmarik** [comment]
Resolved by #847.
