### ISSUE TITLE
Projects with samples are a mess

### ISSUE THREAD

**Issue by cafour** [riganti/dotvvm#723]
Projects containing control and feature samples are quite a mess. We should clean them up.

I propose the following renames (along with namespace changes for every class):
- `DotVVM.Samples.Common -> DotVVM.Samples`
- `DotVVM.Samples.BasicSamples.AspNetCore -> DotVVM.Samples.AspNetCore`
- `DotVVM.Samples.BasicSamples.Owin -> DotVVM.Samples.Owin`
- `EmbeddedResourceControls -> DotVVM.Samples.EmbeddedResourceControls`
- `DotVVM.Samples.BasicSamples.Api.Common -> DotVVM.Samples.Api`
- `DotVVM.Samples.BasicSamples.Api.AspNetCore -> DotVVM.Samples.Api.AspNetCore`
- `DotVVM.Samples.BasicSamples.Api.Owin -> DotVVM.Samples.Api.Owin`

**Comment by exyi** [comment]
I'd also put them into a folder called `samples`, so it's easier to navigate though the projects. I also think we could put UI tests into a separate folder.

**Comment by tomasherceg** [comment]
We should do such refactorings after release of 3.0.

Until 3.0 is out, we'll need to merge/cherry pick some fixes from 2 to 3, or back-port some things from 3 to 2, and having the same samples will make things easier.

**Comment by exyi** [comment]
I think this is pretty much what we did in #1079
