### ISSUE TITLE
Add a DependsOn attribute

### ISSUE THREAD

**Issue by ENgateman** [riganti/dotvvm#736]
Add an attribute that would let the user tell DotVVM that a ViewModel property is a transformation of one or more other properties.

It's probably best to explain why I want this feature with an example:

Let's have a ViewModel:
```csharp
public class SampleViewModel
{
    public int Id { get; set; }

    public string IdDescription => Id.ToString("0000");
}
```

While the `Id` property gets sent to the client on the first request and then only on post-backs when it changes, the `IdDescription` property gets sent to the client on every single request potentially causing a lot of expensive re-renders of controls on the client-side.

(Because the `IdDescription` property doesn't have a setter, the client never sends it back to the server, thus the server is unable to determine if it has changed.)

It would be nice to have an attribute that tells DotVVM: "Only send this property to the client if one of these other properties changes.", wouldn't it?

**Comment by exyi** [comment]
Maybe it sounds easy to implement, we can just exclude the property unless the dependencies are changed, right? Unfortunately, that not the case as (on the server) we have no idea if the property is different from the last postback (which is probably what you mean by "changed"). To know if it's changed, we'd have to send some information from the client about changed properties and that would quite non-trivial.

A viable option could be to utilize Server-side caching of viewmodels (#704) by diffing against what the client actually got. I think it already works, so you can try if it helps your workload. Of course, it only works if the viewmodel is cached on the server, but on the other hand does not require any error-prone marking by attributes.

**Comment by ENgateman** [comment]
Closing, since implementing it probably isn't worth the trouble if server-side viewmodel caching solves it. Should anyone think otherwise, feel free to reopen the issue.
