### ISSUE TITLE
Support complex binding scenarios on the class attribute

### ISSUE THREAD

**Issue by ENgateman** [riganti/dotvvm#754]
Currently there are these ways to bind the class attribute:

__`HtmlGenericControl.Attributes`__:
Binds a string value to the HTML attribute itself using `class="{value: SomeValue}"`.

__`HtmlGenericControl.CssClasses`__:
Adds `some-class` only if the `Class-some-class="{value: DisplaySomeClass}"` binding evaluates to true.

These two approaches are mutually exclusive and there's currently no way to have an element with both class constants and classes added dynamically using a binding.

Perhaps we could support these complex scenarios by finding a way to combine the two approaches or by introducing a new property (e.g. `AdditionalCssClasses` or something)?

**Comment by tomasherceg** [comment]
Let's add `AdditionalCssClasses` and also a `ValidateControlUsage` method that'll make sure the user doesn't bind to both `class` and `class-something`.
