### ISSUE TITLE
IApplicationbuilder does not contain definition for CreatePerOwinContext

### ISSUE THREAD

**Issue by malwareoverflow** [riganti/dotvvm#765]
I am just converting an existing Mvc application into .Net Core now here is the problem when creating perOwinContext

  app.CreatePerOwinContext<ApplicationUserManager>(ApplicationUserManager.Create);

because no extension method of this class IApplicationBuilder contains this method. Are there any alternatives to this in .Net Core?

I have also read this but can't figure out how to resolve this case?

[Link](https://stackoverflow.com/questions/58113262/iapplicationbuilder-does-not-contain-definition-for-createperowincontext)

**Comment by exyi** [comment]
Sorry, that not relevant here. You probably want to store the user manager in `HttpContext.Items`.
