### ISSUE TITLE
Assigning arraysin staticCommand binding never works 

### ISSUE THREAD

**Issue by Mylan719** [riganti/dotvvm#766]
I tried to to load collection of items from the server using static command. I came across an issue where **I cannot set one array to another in static command.**  
Let's have an example, first the C# viewmodel:
```CSharp
public class DefaultViewModel : DotvvmViewModelBase
{
    public List<string> Names { get; set; } = new List<string> { "Anne", "Martin" };
    public List<string> DifferentNames { get; set; } = new List<string> { "Bob", "Oliver", "Pablo" };
}
```
Notice the `staticCommand` binding. Nothing special there just simple assigment:
```html
<div>
    <dot:Button Click="{staticCommand: Names = DifferentNames }" Text="Flip lists" />
    <dot:Repeater DataSource="{value: Names}" WrapperTagName="ul">
        <li>{{value: _this}}</li>
    </dot:Repeater>
</div>
```
After clicking the "Flip lists" button 3 items appear in the repeater. The 3 items will all have the same text `[object Object]`.

Trying to get to the root of this issue we take a look at what can be seen in the html sent to the client. So we take a look at the page source in the web browser. Looking at the serialized content of `onclick` attribute of input for "Flip lists" button we can see following line:

```javascript
dotvvm.serialization.deserialize(a.$data.DifferentNames(), a.$data.Names)
```
To replicate what clicking the "Flip lists" button does we use the browser console. First we declare `var a = ko.contextFor(/*input element here*/)` and the run the above javascript line.
Content of `Names` array gets mangled in the same way as when clicking the "Flip lists" button before.

This brings me to a conclusion that there is likely a bug inside of the `dotvvm.serialization.deserialize` function.

**Comment by exyi** [comment]
This is fixed by #772.
