### ISSUE TITLE
Validation in static commands

### ISSUE THREAD

**Issue by tomasherceg** [riganti/dotvvm#767]
As we are finishing PR #757, there is now an option to support validation in static commands.

## Constraints
In order to preserve backward compatibility, the validation in static commands must be explicit. 
Also, we can validate only static command parameters - the rest of the viewmodel is not transferred to the server. 
We should support also the client-side validation and the current validator controls.

## Part 1: Validation of complex parameters
Let's assume we'll be calling the following method using a static command:

```
[AllowStaticCommand]
public int SubmitOrder(Basket basket, Address billingAddress, string notes) { ... }
```

The `Basket` and `Address` classes can implement `IValidatableObject` or contain properties with validation attributes. Until now, DotVVM didn't run validation on these parameters, so we should explicitly state we want these objects to be validated. 

There are several ways how to indicate that:
1. Create an attribute that would be applied on the parameter, e.g. `[ModelValidation] Basket basket`.
2. Add a property to the `AllowStaticCommand` attribute, e.g. `[AllowStaticCommand(ValidateParameters = true)]`

I like the first approach, but it can make the method signatures longer and difficult to read. What do you think?

## Part 2: Validation of primitive-type parameters

Some users may need to validate the parameters of primitive types. For example: 

```
[AllowStaticCommand]
public int SubmitOrder(Basket basket, Address billingAddress, [MaxLength(200)] string notes) { ... }
```

Of course, this cannot work when the method is called with an expression passed to the `notes` parameter (`{staticCommand: SubmitOrder(Basket, Address, Notes + "foo")}`) because there is no place where we could write the validation error. 

However, if a property is passed in the parameter, we may be able to support that.

## Part 3: Business rule validation

There is also a need to add errors to the model state manually. However, we'll need to decide how the property path expressions will look like. 

In classic commands, the property paths are rooted in the current validation target - e.g. `Address.CustomerName`. 

Since we may need to validate multiple parameters in static commands, we now have multiple "validation targets". When sending the property paths to the client, we'll need to add some indication of the parameter:

```
{
  "modelState": [
    {
      "propertyPath": "CustomerName",
      "errorMessage": "The customer name is required!",
      "parameterIndex": 1   // just one way of expressing this, we can use the parameter name instead, or we can include it within the propertyPath
    }
  ],
  "action": "validationErrors"
}
```

The API for generating the model state should accept the name of the parameter:

```
this.AddParameterModelError<Address>(nameof(billingAddress), "message");  // the entire object is invalid
this.AddParameterModelError<Address>(nameof(billingAddress), a => a.CustomerName, "message");   // the CustomerName property is invalid
```

This would throw an error if the parameter with such a name is not found or if the type doesn't match. 

The regular `AddModelError` method should throw an exception in this case because there is no `Validation.Target` in static commands.

## Other notes

We should also make sure that `Context.InterruptRequest` and `Context.FailOnInvalidModelState` methods work correctly - it makes sense to use them in static commands.

It's important to note that `Validation.Target` and `Validation.Enabled` properties were always ignored in static commands and it should remain that way. We should clearly state this in the docs because it is not obvious from the property names.  

I haven't thought about the REST API bindings yet, but it is not important for now - we haven't got any requests to make the validation work here. We'll make a separate issue for this when/if it becomes relevant.

**Comment by exyi** [comment]
I believe this was done in version 4.2 #1638
