### ISSUE TITLE
Failed to deserialize viewModel encrypted values

### ISSUE THREAD

**Issue by MichalOberreiter** [riganti/dotvvm#773]
Hi guys,
we decided to migrate project to DotVVM 2.x.x (none of them doesnt work) and found this issue. It worked in version 1.1.9.1 and lower.

Problem is that you can't do postback in example below:
```
public class DefaultViewModel : DotvvmViewModelBase
    {
        [Protect(ProtectMode.SignData)]
        public TypA Obj_A { get; set; } = new TypA();


        public void Postback()
        {

        }


        public class TypA
        {
            [Protect(ProtectMode.SignData)]
            public string ID { get; set; }
        }
    }
```
I know that this example doesnt make sense. 
But we have many classes with protected and unprotected properties together. And we want  to
decide with object implementation if data can be passed to unprotected properties or not.

```
[Protect(ProtectMode.SignData)]
public TypA Obj_A { get; set; } = new TypA(); //data CAN'T be passed to unprotected properties

[Protect(ProtectMode.None)]
public TypA Obj_B { get; set; } = new TypA(); //data CAN be passed to unprotected properties
```

Thanks for reply.

**Comment by exyi** [comment]
Thank you for reporting the issue, this should certainly work fine, I'll look into that.
