### ISSUE TITLE
`dotvvm.vm` alias

### ISSUE THREAD

**Issue by ENgateman** [riganti/dotvvm#795]
I hear it's quite inconvenient to write `dotvvm.viewModels.root.viewModel` all the time during development. How about we add an alias? Something like `dotvvm.vm` might be convenient enough.

**Comment by exyi** [comment]
You can trivially do that in your code, if you want to help yourself with shooting to your own leg.

We should rather remove this "API" altogether in favor of #749

**Comment by tomasherceg** [comment]
Closing - we'll focus on #749 instead of adding this alias.
