### ISSUE TITLE
Dotvvm extension is crashing Visual Studio 2019

### ISSUE THREAD

**Issue by PublicV0id** [riganti/dotvvm#807]
Hello, 

Since the last update of dotvvm extension 2.4.172.0 i get the following error when typing in a dothtml file:
"Visual Studio stopped responding. Disabling the extension DotVVM for Visual Studio  2019 2.4.172.0 might help"

Microsoft Visual Studio Enterprise 2019 Version 16.4.4
DotVVM extension 2.4.172.0

**Comment by quigamdev** [comment]
Hello @PublicV0id , 
we are working on the fix. We expect to be published by the end of this week.

**Comment by PublicV0id** [comment]
is there any news?

**Comment by quigamdev** [comment]
Sorry for the delay in getting back to you. The update was already rolled out. Just check that you have the latest version of the extension and also Visual Studio. If the issue persists, feel free to reopen this issue.
