### ISSUE TITLE
Add CancellationToken to IDotvvmRequestContext

### ISSUE THREAD

**Issue by martindybal** [riganti/dotvvm#810]
it would be nice to add CancellationToken to IDotvvmRequestContext. Similiar concept has a asp.net core mvc. 

It'll be a helper for `Context.GetAspNetCoreContext().RequestAborted`

**Comment by tomasherceg** [comment]
I've found that in OWIN there is `Context.GetOwinContext().Request.CallCancelled`. 

Since `IDotvvmRequestContext` is burdened with many things, I think that we should make this an extension method - something like `Context.GetRequestCancellationToken()`.

**Comment by exyi** [comment]
> I think that we should make this an extension method - something like Context.GetRequestCancellationToken()

This is not that easy if you want to have the extension method in `DotVVM.Frameowork` and not in the hosting assembly. You will need to get the reference to the AspNetCore/Owin to implement it, which is not possible :/

Also, adding a property to this interface should definitely wait for 3.0 If we'd have a way to make this just an extension method, we could release it faster.

**Comment by tomasherceg** [comment]
We'd need to have something like `IRequestCancellationTokenProvider` in the service provider and have particular implementations in the hosting assemblies. Then the extension method could be declared in the framework - we don't use the cancellation tokens now, but it may be useful to have it in the future.
