### ISSUE TITLE
rwhtml editor make all controls to lower case on automatic reformat

### ISSUE THREAD

**Issue by holajan** [riganti/dotvvm#82]
If I typing in inner content of Redwood control in rwhtml editor and press ENTER, automatic reformatting of this blog changes all Redwood controls elements with attributes to lower case.

For example in this code:
&lt;rw:LinkButton ID="btnObnovit" class="btn btn-primary" Click="{command: Refresh()}"&gt;
    &lt;i class="fa fa-search"&gt; CURSOR HERE Hledat&lt;/i&gt;
&lt;/rw:LinkButton&gt;
if I press ENTER inside &lt;i&gt; element, I get:
&lt;rw:linkbutton id="btnObnovit" class="btn btn-primary" click="{command: Refresh()}"&gt;
    &lt;i class="fa fa-search"&gt;
        CURSOR HERE Hledat
    &lt;/i&gt;
&lt;/rw:linkbutton&gt;
and another controls on page is lower case too.

**Comment by tomasherceg** [comment]
The latest VSIX extension (version 0.6) shouldn't do that. http://riganti.cz/download/Redwood.VS2015Extension_v0.6.zip

**Comment by holajan** [comment]
Same error behavior with this version

**Comment by tomasherceg** [comment]
In the 0.6 version of the extension, when you press Ctrl-K,D, the extension automatically fixes the casing.
However I have found that sometimes the HTML editor makes all tags lowercase. It happens when the user presses the Enter key. Can someone please verify that?

**Comment by holajan** [comment]
I wasn't using Ctrl-K,D. I was using ENTER key to split lines inside element and than the editor reformat element to lower case.

**Comment by holajan** [comment]
It seems that it working now in current version.

**Comment by tomasherceg** [comment]
Fixed.
