### ISSUE TITLE
getting url for a route name

### ISSUE THREAD

**Issue by PavelBansky** [riganti/dotvvm#821]
Hi,

is there a way to get a URL for a given route name?
Something like:

```
string url = Context.RouteToUrl("AddUser")
```

I'm doing some redirections during OAuth session and I don't want to hard code the url

Thanks!

**Comment by tomasherceg** [comment]
There should be `Context.Configuration.RouteTable["MyRoute"].BuildUrl(...)`.
It returns a virtual URL (it is in the `~/...` form because the app can run in a virtual directory) so you might need to pass the URL to `Context.TranslateVirtualPath`.

**Comment by PavelBansky** [comment]
Perfect! Thank you!
