### ISSUE TITLE
Review UI tests

### ISSUE THREAD

**Issue by cafour** [riganti/dotvvm#830]
They take so long to execute we only run them on Chrome. We should review them and streamline them a bit.

**Comment by quigamdev** [comment]
There is an option to change chrome settings to start it as headless. Maybe that could be faster. But I have to test it first.

**Comment by quigamdev** [comment]
Also, another option is to use Selenium Coordinator with the headless chrome. The coordinator allows you to run several tests in parallel on one docker-machine.

**Comment by quigamdev** [comment]
After internal discussion, we have decided that the speed of tests is not important at this moment. Tests run for 20 min. What is more important is to review use-cases that are tested and to cover unused samples and other use-cases.

**Comment by cafour** [comment]
Not sure why this stayed opened. Closing now.
