### ISSUE TITLE
Suggestion for JS translations available in command expressions

### ISSUE THREAD

**Issue by tomasherceg** [riganti/dotvvm#831]
We've talked about adding more JS translations in the command expressions, so the users can do more especially in static command bindings - e.g. manipulate with arrays and collections, dates etc.

Here are some ideas of what we can add:

## DateTime
- `Year`, `Month`, `Day`, `Hour`, `Minute`, `Second`, `Millisecond`, `DayOfWeek`, `DayOfYear`
- `AddYears(double)`, `AddMonths(double)`, `AddDays(double)`, `AddHours(double)`, `AddMinutes(double)`, `AddSeconds(double)`, `AddMilliseconds(double)`

## String
- `Format(string, params object[])`
- `Join(string, params string[])`
- `Split(char)`
- `Replace(string, string)`
- `Contains(string)`, `StartsWith(string)`, `EndsWith(string)`
- `IndexOf(string)`, `IndexOf(string, int)`, `LastIndexOf(string)`, `LastIndexOf(string, int)`

## Math functions
- `Abs(double)`, `Abs(int)`
- `Ceiling(double)`, `Floor(double)`, `Round(double, int)`
- `Min(double, double)`, `Min(int, int)`, `Max(double, double)`, `Max(int, int)`
- `Sign(double)`, `Sign(int)`

## List<T>
- `Add(T)`, `AddRange(T)`
- `First()`, `Last()`
- `RemoveAt(int)`, `RemoveRange(int, int)`
- custom extension methods `AddOrUpdateItem<TSelectorValue>(string propertySelector, TSelectorValue, T)`, `RemoveItem(string propertySelector, TSelectorValue)`
- if we could add support for lambdas, we could use x => x.Prop instead of string selector in the previous methods, and we could also add quite a lot of LINQ methods in that case (this can be phase 2)

## WebUtility
- `UrlEncode(string)`, `UrlDecode(string)`
- `HtmlEncode(string)`, `HtmlDecode(string)`

Also, there are quite a lot of methods that we could support provided we can support new types - especially `DateTimeOffset`, `TimeSpan`, maybe `Dictionary<K, V>`.

**Comment by exyi** [comment]
On 2020-05-01 17:54, Tomáš Herceg wrote:
>     DateTime
> 
>   * |Year|, |Month|, |Day|, |Hour|, |Minute|, |Second|, |Millisecond|,
>     |DayOfWeek|, |DayOfYear|
>   * |AddYears(double)|, |AddMonths(double)|, |AddDays(double)|,
>     |AddHours(double)|, |AddMinutes(double)|, |AddSeconds(double)|,
>     |AddMilliseconds(double)|

Let's hope JS's Date handles that in the same way as dotnet's DateTime.
Otherwise, this could be very problematic - days might have 23 or 25
hours, years may have 365 or 366 days, ... :(

>     String
> 
>   * |Format(string, params object[])>   * |Join(string, params string[])|

The use of Join is fairly limited without Linq, IMHO. Also, the string
functions that take a list of objects and call ToString on themselves
are quite problematic, since we can't run the same ToString client-side.

>   * |Split(char)|
>   * |Replace(string, string)|
>   * |Contains(string)|, |StartsWith(string)|, |EndsWith(string)|
>   * |IndexOf(string)|, |IndexOf(string, int)|, |LastIndexOf(string)|,
>     |LastIndexOf(string, int)|
> 
> 
>     Math functions
> 
>   * |Abs(double)|, |Abs(int)|
>   * |Ceiling(double)|, |Floor(double)|, |Round(double, int)|
>   * |Min(double, double)|, |Min(int, int)|, |Max(double, double)|,
>     |Max(int, int)|
>   * |Sign(double)|, |Sign(int)|

These should be pretty easy. I guess we can add translation for all
function in Math, for consistency.

>     List
> 
>   * |Add(T)|, |AddRange(T)|
>   * |First()|, |Last()|

Those are extension methods, and we don't support those at all. Would
you be ok calling those directly as `Enumerable.Last(list)`?

>   * |RemoveAt(int)|, |RemoveRange(int, int)|
>   * custom extension methods |AddOrUpdateItem<TSelectorValue>(string
>     propertySelector, TSelectorValue, T)|, |RemoveItem(string
>     propertySelector, TSelectorValue)|

What does the `propertySelector` do?

>   * if we could add support for lambdas, we could use x => x.Prop
>     instead of string selector in the previous methods, and we could
>     also add quite a lot of LINQ methods in that case (this can be phase 2)

Supporting lambda would probably not be even that hard, but I'm not very
convinced that it's what we want here. Certainly better than selecting
property by string, however (remember, there is Bind(Name=...) attribute
and I really don't want DotVVM features to collide with each other).

>     WebUtility
> 
>   * |UrlEncode(string)|, |UrlDecode(string)|

Should be easy.

>   * |HtmlEncode(string)|, |HtmlDecode(string)|

I'd be quite suspicious for use cases of this :] Also, it's not that
trivial to implement.

**Comment by tomasherceg** [comment]
1. Dates - although there may be some edge cases and we should investigate them, I hope that normal usages will be OK.
2. `string.Format` and `object[]` - you're right - we'd have to check the parameters and probably throw an exception if it is not a string, number or date; this is maybe not so important as it is just a syntax helper for string concatenation we can already do
3. `string.Join` - a quite common use case is having a `List<string>` property in the viewmodel and need to print it out comma-separated - now you need to use Repeater for that which involves significant overhead, or do it on the server which is not so comfortable.  
4. `Math` - I intentionally didn't include everything from Math as it is not a frequent requirement to use goniometric functions in value binding expressions - that's why I included only functions for rounding, absolute value and min/max (which are used for various distance calculation) and sign (this is not so important, it can simplify some comparison expressions). But these are easy so we can even add others.
5. Collections - I didn't know that we don't support extension methods. The propertySelector is a name of property for searching - `RemoveItem("Id", 5)` is the same thing as `RemoveAll(i => i.Id == 5)` - it is just a way to do it if we won't support lambdas.
6. `HtmlEncode` and `HtmlDecode`- I am also worried about the use cases but I could imagine some usages in combination with `string.Replace` - something like `<dot:HtmlLiteral Html="{value: HtmlTemplate.Replace("%name%", WebUtility.HtmlEncode(Name)}" />`.

**Comment by acizmarik** [comment]
There are multiple open or already closed PRs that are introducing various JS translations. However, there are still some suggestions in this issue that I am not sure whether we want to implement (`DateTime`, `DateTimeOffset`, `TimeSpan` and some methods listed as `WebUtility`). Do we want to add any of these? Or can we close this issue once all relevant PRs are closed?
