### ISSUE TITLE
Review the postback pipeline

### ISSUE THREAD

**Issue by tomasherceg** [riganti/dotvvm#835]
During imlementation of `js-modules`, we've found many small issues in the postback/staticCommand/spaNavigate pipeline.

We should review the pipeline, create some diagram that indicates all the phases, and then decide on what we'll fix. It involves making sure that errors are being caught in all the phases, and correctly propagated to the outer promise, making sure that they have all the parameters the user may need etc.

**Comment by exyi** [comment]
We have done that.
