### ISSUE TITLE
Changing Placeholder control name

### ISSUE THREAD

**Issue by holajan** [riganti/dotvvm#84]
Consider changing "Placeholder" control name to "PlaceHolder".

**Comment by TomasHubelbauer** [comment]
While this would be consistent with the WebForms control name, compound nouns are usually written as one word in English and the WebForms control is the odd one out compared to how this word in general is used in other frameworks. If this is up to community discussion, I have to say I oppose the idea.

**Comment by exyi** [comment]
Maybe it would be useful to be case-insensitive.

**Comment by tomasherceg** [comment]
It should be definitely renamed to PlaceHolder as we already have ContentPlaceHolder and SpaContentPlaceHolder with this casing.

I am also planning make the property and control names case insensitive however the default casing should be consistent.

**Comment by tomasherceg** [comment]
Fixed in 808d11b
