### ISSUE TITLE
Dotvvm Swashbuckle integration not working for .NET Core 3+ projects

### ISSUE THREAD

**Issue by vaclavnovotny** [riganti/dotvvm#842]
Since the last version DotVVM.Api.Swashbuckle.AspNetCore v2.4.0.1 has dependencies on MVC >= 2.1.0, it does not work properly in projects with MVC >= 3.*
I tried to make it work all day but without success, however, if you are certain it should work for .NET Core 3+ projects (with Host and endpoint routing), please create some sample.

I have been using documentation https://www.dotvvm.com/docs/tutorials/basics-rest-api-bindings-building-own-api/2.0 and sample https://github.com/riganti/dotvvm-samples-weeklyplanner.

**Comment by tomasherceg** [comment]
Thank you for the report, we'll investigate this. 
What's the behavior? Is there a runtime error, or some compile error?

**Comment by novotnycodestories** [comment]
I took Weeklyplanner, removed all non related functionlities (authentication, services, db..), changed target to netcoreapp3.1, updated all packages namely:

- Dotvvm.Aspnetcore -> 2.4.0.1
- Dotvvm.Api.Swashbuckle.Aspnetcore -> 2.4.0.1
- Swashbuckle.Aspnetcore -> 5.4.1

Then I replaced Webhost with Host in Program.cs, in Startup I rewrote Configure method to use Routing and Endpoints.
After all that the code compiles. However it throws runtime error on `app.UseEndpoints(builder => builder.MapControllers());` with exception with message :

`
Unable to load one or more of the requested types.
Method 'Apply' in type 'DotVVM.Framework.Api.Swashbuckle.AspNetCore.Filters.AddAsObjectOperationFilter' from assembly 'DotVVM.Framework.Api.Swashbuckle.AspNetCore, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'Apply' in type 'DotVVM.Framework.Api.Swashbuckle.AspNetCore.Filters.AddTypeToModelSchemaFilter' from assembly 'DotVVM.Framework.Api.Swashbuckle.AspNetCore, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'Apply' in type 'DotVVM.Framework.Api.Swashbuckle.AspNetCore.Filters.HandleKnownTypesDocumentFilter' from assembly 'DotVVM.Framework.Api.Swashbuckle.AspNetCore, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'Apply' in type 'DotVVM.Framework.Api.Swashbuckle.AspNetCore.Filters.RemoveBindNoneFromUriParametersOperationFilter' from assembly 'DotVVM.Framework.Api.Swashbuckle.AspNetCore, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'Apply' in type 'DotVVM.Framework.Api.Swashbuckle.AspNetCore.Filters.RemoveReadOnlyFromUriParametersOperationFilter' from assembly 'DotVVM.Framework.Api.Swashbuckle.AspNetCore, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
`
which ultimately closes the application.

**Comment by novotnycodestories** [comment]
What is interesting to me, that even when I removed `c.EnabledDotvvmIntegration()` and configure of DotvvmApiOptions, it still did not work. To make the application at least start I had to remove the nuget package Dotvvm.Api.Swashbuckle.Aspnetcore. So there are some reflections going on even when nothing from package itself is called.
