### ISSUE TITLE
Directly translated static command bindings does not raise JS dotvvm event

### ISSUE THREAD

**Issue by novotnycodestories** [riganti/dotvvm#843]
When a static command is used and is directly translated to JS (e.g. null assignment `Click="{staticCommand: SomeProperty = null}"`), then after clicking on an element with this command the event `dotvvm.events.staticCommandMethodInvoked` is not triggered. 
The event works for static commands that are creating a request to the server (e.g. `Click="{staticCommand: myStaticService.DoSomething()}`").

**Comment by exyi** [comment]
Right, this is because the method is **not** invoked, only a client-only expression is invoked. However, you can use postback handlers that are invoked.

**Comment by novotnycodestories** [comment]
I do understand, however to me it seems counter-intuitive - I just want to listen to the static command, no matter what it does. I get it - it is not the method that is being invoked but only the expression, but I would like to listen to that nonetheless and postback handlers do not make sense to me in this case, can you elaborate on that?

**Comment by exyi** [comment]
You can add a postback handler into `dotvvm.globalPostbackHandlers` and that will be triggered for every command. Or, you can register the postback handler for all controls using server side styles.
