### ISSUE TITLE
Enabling Debug in Staging environment

### ISSUE THREAD

**Issue by PavelBansky** [riganti/dotvvm#852]
I'm using multiple deployment environments (Debug, Staging, Production) with appropriate. I really like the debug-error page in DotVVM and would like to use it in Staging environment too?

I can do this in my `Startup.cs`

```csharp
public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
{
    if (env.IsDevelopment() || env.IsStaging())
    {
        app.UseDeveloperExceptionPage();
    }

    app.UseAuthentication();
    // use DotVVM
    var dotvvmConfiguration = app.UseDotVVM<DotvvmStartup>(env.ContentRootPath);
    dotvvmConfiguration.AssertConfigurationIsValid();
```

but this enables only the standard ASP.NET debug-error page. Also, this page doesn't show up when exception happens in the DotVVM Command call.

Is there a way to extended DotVVM debug-error page / behaviour to Staging environment too?

Thank you!

**Comment by exyi** [comment]
It depends if you want to switch entire DotVVM into debug configuration or only use the debug page.

1. Set `DotvvmConfiguration.Debug` to `true` in DotvvmStartup
2. The `UseDotVVM` method has an optional `useErrorPages` parameter that you can explicitly set to true:

```csharp
app.UseDotVVM<DotvvmStartup>(useErrorPages: true);
```

> Btw, the `env.ContentRootPath` should be also optional and default to this.

Feel free to reopen or create another issue if you have further questions/suggestions :)
