### ISSUE TITLE
SPA dotvvm.init is called after ready events

### ISSUE THREAD

**Issue by Sebek33** [riganti/dotvvm#861]
When using SPA, events like onload and dotvvm.events.init are called before dotvvm.domUtils.onDocumentReady (which calls window.dotvvm.init) and therefore before all is fully loaded. There is no event that is called after a full load.

Demo with notes:
[SpaDemo.zip](https://github.com/riganti/dotvvm/files/4912394/SpaDemo.zip)

**Comment by quigamdev** [comment]
@mrnustik have added `initCompleted` event in #914. I think this solves this issue.
