### ISSUE TITLE
ErrorLoggingActionFilter and dependecy injection

### ISSUE THREAD

**Issue by PavelBansky** [riganti/dotvvm#865]
I have ErrorLoggingActionFilter registered like this

```
        public void Configure(DotvvmConfiguration config, string applicationPath)
        {
            config.Runtime.GlobalFilters.Add(new ErrorLoggingActionFilter());
```

I need to use ILogger or TelemetryClient (app insight) in my ErrorLoggingActionFilter which takes ILogger as a constructor parameter.

How can I register ErrorLoggingActionFilter in order to get all dependencies injected..

Or is there another pattern to be used in DotVVM?

**Comment by tomasherceg** [comment]
Looks like it is not possible - when registering global filters, the `ServiceProvider` may not be initialized yet so it cannot produce new instances.
I'll try to look into how ASP.NET Core MVC deals with this - they have a similar situation I guess.

**Comment by tomasherceg** [comment]
Looks like there are `ServiceFilter` and `TypeFilter` attributes that can resolve a concrete filter from the DI container. We could implement those in DotVVM as well.
https://www.devtrends.co.uk/blog/dependency-injection-in-action-filters-in-asp.net-core

The easiest way for now is to request the service from `IDotvvmRequestContext` - something like `context.Services.GetRequiredService<TelemetryClient>()` and use it.

**Comment by exyi** [comment]
The action filter gets `IDotvvmRequestContext context` parameter in each method - you can use `context.Services.GetRequiredService<ILogger>()` to access your services.

Implementing the `ServiceFilter` does not solve the issue with global filters. I'd call this not a big enough deal for introducing the new API.
