### ISSUE TITLE
File Upload Files collection not set

### ISSUE THREAD

**Issue by careLearning** [riganti/dotvvm#875]
Following the guidance for the FileUpload control usage here [File Upload Control](https://www.dotvvm.com/docs/controls/builtin/FileUpload/2.0) I'm seeing a weird issue.   The content of the UploadedFilesCollection has empty/default values.   

DotvvmStartup:
   
     public void ConfigureServices(IDotvvmServiceCollection options)
     {
        options.AddDefaultTempStorages("App_Data\\temporary");
     }

View Markup:

     <div class="modalBody">
       <div class="center">
                        <dot:FileUpload AllowMultipleFiles="false"
                                        class="btn btn-cl btn-oval"
                                        NumberOfFilesIndicatorText=""
                                        SuccessMessageText=""
                                        UploadCompleted="{command: OnUploadCompleted()}"
                                        UploadButtonText="Browse"
                                        UploadErrorMessageText=""
                                        UploadedFiles="{value: Files}" />
       </div>
     </div>

View Model:

     // ctor
     public CourseViewModel(IUploadedFileStorage uploadedFileStorage)
     {
         _uploadedFileStorage = uploadedFileStorage;
         Files = new UploadedFilesCollection();
     }
     public void OnUploadCompleted()
     {
       var file = Files.Files.First();
       UploadFileDialog = false;
     }

Debugging the file results in a FileId of "00000000-0000-0000-0000-000000000000", FileName is null, FileSize is 0B, IsAllowed is true, IsFileTypeAllowed is true and IsMaxSizeExceeded is false.  However when I go to the uploadedFiles folder in App_Data\temporary I see the uploaded files. 

Please advise on what I'm doing wrong with this project.   I have this near identical code working in a different project.   I'm using a Web Forms hybrid approach targeting .NET Full Framework 4.8.
![FileUpload](https://user-images.githubusercontent.com/15213955/90515803-26debc80-e131-11ea-8b25-f9e92f00cf97.png)

**Comment by tomasherceg** [comment]
Can you please check how the `Files` collection is declared? Does it have both `get` and `set`? Also, if there is `Bind` attribute, it should be `Direction.Both`.
On the first sight, it looks like there is no setter - DotVVM cannot deserialize the values correctly.

**Comment by careLearning** [comment]
I replaced the property with the suggestion of using the bind attribute and it did have a setter.  See code block below:

        [Bind(Direction.Both)] 
        public UploadedFilesCollection Files { get; set; }

Unfortunately my file content is still incorrect.

**Comment by careLearning** [comment]
We managed to track down the offending code in **Global.asax.cs**

        void Application_Start(object sender, EventArgs e)
        {
            JsonConvert.DefaultSettings = () => new JsonSerializerSettings
            {
                ContractResolver = new CamelCasePropertyNamesContractResolver()
            };
        }

![FileIUpload_Success](https://user-images.githubusercontent.com/15213955/90680316-ad79c380-e22f-11ea-8b60-0625527a962e.png)

**Comment by tomasherceg** [comment]
Good catch, thank you for the info. It seems that DotVVM uses `JsonConvert.SerializeObject` without specifying serializer settings on some places (in the file upload middleware) and thus uses the default settings of Newtonsoft.Json.  
We'll try to fix this and release within 2.5 timeframe - a public preview should follow in a week or two.
