### ISSUE TITLE
Rename the framework to the official name

### ISSUE THREAD

**Issue by tomasherceg** [riganti/dotvvm#88]

**Comment by exyi** [comment]
I have renamed it using few string replace convenstions. You can preview it in dotvvm-rename branch
* Redwood followed by upper case letter => Dotvvm
* redwood/Redwood => dotvvm/DotVVM
* rw/Rw => dot/Dot

I was thinking about the DotVVM shortcut. <dv:Control /> looks stupid, <dvvm:Control /> is long,  you cant have dvvmhtml. I think <dot:Control /> and .dothtml is quite ok.
