### ISSUE TITLE
Default Newtonsoft.Json settings in generated REST API Bindings

### ISSUE THREAD

**Issue by acizmarik** [riganti/dotvvm#889]
We should generate code for REST API Bindings in such a way that we always explicitly pass `JsonSerializerSettings` whenever calling `JsonConvert.SerializeObject` or `JsonConvert.DeserializeObject`. This ensures consistency even when users decide to change the default serialization settings for Newtonsoft.Json

In the meantime users will be advised (in the dotvvm-docs project) to not change the default settings if they work with generated REST API Bindings.

**Comment by quigamdev** [comment]
@acizmarik PR #890 was already merged. Can we close this issue or is there something else to be solved?

**Comment by acizmarik** [comment]
There is something else to be solved. 

PR #890 fixed the issue #875. But someone might run into a similar issue when generating REST API bindings. This was not fixed and together with @tomasherceg we decided to postpone the fix. We wanted to look into other options on how to generate REST API bindings. However, this is not a change that we wanted to introduce into version 2.5

Also right now it seems that someone else run into an unrelated issue but also with generated REST API bindings #911. So it seems that there are more problems with the code generation mechanism.
