### ISSUE TITLE
Multiple statement in command binding => Error XmlHttpRequest failed, maybe internet connection is lost or url is malformed

### ISSUE THREAD

**Issue by martindybal** [riganti/dotvvm#891]
Page loads correctly without any binding error.  But when I click the button, I got "DotVVM Debugger: Error XmlHttpRequest failed, maybe internet connection is lost or url is malformed". Without `AlertIsDisplayed= true` it works.

`<dot:Button Text="Click me" Click="{command: RedirectCommand(); AlertIsDisplayed= true}" />`

```
public void RedirectCommand()
{
    Context.RedirectToRoute("RouteName");
}
```

**Comment by tomasherceg** [comment]
Note: there is no point in setting the `AlertIsDisplayed` as the redirect doesn't send the updated viewmodel to the client - it just sends the new URL. 
But still, the framework shouldn't throw HTTP 500 in such case - we need to fix this.

**Comment by acizmarik** [comment]
I could not replicate this issue. I tried DotVVM versions 2.5 and 3.1 and it seems to work correctly. Can you provide more information on how to replicate this issue?

**Comment by martindybal** [comment]
I prepare a repro for you @acizmarik. Same behavior is on DotVVM 2.5 and current version 3.1 [DotVVM891Repro.zip](https://github.com/riganti/dotvvm/files/6930592/DotVVM891Repro.zip)

**Comment by martindybal** [comment]
@acizmarik I was not able to reproduce it too. Let's close this issue, as it's more than year old. It was probably fixed
