### ISSUE TITLE
Add new supported .net framework 4.7.x

### ISSUE THREAD

**Issue by Necromant24** [riganti/dotvvm#894]

**Comment by exyi** [comment]
Hi, I'm not sure what do you mean. DotVVM support .NET 4.6.1 and netstandard2.0 both of which should run on .NET 4.7, AFAIK. Could you please share more details on what is the problem for you?

**Comment by quigamdev** [comment]
As @exyi  pointed out DotVVM supports .NET Framework 4.7.x. Without further information, we cannot solve this issue at this moment. So I am closing it for now. If the issue persists, do feel free to reopen this issue.
