### ISSUE TITLE
Extensibility point for (not only) attached properties

### ISSUE THREAD

**Issue by tomasherceg** [riganti/dotvvm#895]
Right now, we have `ActiveDotvvmProperty` that allows hooking up to `AddAttributesToRender` which is a great extensibility point - it lets anyone declare attached properties that can externally enhance any control or element. 

Unfortunately, `AddAttributesToRender` happens too late for some usages - for example, when the property needs to request an additional resource or adjust the control tree in some way.
I'd like to have some way of being able to hook a custom functionality earlier - maybe for `Init`, `Load`, and `PreRender` stages. 

Or do we have something like this? I know that a similar thing can be achieved using a decorator, but the advantage of the attached properties is that they can be applied using server-side styles.

**Comment by exyi** [comment]
There is a few problems with adding Init, Load and PreRender to attached properties.

1. When the property is added later, do we have to invoke Init retrospectivelly? Probably yes, as we do for children, but that complicates (and slows down) working with properties significantly.
2. What about when the property value is changed, should we re-evaluate Init/Load/PreRender?
3. We optimize away Init, Load and PreRender invocations on controls that do not implement these method. It would complicate a lot of thing if any control could have a property that would have this method. Also, iterating all properties on all controls takes some time.

If you'd basically like to apply decorators using server-side styles, maybe it would be less problematic to add support for that. Alternativelly, you could add a child component that will modify its parent - it feels a lot like a hack, but it's not much different from the more powerful attached property you propose.

You are right, that requesting a resource from the property is quite a common use case... I don't really know how that could be solved. If it's only a script file, you can still request it in the render phase.
