### ISSUE TITLE
Postbacks inside postbacks

### ISSUE THREAD

**Issue by tomasherceg** [riganti/dotvvm#900]
During the execution of a postback or static command, another postback/static command can be invoked (either by a postback handler or from a JS function...).

There are several combinations that can happen (postback inside postback, postback inside a static command, and so on).

We need to further investigate it. Based on what we find, we should:
* make sure it works and is covered by tests
* disable the particular combinations if they cannot be supported

**Comment by acizmarik** [comment]
This feature seems to be working as it is already used in some projects. We should cover this behaviour with tests still.

**Comment by exyi** [comment]
Tests added in #1709. It seems to work, but note that the nested postbacks must be in a different concurrency queue (regardless of the concurrency mode).
