### ISSUE TITLE
DotVVM validation improvements

### ISSUE THREAD

**Issue by MichalTichy** [riganti/dotvvm#904]
### Current state of validation:
- Validation path is relative to validation context.
This makes harder to manually add and debug validation errors.
- The current method for manually adding validation errors (AddModelError) is buggy.
- There is no way how to send back to client the changed viewmodel and the validation errors.

### Proposed solution
- Validation path should be absolute from viewmodel root.
- When the property requested by validation path could not be found, than the user should be informed in what point the path stopped corresponding with the viewmodel.
- There should be option to process command (and send modified VM to client) even when the user manually added some error.
 Maybe some alternative to Context.FailOnInvalidModelState(); ?

**Comment by acizmarik** [comment]
Already resolved in #1145
