### ISSUE TITLE
Defining Markup Control properties by directives

### ISSUE THREAD

**Issue by Mylan719** [riganti/dotvvm#909]
Properties in DotVVM are in my opinion way too bothersome to define. When extracting piece of markup into markup control more often then not viewmodel does not contain all the data that the control needs. Moreover controls that are tightly coupled with a viewmodel are harder to reuse. Therefore loose coulpling of controls and viewmodels by creating properties should be encuraged.

As it is now, to define properties for our markup control we have to also create control code behind and write a lot of boilerplate. From my expirience this discourages user from structuring their views using controls. At it's core all we need to create a property is to define a type and a name. 

I propose to implement a new directive called `@property` or `@prop`. The directive would define a property in a DotVVM markup file. A possible use in the markup control file `MyMarkupControl.dotcontrol` would look like this:

```html
@viewModel object
@property string MyProperty

<span innerText={value: _control.MyProperty}>
```
Then in another markup file you would use the control property as usual:

```html
<section>
    <MyMarkupControl MyProperty="Hello" />
    <MyMarkupControl MyProperty={value: _this.WorldAndExclamationMark} />
</section>
```

I belive this would cover most of the usecases where controls can be used. 

We had a discussion with @exyi and concluded there does not seems to be any major issue to prevent this feature from being implemented.

**Comment by tomasherceg** [comment]
We should think about the syntax for:
* default values - something like `@property string MyProperty = "hello"`
* value or binding - `@property ValueOrBinding<string> MyProperty`
* binding-only properties - `@property IValueBinding<string> MyProperty`
* content properties - `@property List<DotvvmControl> InnerControls` - but there is no way how to use this property in the markup control
* template properties - `@property ITemplate InnerTemplate` - but there is no way how to use this property in the markup control
