### ISSUE TITLE
Dotvvm Swashbuckle 2.5.0 does not generate responses in client

### ISSUE THREAD

**Issue by mirecad** [riganti/dotvvm#911]
I am using REST Api bindings for the first time (.NET Core 3.1 + all the latest Dotvvm packages). When I generate client by running dotvvm console commands "dotnet dotvvm api ...", all public methods of created client return void (or Task). Some of them should return response object.

API example:
```
        [HttpGet]
        public IEnumerable<Airport> Airports()
        {
            return SampleData.Airports;
        }
```
Should generate:
```
       [DotVVM.Framework.Configuration.RestApiRegistrationHelpers.HttpMethod("Get")]
        public System.Collections.ObjectModel.ObservableCollection<FlightFinder.Shared.Airport> Airports()
        {
            return System.Threading.Tasks.Task.Run(async () => await AirportsAsync(System.Threading.CancellationToken.None)).GetAwaiter().GetResult();
        }
```
But generates:
```
        [DotVVM.Framework.Configuration.RestApiRegistrationHelpers.HttpMethod("Get")]
        public void GetAirports()
        {
            System.Threading.Tasks.Task.Run(async () => await GetAirportsAsync(System.Threading.CancellationToken.None)).GetAwaiter().GetResult();
        }
```

Swagger JSON looks OK and I see response objects there. NSwag tool also generates correct clients.

If I use DotVVM.Api.Swashbuckle.AspNetCore 2.4.0.1 everything is fine. I made simple demo. I targeted .NET Core 2.0, because DotVVM.Api.Swashbuckle.AspNetCore 2.4.0.1 has troubles with .NET Core 3+ (see #842).

Demo - Not working 2.5.0 - https://github.com/mirecad/dotvvm-samples-flight-finder (latest master)
Demo - Working 2.4.0.1 - https://github.com/mirecad/dotvvm-samples-flight-finder/commit/fb1f252ef0e7fe858e08265ce3845271da831ab7

Steps to reproduce:
- Run FlightFinder.Api project
- run command `dotnet dotvvm api regen` in src/FlightFinder.Web folder
- check generated ApiClient.cs

**Comment by tomasherceg** [comment]
Many thanks for this repro, I'll try to look at the issue as soon as possible.
