### ISSUE TITLE
Reference errors within Telerik dlls

### ISSUE THREAD

**Issue by gabrielgc** [riganti/dotvvm#919]
I just added dotvvm to my legacy project and created a blank dothtml view to start testing but once I hit the testing page URL it starts giving System.IO.FileNotFoundException

The exception comes from some Telerik dll that has inner dependencies. But I don't use any of these functionalities that might trigger these inner dependencies, this is why I don't have several dlls. 

I managed to do a workaround by manually adding them, but this doesn't look a good solution. 
Am I missing something around the dotvvm setup ?

**Comment by tomasherceg** [comment]
By default, DotVVM scans all dependencies (including transitive ones).
If you have DotVVM 2.5, you can use the new feature Explicit Assembly Loading (place this in `DotvvmStartup.cs`):

```
// enable the feature
config.ExperimentalFeatures.ExplicitAssemblyLoading.Enable();

// add assemblies
config.Markup.Assemblies.Add("yourAssemblyName");
```

The main assembly of the web application should already be added.

**Comment by gabrielgc** [comment]
Thanks, @tomasherceg, it worked like a charm.

**Comment by tomasherceg** [comment]
Thanks for the info. Feel free to reopen the issue if you run into any problems with this feature.
