### ISSUE TITLE
IUploadedFileStorage should be in DotVVM.Core nuget package

### ISSUE THREAD

**Issue by martindybal** [riganti/dotvvm#926]
`IUploadedFileStorage` is located in `DotVVM.Framework`. I think it should move moved to `DotVVM.Core`

https://github.com/riganti/dotvvm/blob/949d3b121be46069691ad133407dc6ff0c2128b7/src/DotVVM.Framework/Storage/IUploadedFileStorage.cs

**Comment by tomasherceg** [comment]
Agree, there is also `IReturnedFileStorage`. 
I'll research if there are other things that we should move as well.

**Comment by exyi** [comment]
This was done in the #981 PR
