### ISSUE TITLE
Custom Initializer Control Property

### ISSUE THREAD

**Issue by Mylan719** [riganti/dotvvm#932]
I could use a feature that would let me register custom initializer for a control. My use case is as follows:

I would like to add a registered a resource for all my markup controls. I don't want to create code behind for every single markup control, just so that I could override `OnInit` and register my resource. I would like to use something like server side styles to register custom iaction to initialize a control for all controls that satisfy given filter condition.

This would no be hard to implement at all. Basicly we could have an internal properties like `OnInitAction`, `OnLoadAction`, `OnPreRenderAction`. And those would be run before or after `OnInit`, `OnLoad`, `OnPreRender`. I could then set those properties using Server Styles.

**Comment by tomasherceg** [comment]
The concrete use case for requesting resources will be solved by #1056.
