### ISSUE TITLE
Handle whitespace in output HTML

### ISSUE THREAD

**Issue by exyi** [riganti/dotvvm#94]
We should ignore whitespace in markup and not add lot of whitespace Literal components. Then handle the whitespace while rendering - in debug mode pretty print the result and in release mode emit minimal amount.

```
<dot:Control />
<dot:Control />
```

whould be control immediately followed by another control, not Control, literal, control

```
<dot:Control />
&nospace;
<dot:Control />
```

-> Control, Internal.NoWhitespace, Control

```
<dot:Control /><dot:Control />
```

also to Control, Internal.NoWhitespace, Control

I would use explicit `no whitespace` insted of explicit `whitespace` because you would have less of them in control tree as well as in render methods. Developers would also not add whitespace directives in rendering and the result html would not be ugly like now.

**Comment by tomasherceg** [comment]
I am afraid this won't be possible. Consider the following CSS:

```
.myClass { 
   white-space: pre-wrap; 
}
```

If you delete whitespaces in this element, the page will break:
```
<div class="myClass">
    test
        test2
</div>
```

We are not able to find out, what CSS properties will be applied to the element. So we would have to introduce a DotVVM property (something like Render.PreserveWhitespace="true") and evaluate it when we are compiling the view (I don't know if it is possible).

I don't think this is so much important for now - most of devs are looking on the HTML using some kind of DOM explorer and almost noone is displaying the generated HTML. Moreover, many HTTP servers use gzip compression, so skipping whitespace doesn't help so much.

**Comment by exyi** [comment]
We could use standard xml:space="preserve". I have found few attempts to wrap and indent in some controls but I agree it is not so important now.

**Comment by MarekPokornyOva** [comment]
Hello,
I've been playing with the framework and its extensibility and capability. I also got the idea "How to handle HTML-comments and whitespaces". And here is my solution:

```
public class DotvvmStartup : IDotvvmStartup
{
	public void Configure(DotvvmConfiguration config, string applicationPath)
	{
		ServiceLocator sl = config.ServiceLocator;
		IViewModelLoader defaultViewModelLoader = sl.GetService<IViewModelLoader>();
		sl.RegisterSingleton<IViewModelLoader>(() => new ExtViewModelLoader(defaultViewModelLoader));
	}

	class ExtViewModelLoader : IViewModelLoader
	{
		IViewModelLoader _innerLoader;
		public MyViewModelLoader(IViewModelLoader innerLoader)
		{
			_innerLoader = innerLoader;
		}

		public void DisposeViewModel(object instance)
		{
			_innerLoader.DisposeViewModel(instance);
		}

		public object InitializeViewModel(IDotvvmRequestContext context, DotvvmView view)
		{
			bool globRemoveHtmlComments=...;
			bool globRemoveWhitespaces=...;
			string temp;
			bool removeHtmlComments=(!view.Directives.TryGetValue("allowHtmlComments",out temp))||(!StringToBool(temp,globRemoveHtmlComments));
			bool removeWhitespaces=(!view.Directives.TryGetValue("allowWhitespaces",out temp))||(!StringToBool(temp,globRemoveWhitespaces));
			if (removeHtmlComments|removeHtmlComments)
				RemoveControls(view,removeHtmlComments,removeWhitespaces);

			return _innerLoader.InitializeViewModel(context,view);
		}

		void RemoveControls(DotvvmControl control,bool removeHtmlComments,bool removeWhitespaces)
		{
			DotvvmControlCollection children=control.Children;
			for (int a=children.Count-1;a>=0;a--)
			{
				DotvvmControl item=children[a];
				if (item is RawLiteral)
				{
					RawLiteral rl=(RawLiteral)item;
					string text=rl.EncodedText;
					if (text==null)
						continue;
					int textLength=text.Length;

					if ((removeHtmlComments) && //has to be configured to remove
						(textLength>6) &&
						(string.Compare(text,0,"<!--",0,4,StringComparison.InvariantCulture)==0) && //content has to starts with HTML comment
						(string.Compare(text,textLength-3,"-->",0,3,StringComparison.InvariantCulture)==0) && //content has to ends with HTML comment
						(!((textLength>8)&&(string.Compare(text,4," ko ",0,4,StringComparison.InvariantCulture)==0))) && //mustn't be a KO expression start <!-- ko text: Title -->
						(!((textLength==12)&&(string.Compare(text,4," /ko ",0,5,StringComparison.InvariantCulture)==0)))) //mustn't  be a KO expression end <!-- /ko -->
					{
						children.Insert(a+1,new RawLiteral("","",rl.IsWhitespace));
						children.RemoveAt(a);
						continue;
					}

					if (removeWhitespaces)
					{
						string textNew=text.Trim();
						if (textLength!=textNew.Length)
						{
							children.Insert(a+1,new RawLiteral(textNew,textNew,rl.IsWhitespace));
							children.RemoveAt(a);
						}
					}
				}
				else
					RemoveControls(item,removeHtmlComments,removeWhitespaces);
			}
		}

		bool StringToBool(string value,bool defaultValue)
		{
			if ((value=="1")||(string.Equals(value,"true",StringComparison.InvariantCultureIgnoreCase)))
				return true;
			if ((value=="0")||(string.Equals(value,"false",StringComparison.InvariantCultureIgnoreCase)))
				return false;
			return defaultValue;
		}
	}
}
```

Of course it would be better to hook somewhere into DefaultViewCompiler.CompileView() or so but that isn't extendable or I haven't found a way.

Marek

**Comment by exyi** [comment]
1. This should be possible to inject into compiler using something called Styles, but it is not documented, since I don't consider the API stable.
2. You can't just remove all whitespaces in the page, because it could break some code. for example `<b>first part</b> <a>second part</b>` behave differently when you remove the space between `</b>` and `<a>`. And it can be much more complicated as @tomasherceg has shown in his post here.
3. I also wanted to auto-indent rendered elements for better readability.

However this is fairly complicated (and the validation issue too), so I'd like to meet you and discuss that personally. Could you please send us email or whatever where we could meet?

**Comment by quigamdev** [comment]
Closing as outdated.

**Comment by exyi** [comment]
How is this issue outdated? It's not an technical issue but a principial one, there is no way this could become outdated. It's also not solved in any other way. I'm not sure if we want to do that, but that's the reason why it's in the Future milestone.

**Comment by exyi** [comment]
>  I think that most web devs use Dev Tools way more frequently than View Source, so it doesn't matter how the output looks like

Devtools don't show you what was returned by the server, but what is in the DOM, which can be different. Especially in cases you have a bug somewhere, when you want to debug what's inside a grid that is not rendering, you can't use devtools...

> The unnecessary spaces are not a problem when gzip compression is used - the difference will be very small

5% gzipped, 10% ungzipped - by a quick adhoc measurement

> Moreover, third-party services like CloudFlare can remove HTML comments and other things from the output.

Including the comments, so you have to turn them off, always.

> This issue is 2 years old - I would close it because chances that we are implementing it are low

Yes, and we can also close all the other issues as well using the same logic. Moreover, when we close them the probability of implementation decreases even more, so there is really not any reason to keep them open... Not even mentioning that the issue DotVVM solves in general is more that 3 years old :P

**Comment by tomasherceg** [comment]
So what do you suggest? Keep this issue open? Do you have some specific ideas how to implement this?
