### ISSUE TITLE
Automated build and tests with GitHub Actions

### ISSUE THREAD

**Issue by aleks-ivanov** [riganti/dotvvm#945]
A simple GitHub Actions workflow to validate the build and tests processes each time a push commit is made or a PR is created.

Built with ❤ by [Pipeline Foundation](https://pipeline.foundation).

**Comment by aleks-ivanov** [comment]
> @quigamdev Github action test results would be available publicly, not only to RIGANTI.

@exyi That is true and that is just one of the benefits of using GitHub Actions.

To the visibility of CI data to users and contributors, I would add also several security and quality features that GitHub offers to open source projects for free like secrets vault, Dependabot, CodeQL etc. Also on top of that seamless extensibility for GitHub releases and tagging, automated NuGet publishing and more.

We would gladly contribute to the project with any or all of those features promptly, so please let us know if you are interested. 🙂

**Comment by quigamdev** [comment]
Ah, my bad, I thought that it has something to do with automation on another platform. I do understand the benefits of opening testing results to the public via GitHub Actions. I think it is a good idea. But just the results of build and tests. I will look at whether we can provide results to the public somehow from our DevOps. Still, I do not think that running concurrent pipelines make sense.
