### ISSUE TITLE
Multilanguage problem

### ISSUE THREAD

**Issue by daltinkurt** [riganti/dotvvm#953]
I'm trying to make a site with multilanguage support.

I couldn't understand how to manage two resx file.

for example: GlobalRes.**en-US**.resx and GlobalRes.**tr-TR**.resx (English and Turkish)

I'm using **presenterFactory** in **DotvvmStartup.cs**, 
how can I get the values from **GlobalRes.en-US.resx** if the active language is English, and from **GlobalRes.tr-TR.resx** if Turkish.

on the other hand,
When I use the localization mechanism of the .net core, I get an error "Assembly with same name is already loaded" after changing the language.

thanks.

**Comment by tomasherceg** [comment]
Can you provide a full stack trace for the exception? I haven't seen any of these.
The naming of resource files should be correct, but I believe there should be one default resource `GlobalRes.resx` and then specific resource files for non-default languages. 

Can you try the following sample? I've added a demonstration of RESX files and it works there.
https://github.com/riganti/dotvvm-samples-request-localization

**Comment by daltinkurt** [comment]
thanks for quick reply
I think, i forgot to add default resx file :(
sorry for this post

**Comment by tomasherceg** [comment]
No need to apologize, we're happy that we found the problem. :-)
