### ISSUE TITLE
DotVVM cannot load

### ISSUE THREAD

**Issue by neumatho** [riganti/dotvvm#959]
I have spent some time reading about DotVVM and I'm really impressed. It sounds like it could be something we can use to migrate our old ASP.NET Web forms application. I will then try it out and installed the extension via extension manager. That went fine, but when I start Visual Studio, a popup message shows:

"The 'DotvvmPackage' package did not load correctly."

I'm using Visual Studio Professional 16.9.0.
I also have Resharper installed, tried to disable that, but that didn't help.

In the activity log, mentioned in the dialog, it says:

`SetSite failed for package [DotvvmPackage]Source: 'System.ComponentModel.Composition' Description: The composition produced multiple composition errors, with 2 root causes. The root causes are provided below. Review the CompositionException.Errors property for more detailed information. 1) No exports were found that match the constraint: 	ContractName	DotVVM.Integration.VisualStudio.Dialogs.DialogFactory	RequiredTypeIdentity	DotVVM.Integration.VisualStudio.Dialogs.DialogFactory Resulting in: Cannot set import 'DotVVM.Integration.VisualStudio.VsPackages.DotvvmPackageDependencies.DialogFactory (ContractName="DotVVM.Integration.VisualStudio.Dialogs.DialogFactory")' on part 'DotVVM.Integration.VisualStudio.VsPackages.DotvvmPackageDependencies'. Element: DotVVM.Integration.VisualStudio.VsPackages.DotvvmPackageDependencies.DialogFactory (ContractName="DotVVM.Integration.VisualStudio.Dialogs.DialogFactory") -->  DotVVM.Integration.VisualStudio.VsPackages.DotvvmPackageDependencies 2) No exports were found that match the constraint: 	ContractName	DotVVM.Integration.VisualStudio.Common.Licensing.ILoginProvider	RequiredTypeIdentity	DotVVM.Integration.VisualStudio.Common.Licensing.ILoginProvider Resulting in: Cannot set import 'DotVVM.Integration.VisualStudio.VsPackages.DotvvmPackageDependencies.LoginProvider (ContractName="DotVVM.Integration.VisualStudio.Common.Licensing.ILoginProvider")' on part 'DotVVM.Integration.VisualStudio.VsPackages.DotvvmPackageDependencies'. Element: DotVVM.Integration.VisualStudio.VsPackages.DotvvmPackageDependencies.LoginProvider (ContractName="DotVVM.Integration.VisualStudio.Common.Licensing.ILoginProvider") -->  DotVVM.Integration.VisualStudio.VsPackages.DotvvmPackageDependencies
`

-Thomas

**Comment by tomasherceg** [comment]
Thanks for the feedback. We'll publish the new version of VS extension very soon - VS 16.9 changes some APIs the extension relies on. 
Right now you should be able to use the version 2.5.249.0 which can be downloaded from here: https://www.dotvvm.com/docs/tutorials/commercial-dotvvm-for-visual-studio-release-notes/2.0
