### ISSUE TITLE
Conditional inclusion of bolean attributes

### ISSUE THREAD

**Issue by Mylan719** [riganti/dotvvm#961]
When constructing a modern HTML UI it is in many cases necessary to indicate a state change and other additional HTML tag properties by including or excluding an attribute completely. 
At present we can control a value of a HTML an attribute using bindings.
However it is not possible to control if the attribute present or not.
We need a solution to allow for a standard collapsible detail control and other similar applications:
```html
<detail>
   <summary>...<summary>
<detail>
```
to open the summary:
```html
<detail open>
   <summary>...<summary>
<detail>
```
Proposed Dothtml syntax to archieve this:
```xml
<detail Attr-open={value: IsOpen}>
   <summary>...<summary>
<detail>
```
We already have the infrastructure in place for property groups to make this work.

**Comment by exyi** [comment]
this was resolved by #1028

In short, you can just use `open={valid: IsOpen}`
