### ISSUE TITLE
Redirect immediality

### ISSUE THREAD

**Issue by daltinkurt** [riganti/dotvvm#963]
is that normal?

```
...
context.RedirectToRoute(url);
// why comes here?
```

How can I make it go directly to the link I want?

**Comment by tomasherceg** [comment]
I am afraid I don't understand - can you describe the problem in more detail?

In general, `context.Redirect*` is used to make a redirect from postbacks. 
It throws an exception (that is caught via DotVVM) so the code after that is not executed.

If you want just to create a link to another page, you can use `<a href="...">` or better `<dot:RouteLink RouteName="Something" Param-par1="value" />` etc.

**Comment by exyi** [comment]
Without further information we won't be able to provide any help. I'm closing this for now, feel free to reopen later.
