### ISSUE TITLE
Attribut InnerText doesn't display any text when rendering on Server

### ISSUE THREAD

**Issue by spiritak** [riganti/dotvvm#97]
Simply writing this
```
<p InnerText="{value: Whatever}" RenderSettings.Mode="Server"/>
```
doesn't render anything. 
Expected behaviour is rendered content of Whatever inside element p.
Client rendering works as expected.

**Comment by exyi** [comment]
@tomasherceg wanted to remove this property. I'll fix it, but it may get removed.

**Comment by tomasherceg** [comment]
The property InnerText can stay in the framework, however we should allow it only on HTML elements or on controls which can handle it. Most of them ignores it now.
