### ISSUE TITLE
System.NullReference object not set to an instance of an object in dotvvm Visual Studio extension

### ISSUE THREAD

**Issue by zacuke** [riganti/dotvvm#973]
This happens every time we open a dothtml file. Visual studio shows the yellow bar as 
 we begin typing. Probably something in our page mark-up, but it's not clear what we need to change to get the extension to stop crashing. 

VS2019 16.9.1
dotvvm extension 2.5.250.0
```


System.NullReferenceException: Object reference not set to an instance of an object.   at DotVVM.Integration.VisualStudio.Classification.DothtmlClassifierProvider.<>c__DisplayClass14_0.<GetClassifier>b__0() in C:\dev\vs-extension\src\Extension\DotVVM.Integration.VisualStudio.VSShared\EditorClassification\DothtmlClassifierProvider.cs:line 57   at DotVVM.Integration.VisualStudio.Classification.DothtmlClassifier.GetClassificationSpans(SnapshotSpan span) in C:\dev\vs-extension\src\Extension\DotVVM.Integration.VisualStudio.VSShared\EditorClassification\DothtmlClassifier.cs:line 63   at Microsoft.VisualStudio.Text.Classification.Implementation.ClassifierTagger.<GetTags>d__5.MoveNext()   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.<GetTagsForBuffer>d__47.MoveNext() --- End of stack trace from previous location where exception was thrown ---   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
--




```
![image](https://user-images.githubusercontent.com/2529117/111193215-ef7da480-8587-11eb-9ce7-3ffa141a14ee.png)

**Comment by zacuke** [comment]
For what it's worth, we moved all of our javascript and CSS into separate files (previously inside <script> and <style> tags on hte dothml page), and it cleared this up

also cleared up a stalling issue we were having.

**Comment by quigamdev** [comment]
Thank you for reporting this issue. I going to investigate why this happened and release a fixed version as soon as possible.

**Comment by zacuke** [comment]
A little background if you are curious, we have an old Web Forms application with about 2000 files. I've started to introduce and re-write old web forms pages as Dotvvm pages, hoping someday the whole app can be flipped over to .net 5.0 or greater.

I create a new project from dotvvm template, and started to paste in code.  It might be related to the usage of {{ resource }} inside a <script> tag, as this is starting to lag as I scroll the window, and you can see the javaScript syntax coloring is not working past the {{ resource}} tag

![image](https://user-images.githubusercontent.com/2529117/111875604-abfcaf00-8968-11eb-95c5-b337805ad78f.png)
