### ISSUE TITLE
lambda in staticCommand can not pass arguments to server methods

### ISSUE THREAD

**Issue by exyi** [riganti/dotvvm#980]
`{staticCommand: (int x) => s.Method(x)}` produces invalid expression - the argument is declared after the `Method` is invoked, which leads to JS error.

**Comment by tomasherceg** [comment]
We need to do this change in DotVVM 4.0 because it depends on dropping the support for IE11 (we need to use async/await in JS expressions).

**Comment by quigamdev** [comment]
Since we have rewritten promises to async/await calls, we should add tests for this case.
