### ISSUE TITLE
Do not use iframe in FileUpload

### ISSUE THREAD

**Issue by OronDF343** [riganti/dotvvm#984]
Hi,

I need to add the option to upload a file in a form.
The built-in FileUpload control renders an invisible iframe, which means that it does not work in our environment, because the server always returns the header "X-Frame-Options: DENY" due to security requirements which are non-negotiable.
1. Is it possible to change FileUpload so it does not require the use of an iframe? (In general, iframes are not ideal. AJAX could and should be used instead today)
2. Is there an alternative method to upload files in DotVVM? (I also have another issue with the built-in control so it makes sense)

Thanks

**Comment by tomasherceg** [comment]
Thanks for the feedback. I think that it is possible to write a FileUpload control that is not using iframe, but it wouldn't work in IE11 (which we still support for some customers).

Basically, you need to implement a control which renders `input[type=file]`, and inject the script from here: https://github.com/riganti/dotvvm/blob/main/src/DotVVM.Framework/Controls/FileUploadPageTemplate.tt 

I can try to implement the control in [DotVVM contrib](https://github.com/riganti/dotvvm-contrib) repo, but I am quite busy so it may take a few days.

**Comment by tomasherceg** [comment]
I've played with this a little, and found out that uploading files in AJAX works even in IE11, so we can get rid of the iframe. 

I've implemented a prototype here: https://github.com/riganti/dotvvm-contrib/blob/master/Controls/FileUploadNoIframe/readme.md

I haven't made a NuGet package with this control yet - what version of DotVVM are you using? I'll publish the package that will match your version so you can try it.

**Comment by OronDF343** [comment]
I am using version 2.5.2. Thanks!
