### ISSUE TITLE
FileUpload.AllowMultipleFiles = false does not prevent the user from uploading multiple files

### ISSUE THREAD

**Issue by OronDF343** [riganti/dotvvm#985]
Setting `FileUpload.AllowMultipleFiles = false` prevents the user from selecting multiple files at once, but does not prevent them from selecting another file after the first one is done uploading.

I was able to work around the issue like this:
View
```
<dot:FileUpload html:id="Files" UploadedFiles="{value: Files}" AllowedFileTypes="image/*,application/pdf" AllowMultipleFiles="false" UploadCompleted="{command: OnFileUploaded()}" Validation.Enabled="false" />
```
ViewModel
```
// Both assigned by the constructor
private readonly IUploadedFileStorage _storage;
public UploadedFilesCollection Files { get; set; }

public void OnFileUploaded()
{
    if (Files.Files.Count > 1)
    {
        var want = Files.Files.Last();
        foreach (var f in Files.Files.Take(Files.Files.Count - 1))
            _storage.DeleteFile(f.FileId);
        Files.Files.Clear();
        Files.Files.Add(want);
        return;
    }
}

// IMPORTANT: When the form is submitted, the number of files needs to be checked (before checking UploadedFile.IsAllowed)
```
(Note that `Validation.Enabled="false"` is required to make this work regardless of the state of other validation in the page.)

I don't think that this workaround is ideal as it causes a postback, rather than it being part of the actual upload process. Also, this method isn't obvious to the user.

**Comment by tomasherceg** [comment]
Thanks for reporting this. 
I am not sure if we can change the behavior (it may be a breaking change). I agree that the naming of the property could be better, but it is just a wrapper on the `multiple` attribute on `input[type=file]` - it means that it's possible to select multiple files in the dialog at the same time. 
We'll discuss internally with the team.
