### ISSUE TITLE
RouteLink with null parameter

### ISSUE THREAD

**Issue by martindybal** [riganti/dotvvm#997]
```
<div IncludeInPage="{value: Id != null}" RenderSettings.Mode="Server">
    <dot:RouteLink RouteName="RouteWithParameter" Param-id="{value: Id}" Text="RouteLink with null parameter" />
</div>
```

```
config.RouteTable.Add("RouteWithParameter", "RouteWithParameter/{id:guid}", "Views/Default.dothtml");
```

`System.ArgumentNullExceptionValue cannot be null. (Parameter 'Could not build route, parameter 'id' is null')`

**Comment by tomasherceg** [comment]
We cannot fix this - if we substitute an empty value to a required parameter, it could point to a different route. 
You can use something like this: `Param-id="{value: Id ?? "something"}"`
